#!/usr/bin/env python3
"""Build checksum-bound Kuwait production sources."""
import hashlib,json
from pathlib import Path
from model import ROOT,SCHEMA_VERSION,write_json
IMPORT=ROOT/'data/imports/kuwait'; MANIFEST=IMPORT/'snapshot_manifest.json'; RETRIEVED='2026-08-16'; DEPTH_RETRIEVED='2026-09-20'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def digest(p): return 'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 m=load(MANIFEST)
 for r in m['records']:
  p=ROOT/r['path']; b=p.read_bytes()
  if len(b)!=r['bytes'] or hashlib.sha256(b).hexdigest()!=r['sha256']: raise SystemExit('Kuwait fixture checksum changed: '+r['path'])
 census='data/imports/kuwait/fixtures/census_governorates_2021.json'; whc='data/imports/kuwait/fixtures/world_heritage_scope_2026.json'; depth='data/imports/kuwait/fixtures/cultural_depth_2026.json'
 rows=[
 {'id':'SRC-KW-CSB-CENSUS-GOVERNORATES-2021','title':'Kuwait Registration Census 2021 — population by governorate','publisher':'Central Statistical Bureau','source_type':'census','url':'https://census.csb.gov.kw/Census_Gov','archive_url':None,'publication_date':None,'retrieved_at':RETRIEVED,'license':'Kuwait government statistical publication; factual extraction with attribution; reuse terms not stated','language':'ar-en','country_codes':['KW'],'locator':'downloadable Table 1/chart: six governorates, Not Stated row, and total population','checksum':digest(ROOT/census),'quality_tier':'A','notes':'Checksum binds the reconciled exact table fixture. Publication date unavailable. Census index identifies the registration census as 2021; year precision is normalized to 2021-01-01. Differing prominent widgets are excluded; table/chart rows reconcile exactly to total with Not Stated.'},
 {'id':'SRC-KW-CSB-CENSUS-METHODOLOGY-2021','title':'Kuwait Registration Census 2021','publisher':'Central Statistical Bureau','source_type':'official_report','url':'https://census.csb.gov.kw/index','archive_url':None,'publication_date':None,'retrieved_at':RETRIEVED,'license':'Kuwait government statistical publication; factual extraction with attribution; reuse terms not stated','language':'ar','country_codes':['KW'],'locator':'heading and methodology paragraphs identifying the first registration census of Kuwait 2021 and total 4,385,717','checksum':digest(ROOT/census),'quality_tier':'A','notes':'Checksum binds the structured census fixture cross-checked against the official index. Publication date unavailable.'},
 {'id':'SRC-UNESCO-WHC-KW-2026','title':'World Heritage List — Kuwait State Party','publisher':'UNESCO World Heritage Centre','source_type':'institutional_dataset','url':'https://whc.unesco.org/en/statesparties/kw','archive_url':None,'publication_date':None,'retrieved_at':RETRIEVED,'license':'CC BY-SA 3.0 IGO for property descriptions','language':'en','country_codes':['KW'],'locator':'State Party summary: 0 inscribed properties and 6 tentative-list sites','checksum':digest(ROOT/whc),'quality_tier':'A','notes':'Checksum binds exact inscribed/tentative counts. Publication date unavailable on live State Party page; tentative sites are not treated as inscribed.'},
 {'id':'SRC-KW-UNESCO-ICH-2026','title':'Elements on the Lists — Kuwait State Party','publisher':'UNESCO Intangible Cultural Heritage','source_type':'institutional_dataset','url':'https://ich.unesco.org/en/state/kuwait-KW?info=elements-on-the-lists','archive_url':None,'publication_date':None,'retrieved_at':DEPTH_RETRIEVED,'license':'UNESCO ICH pages; factual extraction with attribution','language':'en','country_codes':['KW'],'locator':'inscribed elements: Al Sadu 2025 ref 02158, Bisht 2025 ref 02233, The Diwaniya 2025 ref 02281, Henna 2024 ref 02116, Date palm 2022 ref 01902, Al Sadu Educational Programme 2022 ref 01905, Arabic calligraphy 2021 ref 01718','checksum':digest(ROOT/depth),'quality_tier':'A','notes':'Publication date unavailable on the live State Party list page. Only elements on which Kuwait appears are imported; multi-State files stay shared and never exclusive. Element descriptions come from the same UNESCO element pages.'},
 {'id':'SRC-KW-DIALECT-MIRROR-2026','title':'لهجة كويتية — موسوعة مرآة','publisher':'ويكيبيديا العربية (نسخة مرآة)','source_type':'local_website','url':'https://ar.wikipedia.org/wiki/%D9%84%D9%87%D8%AC%D8%A9_%D9%83%D9%88%D9%8A%D8%AA%D9%8A%D8%A9','archive_url':None,'publication_date':None,'retrieved_at':DEPTH_RETRIEVED,'license':'CC BY-SA 4.0 for the mirror text','language':'ar','country_codes':['KW'],'locator':'sections: تصنيف اللهجة إلى ست لهجات (جبلة/شرق/فيلكا/الجهراء/الفنطاس/الدمنة) والفونولوجيا وجدول المفردات بمعانيها','checksum':digest(ROOT/depth),'quality_tier':'E','notes':'Publication date unavailable on the mirror. Depth-cycle tier-E mirror: dialect profiles and glossed words enter as local_reported and unpublished, never as verified facts.'},
 {'id':'SRC-KW-DIALECT-LOANS-2026','title':'ظاهرة قلب الحروف وإبدالها في اللهجة الكويتية','publisher':'تاريخ الكويت (أرشيف محلي)','source_type':'forum','url':'https://www.kuwait-history.net/vb/archive/index.php/t-1909.html','archive_url':None,'publication_date':None,'retrieved_at':DEPTH_RETRIEVED,'license':'Local heritage forum archive; factual extraction with attribution; reuse terms not stated','language':'ar','country_codes':['KW'],'locator':'articles on replacement phenomena and the list of words of Persian, Turkish, Indian, and English origin','checksum':digest(ROOT/depth),'quality_tier':'E','notes':'Publication date unavailable in the archive view. Tier-E local heritage material: loan etymologies stay local_reported and unpublished and are never stated as certain origins.'},
 {'id':'SRC-KW-CUISINE-MIRROR-2026','title':'مطبخ كويتي — موسوعة مرآة','publisher':'ويكيبيديا العربية (نسخة مرآة)','source_type':'local_website','url':'https://ar.wikipedia.org/wiki/%D9%85%D8%B7%D8%A8%D8%AE_%D9%83%D9%88%D9%8A%D8%AA%D9%8A','archive_url':None,'publication_date':None,'retrieved_at':DEPTH_RETRIEVED,'license':'CC BY-SA 4.0 for the mirror text','language':'ar','country_codes':['KW'],'locator':'sections: أشهر الأكلات الكويتية وأشهر الحلويات الكويتية with the per-dish descriptions','checksum':digest(ROOT/depth),'quality_tier':'E','notes':'Publication date unavailable on the mirror. Dish knowledge enters as local_reported and unpublished; Gulf-shared dishes keep classification shared.'},
 {'id':'SRC-KW-DRESS-HERITAGE-2026','title':'مسميات للملابس النسائية في الكويت قديمًا','publisher':'وكالة الأنباء الكويتية (كونا) عبر أرشيف تاريخ الكويت','source_type':'local_press','url':'https://www.kuwait-history.net/vb/archive/index.php/t-6051.html','archive_url':None,'publication_date':'2008-09-14','retrieved_at':DEPTH_RETRIEVED,'license':'Local heritage archive reproducing a Kuna report; factual extraction with attribution','language':'ar','country_codes':['KW'],'locator':'Kuna report of 2008-09-14 quoting researchers on الدراعة والنفنوف والبخنق والبوشية والثوب وأنواعها','checksum':digest(ROOT/depth),'quality_tier':'E','notes':'The archive copy carries the original Kuna date; dress entries stay local_reported and unpublished.'},
 {'id':'SRC-KW-KUNA-FIRJAN-2017','title':'فريج المطبة.. أحد أشهر فرجان الكويت قديمًا','publisher':'وكالة الأنباء الكويتية (كونا)','source_type':'local_press','url':'https://www.kuna.net.kw/NewsAgenciesPublicSite/ArticleDetails.aspx?id=2607422','archive_url':None,'publication_date':'2017-04-27','retrieved_at':DEPTH_RETRIEVED,'license':'State news agency report; factual extraction with attribution','language':'ar','country_codes':['KW'],'locator':'the four historic quarters of Kuwait City, the فريج/سكة structure, فريج المطبة boundaries and neighbours, and the naming explanation attributed to Dr Abdullah Al-Ghunaim','checksum':digest(ROOT/depth),'quality_tier':'B','notes':'State news agency reporting with named researchers and a cited book; historical quarters remain historical places, never current administrative units.'},
 {'id':'SRC-KW-MIRQAB-HERITAGE-2026','title':'صور من عبق أحياء المرقاب — تاريخ وشخصيات','publisher':'تاريخ الكويت (أرشيف محلي)','source_type':'heritage_book','url':'https://www.kuwait-history.net/vb/archive/index.php/t-13665.html','archive_url':None,'publication_date':None,'retrieved_at':DEPTH_RETRIEVED,'license':'Local heritage archive article; factual extraction with attribution; reuse terms not stated','language':'ar','country_codes':['KW'],'locator':'listing of المرقاب quarters quoted from حمد السعيدان «الموسوعة الكويتية المختصرة» and later local-history articles','checksum':digest(ROOT/depth),'quality_tier':'E','notes':'Publication date unavailable in the archive view. Firjan of المرقاب enter as local_reported historical places.'},
 {'id':'SRC-KW-SIGN-LANGUAGE-MIRROR-2026','title':'لغة الإشارة الكويتية — موسوعة مرآة','publisher':'ويكيبيديا العربية (نسخة مرآة)','source_type':'local_website','url':'https://ar.wikipedia.org/wiki/%D9%84%D8%BA%D8%A9_%D8%A7%D9%84%D8%A5%D8%B4%D8%A7%D8%B1%D8%A9_%D8%A7%D9%84%D9%83%D9%88%D9%8A%D8%AA%D9%8A%D8%A9','archive_url':None,'publication_date':None,'retrieved_at':DEPTH_RETRIEVED,'license':'CC BY-SA 4.0 for the mirror text','language':'ar','country_codes':['KW'],'locator':'infobox and lead: Kuwaiti Sign Language, ISO 639-3 lbs, Arabic sign-language family','checksum':digest(ROOT/depth),'quality_tier':'E','notes':'Publication date unavailable on the mirror. Language presence stays probable and unpublished without an official speaker register.'}
 ]
 expected={r['id'] for r in rows}
 for p in (ROOT/'data/sources').glob('*.json'):
  x=load(p)
  if x.get('country_codes')==['KW'] and x.get('id') not in expected: raise SystemExit('unexpected Kuwait-only source '+x.get('id','?'))
 for r in rows: r['schema_version']=SCHEMA_VERSION; write_json(ROOT/'data/sources'/f"{r['id']}.json",r)
 write_json(IMPORT/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'KW','sources':rows})
 print(f'Materialized {len(rows)} Kuwait atomic sources.')
if __name__=='__main__': main()
