#!/usr/bin/env python3
"""Deterministic Kuwait governorate production import plus depth cycle 1.

Depth cycle 1 (Maximum Arabic Knowledge Coverage, 2026-09-20):
UNESCO intangible-heritage elements are published as verified facts; dialect,
cuisine, dress, and the historic quarters of Kuwait City enter as classified,
unpublished claims and historical places — never as administrative tiers and
never with an invented denominator.
"""
import hashlib,json
from pathlib import Path
from model import ROOT,SCHEMA_VERSION,read_jsonl,record_id,write_json,write_jsonl
from build_kuwait_sources import main as build_sources
IMPORT=ROOT/'data/imports/kuwait'; FIX=IMPORT/'fixtures/census_governorates_2021.json'; WHC=IMPORT/'fixtures/world_heritage_scope_2026.json'; DEPTH=IMPORT/'fixtures/cultural_depth_2026.json'; MAN=IMPORT/'snapshot_manifest.json'
DATE='2026-08-16'; ASOF='2021-01-01'; SNAP='SNP-KW-PRODUCTION-20260816'; SRC='SRC-KW-CSB-CENSUS-GOVERNORATES-2021'; LIC='Kuwait government statistical publication; factual extraction with attribution; reuse terms not stated'; WHCS='SRC-UNESCO-WHC-KW-2026'; WHCL='CC BY-SA 3.0 IGO for property descriptions'
ICH='SRC-KW-UNESCO-ICH-2026'; DIAL='SRC-KW-DIALECT-MIRROR-2026'; LOANS='SRC-KW-DIALECT-LOANS-2026'; FOOD='SRC-KW-CUISINE-MIRROR-2026'; DRESS='SRC-KW-DRESS-HERITAGE-2026'; KUNA='SRC-KW-KUNA-FIRJAN-2017'; MIRQAB='SRC-KW-MIRQAB-HERITAGE-2026'; SIGN='SRC-KW-SIGN-LANGUAGE-MIRROR-2026'
DEPTH_DATE='2026-09-20'; WEAK_LIC='Depth-cycle tier-E mirror; claims stay local_reported and unpublished'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def replace(path,pred,add): write_jsonl(path,[r for r in read_jsonl(path) if not pred(r)]+add)
def entity(eid,name,loc): return {'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'KW','canonical_name':name,'canonical_name_language':'ar','entity_type':'kw_governorate','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':SRC,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Current governorate in the official 2021 registration-census table; no address area, block, municipality, or polygon centroid is inferred.','verification_status':'source_verified','confidence':'high'}
def alias(eid,name,loc): return {'id':record_id('ALS-KW',eid,name),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':name,'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':SRC,'source_locator':loc,'valid_from':None,'valid_to':None}
def rel(eid,loc): return {'id':record_id('REL-KW','administrative_parent',eid,'ENT-KW-COUNTRY'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-KW-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':SRC,'source_locator':loc,'notes':'Governorate-to-country relation only; area and block address units are not inferred as municipalities.','verification_status':'source_verified','confidence':'high'}
def claim(eid,pop,loc): return {'id':record_id('CLM-KW','population',eid,ASOF),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'population','value':{'type':'integer','data':pop},'unit':'person','status':'verified','observed_at':ASOF,'valid_from':None,'valid_to':None,'source_id':SRC,'second_source_id':'SRC-KW-CSB-CENSUS-METHODOLOGY-2021','source_locator':loc,'sensitivity':'ordinary','notes':'2021 registration-census year precision normalized to 1 January. Six governorate rows exclude the separate Not Stated population row.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'official census index identifying Kuwait Registration Census 2021 and total 4,385,717','lexical_context':None}
def den(i,layer,value,asof,source,loc,lic,note): return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KW','layer':layer,'definition':note,'value':value,'as_of':asof,'status':'official','source_id':source,'source_locator':loc,'license':lic,'missing_reason':None,'notes':note,'denominator':value,'snapshot_date':asof}
def cov(i,layer,did,value,source,lic,note): return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KW','layer':layer,'snapshot_id':SNAP,'denominator_id':did,'source_id':source,'matched':value,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':value,'snapshot_date':DATE,'license':lic,'coverage_percentage':100.0,'exclusion_reasons':[]}
def place(eid,name,etype,src,loc,note,vs='local_reported'): return {'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'KW','canonical_name':name,'canonical_name_language':'ar','entity_type':etype,'status':'historical','valid_from':None,'valid_to':None,'canonical_source_id':src,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':vs,'confidence':'medium'}
def located(child,parent,src,loc,note,vs='local_reported'): return {'id':record_id('REL-KW-LOCATED','located_in',child,parent),'schema_version':SCHEMA_VERSION,'child_id':child,'parent_id':parent,'relationship_type':'located_in','status':'historical','valid_from':None,'valid_to':None,'source_id':src,'source_locator':loc,'notes':note,'verification_status':vs,'confidence':'medium'}
def dclaim(key,subject,predicate,data,loc,source,vs,status,cls,published,note,unit=None,conf='medium',observed=None):
 return {'id':record_id('CLM-KW-DEPTH',key),'schema_version':SCHEMA_VERSION,'subject_id':subject,'predicate':predicate,'value':{'type':'json','data':data},'unit':unit,'status':status,'observed_at':observed,'valid_from':None,'valid_to':None,'source_id':source,'second_source_id':None,'source_locator':loc,'second_source_locator':None,'sensitivity':'ordinary','notes':note,'verification_status':vs,'confidence':conf,'classification':cls,'published':published,'lexical_context':None}
def main():
 build_sources(); x=load(FIX); w=load(WHC); d=load(DEPTH)
 if x['schema_version']!=SCHEMA_VERSION or len(x['records'])!=6 or sum(r['population'] for r in x['records'])+x['not_stated_population']!=x['total_population']: raise SystemExit('invalid Kuwait census fixture/reconciliation')
 if w['inscribed_properties']!=0: raise SystemExit('Kuwait WHC zero scope changed')
 if len(d['ich_elements'])!=7 or len(d['non_arabic_languages'])!=2 or len(d['dialect_profiles'])!=5 or len(d['dishes'])!=17 or len(d['dress'])!=6: raise SystemExit('invalid Kuwait depth fixture counts')
 if len(d['quarters']['city_quarters'])!=4 or len(d['quarters']['firjan'])!=12 or len(d['quarters']['sikak'])!=1: raise SystemExit('invalid Kuwait firjan fixture counts')
 entities=[];aliases=[];rels=[];claims=[]
 tokens={'العاصمة':'CAPITAL','حولي':'HAWALLI','الأحمدي':'AL-AHMADI','الجهراء':'AL-JAHRA','الفروانية':'AL-FARWANIYA','مبارك الكبير':'MUBARAK-AL-KABEER'}
 for r in x['records']:
  eid='ENT-KW-GOVERNORATE-'+tokens[r['name_ar']]; loc=f"2021 census Table 1 row: {r['name_ar']} / {r['name_en']}; total={r['population']}"
  entities.append(entity(eid,r['name_ar'],loc));aliases.append(alias(eid,r['name_en'],loc));rels.append(rel(eid,loc));claims.append(claim(eid,r['population'],loc))
 denoms=[den('DEN-KW-GOVERNORATES-2021','kw_governorate',6,ASOF,SRC,'six named governorate rows; Not Stated is not a governorate',LIC,'All six current governorates enumerated in the official 2021 registration-census table.'),den('DEN-KW-WHC-20260816','world_heritage_property',0,DATE,WHCS,'Kuwait State Party summary: zero inscribed properties',WHCL,'All inscribed World Heritage properties for Kuwait: zero. Six tentative-list sites are outside this denominator.')]
 covs=[cov('COV-KW-GOVERNORATES-2021','kw_governorate','DEN-KW-GOVERNORATES-2021',6,SRC,LIC,'Six matched governorates. Not Stated population is not an entity; areas and blocks are outside scope.'),cov('COV-KW-WHC-20260816','world_heritage_property','DEN-KW-WHC-20260816',0,WHCS,WHCL,'Zero matched of zero inscribed properties; six tentative-list sites excluded by definition.')]
 # Depth cycle 1 — historic city quarters, firjan, and sikka as historical places (never administrative tiers).
 quarter_ids={};firij_ids={}
 for q in d['quarters']['city_quarters']:
  eid=record_id('ENT-KW-QUARTER','city_quarter',q['name'])
  quarter_ids[q['name']]=eid
  entities.append(place(eid,q['name'],'quarter',KUNA,f"KUNA 2017-04-27: أحد أحياء مدينة الكويت القديمة الأربعة — {q['name']}",q['note']+' لا تُعالج وحدة إدارية حالية ولا يُنسب إليها سكان.'))
  rels.append(located(eid,'ENT-KW-GOVERNORATE-CAPITAL',KUNA,f"KUNA 2017-04-27: نطاق مدينة الكويت القديمة — {q['name']}",'وقوع تاريخي داخل نطاق محافظة العاصمة الحالية؛ العلاقة تاريخية لا إدارية حالية.'))
 translit={'شرق':'Sharq','الوسط':'Wasat','جبلة':'Jibla','المرقاب':'Mirqab'}
 for q in d['quarters']['city_quarters']:
  eid=quarter_ids[q['name']]
  aliases.append({'id':record_id('ALS-KW','quarter',eid,q['name']),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':translit[q['name']],'language':'en','script':'Latn','kind':'transliteration','status':'historical','source_id':KUNA,'source_locator':f"transliteration of the historic quarter name: {q['name']}",'valid_from':None,'valid_to':None})
 for f in d['quarters']['firjan']:
  eid=record_id('ENT-KW-FIRIJ','firij',f['name'])
  firij_ids[f['name']]=eid
  src=KUNA if f['source']=='quarters_kuna' else MIRQAB
  loc=f"KUNA 2017-04-27: فريج من فرجان {f['quarter']} — {f['name']}" if f['source']=='quarters_kuna' else f"أرشيف تاريخ الكويت — فرجان المرقاب المقتبسة من «الموسوعة الكويتية المختصرة»: {f['name']}"
  entities.append(place(eid,f['name'],'quarter',src,loc,(f.get('note') or '')+(' فريج تاريخي داخل حي '+f['quarter']+'؛ لا مقام ولا سكان منشوران.')))
  rels.append(located(eid,quarter_ids[f['quarter']],src,loc,'فريج تابع تاريخيًا لحي داخل مدينة الكويت القديمة؛ الترتيب سردي تراثي لا إداري.'))
 for s in d['quarters']['sikak']:
  eid=record_id('ENT-KW-LANE','sikka',s['name'])
  loc=f"KUNA 2017-04-27: من أشهر سكيك {s['firij']} — {s['name']}"
  entities.append(place(eid,s['name'],'lane',KUNA,loc,s['note']+' أول سكة موثقة خارج صنعاء في المشروع؛ مكان لا وحدة إدارية.'))
  rels.append(located(eid,firij_ids[s['firij']],KUNA,loc,'سكة داخل فريج موثق؛ لا مقام ولا سكان.'))
 narrative=d['quarters']['narrative']
 claims.append(dclaim('narrative|'+narrative['subject'],firij_ids[narrative['subject']],'name_origin_narrative',{'text':narrative['text']},f"KUNA 2017-04-27: رواية تسمية {narrative['subject']} منسوبة إلى الدكتور عبدالله الغنيم وموافقة الباحث عبدالله محمد بن ناصر",KUNA,'local_reported','reported',narrative['classification'],False,'رواية تسمية محلية منسوبة بالاسم؛ تُعرض رواية لا حقيقة قطعية.'))
 # UNESCO intangible cultural heritage — authoritative, published.
 for e in d['ich_elements']:
  key=f"ich|{e['name']}"
  loc=f"UNESCO ICH state page for Kuwait: {e['official_title']} ({e['year']}, {e['list']} list, ref {e['reference']})"
  claims.append(dclaim(key,'ENT-KW-COUNTRY',e['predicate'],{'name':e['name'],'official_title':e['official_title'],'year':e['year'],'list':e['list'],'reference':e['reference'],'description':e['description']},loc,ICH,'verified','verified',e['classification'],True,'عنصر مدرج عند اليونسكو مع الكويت؛ سنة الإدراج تحمل دقة سنة داخل القيمة ولا تُحوَّل إلى تاريخ يوم كامل. العناصر المشتركة تحمل shared ولا تُنسب حصريًا.',conf='high'))
 for l in d['non_arabic_languages']:
  src=SIGN if l['name'].startswith('لغة الإشارة') else DIAL
  claims.append(dclaim('language|'+l['name'],'ENT-KW-COUNTRY','language_presence',{'language':l['name'],'description':l['description']},f"حضور لغوي في الكويت: {l['name']}",src,l['status'],'reported','regional',False,'حضور لغوي غير عربي بوصف صريح ودرجة ثقة معلنة؛ بلا عدد متحدثين مصطنع.',conf='low' if l['status']=='local_reported' else 'medium'))
 for p in d['dialect_profiles']:
  claims.append(dclaim('dialect|'+p['group'],'ENT-KW-COUNTRY','dialect_profile',{'group':p['group'],'scope':p['scope'],'features':p['features'],'sample_words':p['words'],'researcher':p.get('researcher'),'sub_varieties':p.get('sub_varieties',[])},f"ملف لهجي: {p['group']}",LOANS if p['group']=='المفردات الدخيلة' else DIAL,'local_reported','reported','regional',False,'وصف لهجي من مصادر مرآة محلية؛ المفردات بمعانيها، والدخيل يُفسّر بمصدره لا بادعاء أصل عربي.',conf='low'))
 for f in d['dishes']:
  claims.append(dclaim('dish|'+f['name'],'ENT-KW-COUNTRY','food_dish',{'name':f['name'],'description':f['desc'],'occasion':f['occasion']},f"طبق كويتي: {f['name']}",FOOD,'local_reported','reported',f['classification'],False,'معرفة طعام محلية من مصدر مرآة؛ الأطباق الخليجية المشتركة تبقى shared بلا حصرية.',conf='low'))
 for g in d['dress']:
  src=ICH if g['name']=='البشت' else DRESS
  vs='verified' if g['name']=='البشت' else 'local_reported'
  claims.append(dclaim('dress|'+g['name'],'ENT-KW-COUNTRY','clothing_item',{'name':g['name'],'gender':g['gender'],'description':g['desc']},f"لباس كويتي: {g['name']}",src,vs,'verified' if g['name']=='البشت' else 'reported',g['classification'],g['name']=='البشت','وصف اللباس من مادة تراثية/يونسكو؛ التفاصيل المحلية تبقى غير منشورة حتى مصدر أقوى.',conf='high' if g['name']=='البشت' else 'low'))
 replace(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='KW' and r.get('entity_type')!='country',entities)
 ids={r['id'] for r in entities}|{'ENT-KW-COUNTRY'}
 replace(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-KW-'),aliases);replace(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-KW-'),rels);replace(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,claims)
 replace(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='KW' and r.get('layer')!='country_scope',denoms);replace(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='KW' and r.get('layer')!='country_scope',covs);replace(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-KW-'),[snapshot := {'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Kuwait production expansion — six governorates, World Heritage scope, and depth cycle 1','captured_at':DATE,'source_id':SRC,'scope':'Six 2021 census governorates, the zero-property UNESCO inscribed scope, seven UNESCO intangible-heritage elements, and the historic quarters of Kuwait City','method':'Offline deterministic import from checksum-bound reconciled official census, UNESCO, heritage, and mirror fixtures.','checksum':'sha256:'+hashlib.sha256(MAN.read_bytes()).hexdigest(),'notes':'Population table uses census-year precision. Address areas and blocks remain unclosed with no denominator; historic quarters and firjan are places, never current administrative units.'}])
 m=load(ROOT/'manifests/KW.yml');m.update({'status':'pilot_migrated','official_authority':{'name':'Central Statistical Bureau / Public Authority for Civil Information','source_ids':[SRC,'SRC-KW-CSB-CENSUS-METHODOLOGY-2021'],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-KW-COUNTRY-SCOPE','COV-KW-GOVERNORATES-2021','COV-KW-WHC-20260816'],'caveats':['Production status is recorded by the closeout; coarse manifest status retains pilot_migrated.','Areas and blocks are address/statistical units and are not automatically municipalities.','The 4,578 Not Stated census population is retained in source reconciliation but is not a geographic entity.','Tentative UNESCO sites are not inscribed properties.','Historic quarters and firjan of Kuwait City are historical places with located_in only; they carry no denominator and no current administrative status.','No national denominator is asserted for populated places, broad culture, or dialect.'],'next_action':'Maintain the closed six-governorate layer; extend depth with dated official area topology, and keep the historic firjan layer bounded and unpublished.'})
 for l in m['hierarchy']:
  if l['entity_type']=='kw_governorate': l.update({'source_ids':[SRC],'verification_status':'verified','authority_name':'Central Statistical Bureau / Public Authority for Civil Information','denominator':6,'denominator_id':'DEN-KW-GOVERNORATES-2021','coverage_record_id':'COV-KW-GOVERNORATES-2021','snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'Six governorates in Registration Census 2021.','special_cases':['Not Stated population is not a seventh governorate.']})
  elif l['entity_type'] in {'kw_area','kw_block'}: l.update({'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'No accepted dated official denominator/topology in this cycle.','special_cases':['Do not infer municipal status from address/statistical labels.']})
 m['pilot_layers']=[{'layer':'kw_governorate','entity_types':['kw_governorate'],'local_names':['محافظة'],'authority_name':'Central Statistical Bureau / Public Authority for Civil Information','denominator':6,'denominator_id':'DEN-KW-GOVERNORATES-2021','coverage_record_id':'COV-KW-GOVERNORATES-2021','snapshot_date':ASOF,'source_ids':[SRC,'SRC-KW-CSB-CENSUS-METHODOLOGY-2021'],'license':LIC,'scope_status':'closed','notes':'Complete six-governorate census layer.','special_cases':['Not Stated excluded from entity denominator.']},{'layer':'world_heritage_property','entity_types':['cultural_site'],'local_names':['موقع تراث عالمي'],'authority_name':'UNESCO World Heritage Centre','denominator':0,'denominator_id':'DEN-KW-WHC-20260816','coverage_record_id':'COV-KW-WHC-20260816','snapshot_date':DATE,'source_ids':[WHCS],'license':WHCL,'scope_status':'closed','notes':'Zero inscribed properties; not broad cultural absence.','special_cases':['Six tentative-list sites excluded.']},{'layer':'unesco_intangible_heritage','entity_types':['cultural_site'],'local_names':['عنصر تراث غير مادي'],'authority_name':'UNESCO Intangible Cultural Heritage','denominator':7,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DEPTH_DATE,'source_ids':[ICH],'license':'UNESCO ICH pages; factual extraction with attribution','scope_status':'closed','notes':'Seven inscribed elements on which Kuwait appears; shared elements are never exclusive. No coverage record is asserted because the layer itself is the inscription list.','special_cases':['Shared multi-State files carry classification shared.']},{'layer':'historic_city_quarters','entity_types':['quarter','lane'],'local_names':['فريج','سكة','حي قديم'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DEPTH_DATE,'source_ids':[KUNA,MIRQAB],'license':'Historic narratives from state news agency and local heritage archives; reuse terms not stated','scope_status':'open','notes':'Bounded heritage-attested set of the four historic quarters, twelve firjan, and one sikka; no complete register exists and no percentage is claimed.','special_cases':['Historical places only: located_in relationships, no administrative parent, no population claims.']}]
 write_json(ROOT/'manifests/KW.yml',m);write_json(ROOT/'data/cultural/kuwait_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'KW','snapshot_date':DEPTH_DATE,'domains':{'world_heritage':{'status':'documented_zero_inscribed','claims':0,'denominator':0,'tentative_list_sites':6},'intangible_cultural_heritage':{'status':'documented_published_unesco','claims':7,'elements':['السدو','البشت','الديوانية','الحناء','نخيل التمر','الخط العربي','برنامج السدو التعليمي']},'languages':{'status':'documented_probable_and_local_reported_unpublished','claims':2},'dialect':{'status':'documented_local_reported_unpublished','claims':5},'cuisine':{'status':'documented_local_reported_unpublished','claims':17},'dress':{'status':'documented_local_reported_unpublished','claims':7},'historic_city_quarters':{'status':'documented_historical_places_no_denominator','entities':17,'denominator':None}},'notes':'UNESCO elements are published; weak-source cultural domains stay labelled and unpublished; the historic firjan layer is bounded and carries no percentage.'})
 print(json.dumps({'entities':len(entities),'aliases':len(aliases),'relationships':len(rels),'claims':len(claims),'depth_claims':sum(1 for c in claims if c['id'].startswith('CLM-KW-DEPTH')),'sources':11,'denominators_added':2,'coverage_added':2},sort_keys=True))
if __name__=='__main__': main()
