#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/iraq';F=I/'fixtures/governorate_profiles_2025.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-IQ-PRODUCTION-20260817';COS='SRC-IQ-COSIT-GOVERNORATES-2023';LAW='SRC-IQ-LAW-7-HALABJA-2025';DEC='SRC-IQ-DECREE-21-HALABJA-2025';KRSO='SRC-IQ-KRSO-FOUR-GOVERNORATES';LIC='Official Iraq federal/regional statistical/legal material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'ar-en','country_codes':['IQ'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['governorates'])==19 and sum(x['profile']=='kri' for x in f['governorates'])==4 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(COS,'Iraq governorate population indicators','Iraq Statistics and GIS Authority','official_dataset',f['sources']['cosit'],'federal statistical governorate series before Halabja addition','Legacy 18-row series used with law transition.'),src(LAW,'Law 7/2025 establishing Halabja Governorate','Iraqi Ministry of Justice / Iraqi Gazette','law',f['sources']['law'],'Iraqi Gazette 4824, 5 May 2025','Halabja becomes nineteenth governorate.',pub='2025-05-05'),src(DEC,'Republican Decree 21/2025 — Halabja','Iraqi Ministry of Justice / Iraqi Gazette','law',f['sources']['decree'],'Iraqi Gazette 4825; center Halabja district','Federal decree confirmation.',pub='2025-05-12'),src(KRSO,'KRI population projections by governorate','Kurdistan Region Statistics Office','official_dataset',f['sources']['krso'],'Erbil, Sulaymaniyah, Duhok, Halabja','KRI statistical profile; not duplicate federal entities.')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'IQ','sources':S});E=[];A=[];R=[];C=[]
 for q in f['governorates']:
  eid='ENT-IQ-GOVERNORATE-'+q['code'];is_h=q['code']=='19';s=LAW if is_h else COS;loc=f"Governorate {q['code']}: {q['name_ar']} / {q['name_en']}; profile {q['profile']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'IQ','canonical_name':q['name_ar'],'canonical_name_language':'ar','entity_type':'iq_governorate','status':'current','valid_from':q['valid_from'],'valid_to':None,'canonical_source_id':s,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Federal legal identity with KRI statistical profile where applicable; no disputed/effective-control inference.','verification_status':'verified','confidence':'high'});A.append({'id':record_id('ALS-IQ',eid,q['name_en']),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':q['name_en'],'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':s,'source_locator':loc,'valid_from':q['valid_from'],'valid_to':None});R.append({'id':record_id('REL-IQ',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-IQ-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':q['valid_from'],'valid_to':None,'source_id':s,'source_locator':loc,'notes':'Federal parent; KRI profile is a Claim, not a second entity.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-IQ','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':q['valid_from'],'valid_to':None,'source_id':KRSO if q['profile']=='kri' else COS,'second_source_id':LAW if is_h else None,'source_locator':loc,'sensitivity':'ordinary','notes':'Profile does not encode disputed territory or effective control.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'Law 7/2025' if is_h else None,'lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-IQ-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='IQ' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-IQ-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-IQ-'),R);C.append({'id':record_id('CLM-IQ','halabja-law'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-IQ-GOVERNORATE-19','predicate':'federal_establishment_law','value':{'type':'json','data':{'law_number':7,'gazette_issue':4824,'effective_date':'2025-05-05','republican_decree':21}},'unit':None,'status':'verified','observed_at':'2025-05-12','valid_from':'2025-05-05','valid_to':None,'source_id':LAW,'second_source_id':DEC,'source_locator':'Law 7/2025, Gazette 4824','sensitivity':'ordinary','notes':'Federal legal transition from prior KRI statistical use.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'Decree 21/2025, Gazette 4825','lexical_context':None});rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'IQ','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':s,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'IQ','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('GOVERNORATES','iq_governorate',19,LAW),('KRI-PROFILE','iq_governorate_kri_profile',4,KRSO),('FEDERAL-NON-KRI','iq_governorate_federal_non_kri',15,COS)];ds=[d('DEN-IQ-'+a,l,n,s,f'Exact {l} denominator.') for a,l,n,s in specs];vs=[v('COV-IQ-'+a,l,'DEN-IQ-'+a,n,s,f'{n}/{n} matched without duplicate entities.') for a,l,n,s in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='IQ' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='IQ' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Iraq 19-governorate federal/KRI profile','captured_at':DATE,'source_id':LAW,'scope':'19 federal legal governorates; four KRI statistical profiles','method':'Checksum-bound federal law/COSIT/KRSO reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Districts, disputed areas, and de facto overlays deferred.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-IQ-'),[snap])
 man=L(ROOT/'manifests/IQ.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Iraqi Statistics and GIS Authority / KRSO / Ministry of Justice','source_ids':[COS,LAW,DEC,KRSO],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-IQ-COUNTRY-SCOPE',*[f'COV-IQ-{a}' for a,_,_,_ in specs]],'caveats':['KRI profiles do not create duplicate governorates.','Halabja current federally from 2025-05-05.','Disputed/de facto areas require dated overlays.'],'next_action':'Maintain 19 current governorates; add districts only after federal/KRI semantic reconciliation.'})
 for x in man['hierarchy']:
  if x['entity_type']=='iq_governorate':x.update({'source_ids':[COS,LAW,KRSO],'verification_status':'verified','authority_name':'Federal / KRSO','denominator':19,'denominator_id':'DEN-IQ-GOVERNORATES','coverage_record_id':'COV-IQ-GOVERNORATES','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'19 federal legal identities.','special_cases':['Halabja effective 2025-05-05.']})
  elif x['entity_type'] in {'iq_district','iq_subdistrict'}:x.update({'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'Federal/KRI lower semantics not reconciled.','special_cases':['No disputed-area parent inference.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['iq_governorate'],'local_names':['governorate'],'authority_name':'Federal / KRSO','denominator':n,'denominator_id':'DEN-IQ-'+a,'coverage_record_id':'COV-IQ-'+a,'snapshot_date':DATE,'source_ids':[s],'license':LIC,'scope_status':'closed','notes':'Profile scope.','special_cases':[]} for a,l,n,s in specs];write_json(ROOT/'manifests/IQ.yml',man);write_json(ROOT/'data/cultural/iraq_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'IQ','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_full_pilot_stage1'},'dialect':{'status':'not_documented_in_cycle','claims':0}}});print(json.dumps({'entities':19,'aliases':19,'relationships':19,'claims':20,'sources':4}))
if __name__=='__main__':main()
