#!/usr/bin/env python3
import json,hashlib,re
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/oman';F=I/'fixtures/legal_hierarchy_2022.json';CD=I/'fixtures/cultural_depth_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';ASOF='2022-06-16';SNAP='SNP-OM-PRODUCTION-20260816';LAW='SRC-OM-RD-36-2022-GOVERNORATES';ONA='SRC-OM-ONA-63-WILAYATS-2022';NCSI='SRC-OM-NCSI-ADMIN-CODES-2026';CULT='SRC-OM-CULTURE-MIRROR-2026';LIC='Official Oman legal/statistical material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def tok(s):return re.sub('[^A-Z0-9]+','-',s.upper()).strip('-')
def source(i,title,pub,ty,url,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'title':title,'publisher':pub,'source_type':ty,'url':url,'archive_url':None,'publication_date':ASOF if i==LAW else None,'retrieved_at':DATE,'license':LIC,'language':'ar-en','country_codes':['OM'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if i==LAW else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();rec={r['path'].split('/')[-1]:r['sha256'] for r in m['records']};fc=L(CD)
 assert len(f['governorates'])==11 and sum(len(g['wilayats']) for g in f['governorates'])==63 and hashlib.sha256(b).hexdigest()==rec['legal_hierarchy_2022.json']
 assert hashlib.sha256(CD.read_bytes()).hexdigest()==rec['cultural_depth_2026.json'] and len(fc['non_arabic_languages'])==6 and len(fc['dishes'])==7
 S=[source(LAW,'Royal Decree 36/2022 — Governorates System','Sultanate of Oman / Official Gazette','law',f['decree_url'],'Article 2 governorates/wilayats; Article 3 creation rules','Effective 16 June 2022; checksum binds reconciled record fixture.'),source(ONA,'Al Jabal Al Akhdar and Sinaw raise wilayats to 63','Oman News Agency','institutional_page','https://omannews.gov.om/topics/en/79/show/110798/dark','paragraph confirming two additions and total 63','Official count reconciliation.'),source(NCSI,'Oman administrative coded domains','National Centre for Statistics and Information','official_dataset','https://nsdig2gapps.ncsi.gov.om/arcgis/rest/services/BaseMap_EN_Landmarks/MapServer/61?f=pjson','bilingual governorate/wilayat coded domains','Older 61-code universe used for identity leads only, not denominator.'),{'id':CULT,'schema_version':SCHEMA_VERSION,'title':'Omani dialects, languages, cuisine, and dress — encyclopedic mirror pages','publisher':'Encyclopedic mirror pages on Omani culture','source_type':'institutional_page','url':fc['sources']['dialect_mirror'],'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['OM'],'locator':'Regional dialect profiles, six non-Arabic language notes, dish and dress entries','checksum':'sha256:'+hashlib.sha256(CD.read_bytes()).hexdigest(),'quality_tier':'E','notes':'Depth-cycle weak/secondary mirror. Cultural claims stay probable/local_reported and unpublished; Gulf-shared dishes (القبولي والهريس والثريد والمضروبة) carry shared classification, never exclusive ownership. Publication date unavailable.'}]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'OM','sources':S})
 E=[];A=[];R=[];C=[]
 for g in f['governorates']:
  gid=f"ENT-OM-GOVERNORATE-{g['code']}";loc=f"Decree Article 2 governorate {g['code']}: {g['name_en']}; {len(g['wilayats'])} wilayats"
  E.append({'id':gid,'schema_version':SCHEMA_VERSION,'country_code':'OM','canonical_name':g['name_ar'],'canonical_name_language':'ar','entity_type':'om_governorate','status':'current','valid_from':ASOF,'valid_to':None,'canonical_source_id':LAW,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Legal governorate; no centroid invented.','verification_status':'verified','confidence':'high'});A.append({'id':record_id('ALS-OM',gid,g['name_en']),'schema_version':SCHEMA_VERSION,'entity_id':gid,'name':g['name_en'],'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':LAW,'source_locator':loc,'valid_from':ASOF,'valid_to':None});R.append({'id':record_id('REL-OM',gid,'country'),'schema_version':SCHEMA_VERSION,'child_id':gid,'parent_id':'ENT-OM-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':ASOF,'valid_to':None,'source_id':LAW,'source_locator':loc,'notes':None,'verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-OM','wilayat-count',gid),'schema_version':SCHEMA_VERSION,'subject_id':gid,'predicate':'wilayat_count','value':{'type':'integer','data':len(g['wilayats'])},'unit':'wilaya','status':'verified','observed_at':ASOF,'valid_from':ASOF,'valid_to':None,'source_id':LAW,'second_source_id':ONA if g['code'] in {'05','09'} else None,'source_locator':loc,'sensitivity':'ordinary','notes':'Count of legal child records in reconciled fixture.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'confirmation of added wilayat and national total 63' if g['code'] in {'05','09'} else None,'lexical_context':None})
  for w in g['wilayats']:
   wid=f"ENT-OM-WILAYA-{w['code']}";wl=f"Decree Article 2: {w['name_en']} under {g['name_en']}; reconciled code {w['code']}"
   E.append({'id':wid,'schema_version':SCHEMA_VERSION,'country_code':'OM','canonical_name':w['name_ar'],'canonical_name_language':'ar','entity_type':'om_wilaya','status':'current','valid_from':ASOF,'valid_to':None,'canonical_source_id':LAW,'source_locator':wl,'legacy_ids':[],'coordinates':None,'notes':'Legal wilaya; municipality branch and niyabah are distinct.','verification_status':'verified','confidence':'high'});A.append({'id':record_id('ALS-OM',wid,w['name_en']),'schema_version':SCHEMA_VERSION,'entity_id':wid,'name':w['name_en'],'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':LAW,'source_locator':wl,'valid_from':ASOF,'valid_to':None});R.append({'id':record_id('REL-OM',wid,gid),'schema_version':SCHEMA_VERSION,'child_id':wid,'parent_id':gid,'relationship_type':'administrative_parent','status':'current','valid_from':ASOF,'valid_to':None,'source_id':LAW,'source_locator':wl,'notes':None,'verification_status':'verified','confidence':'high'})
 # Cultural depth cycle: languages, dialect profiles, dishes, dress. Unpublished, classified.
 def dc(key,subj,pred,val,loc,vs,cls,note):
  C.append({'id':record_id('CLM-OM-DEPTH',key),'schema_version':SCHEMA_VERSION,'subject_id':subj,'predicate':pred,'value':val,'unit':None,'status':'reported','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':CULT,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':note,'verification_status':vs,'confidence':'medium' if vs=='probable' else 'low','classification':cls,'published':False,'second_source_locator':None,'lexical_context':None})
 for q in fc['non_arabic_languages']:
  dc('lang|'+q['name'],q['subject'],'language_presence',{'type':'json','data':{'language':q['name'],'description':q['desc']}},f"Language note: {q['name']}",q['status'],'regional','Living local language documented in secondary mirrors; Kumzari and Bathari stay local_reported pending academic atomic sources; unpublished.')
 for q in fc['dialect_profiles']:
  dc('dialect|'+q['group'],q['subject'],'dialect_profile',{'type':'json','data':{'group':q['group'],'scope':q['scope'],'features':q['features'],'sample_words':q['words']}},f"Dialect profile: {q['group']}",'local_reported','regional','Regional dialect profile from secondary mirrors; a field-attested corpus remains the upgrade path; unpublished.')
 for q in fc['dishes']:
  dc('dish|'+q['name'],q['subject'],'food_dish',{'type':'json','data':{'name':q['name'],'description':q['desc'],'occasion':q['occasion'],'note':q['note']}},f"Dish entry: {q['name']}",'local_reported',q['classification'],'Culinary knowledge from weak/secondary mirrors; unpublished. Gulf-shared dishes stay shared, never exclusive.')
 for q in fc['dress']:
  dc('dress|'+q['name'],q['subject'],'clothing_item',{'type':'json','data':{'name':q['name'],'gender':q['gender'],'description':q['desc']}},f"Dress entry: {q['name']}",'local_reported',q['classification'],'Dress knowledge from weak/secondary mirrors; unpublished.')
 ids={x['id'] for x in E}|{'ENT-OM-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='OM' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-OM-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-OM-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'OM','layer':l,'definition':note,'value':n,'as_of':ASOF,'status':'official','source_id':LAW,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':ASOF}
 def v(i,l,did,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'OM','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':LAW,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 ds=[d('DEN-OM-GOVERNORATES-2022','om_governorate',11,'All governorates in Decree 36/2022.'),d('DEN-OM-WILAYATS-2022','om_wilaya',63,'All legal wilayats after Al Jabal Al Akhdar and Sinaw additions.')];vs=[v('COV-OM-GOVERNORATES-2022','om_governorate','DEN-OM-GOVERNORATES-2022',11,'11/11 legal governorates.'),v('COV-OM-WILAYATS-2022','om_wilaya','DEN-OM-WILAYATS-2022',63,'63/63 reconciled legal wilayats.')];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='OM' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='OM' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Oman legal governorates and wilayats','captured_at':DATE,'source_id':LAW,'scope':'11 governorates and 63 wilayats','method':'Checksum-bound legal reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Niyabahs and administrative centres unavailable.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-OM-'),[snap])
 man=L(ROOT/'manifests/OM.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Ministry of Interior / Official Gazette','source_ids':[LAW,ONA],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-OM-COUNTRY-SCOPE','COV-OM-GOVERNORATES-2022','COV-OM-WILAYATS-2022'],'caveats':['Governorate, wilaya, municipality branch, and niyabah are distinct.','NCSI 61-code domain is historical identity evidence, not current denominator.','No niyabah denominator asserted.'],'next_action':'Maintain 11/63 legal hierarchy; add niyabahs only from ministerial decisions.'})
 for q in man['hierarchy']:
  if q['entity_type']=='om_governorate':q.update({'source_ids':[LAW],'verification_status':'verified','authority_name':'Ministry of Interior','denominator':11,'denominator_id':'DEN-OM-GOVERNORATES-2022','coverage_record_id':'COV-OM-GOVERNORATES-2022','snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'11 legal governorates.','special_cases':[]})
  elif q['entity_type']=='om_wilaya':q.update({'source_ids':[LAW,ONA],'verification_status':'verified','authority_name':'Ministry of Interior','denominator':63,'denominator_id':'DEN-OM-WILAYATS-2022','coverage_record_id':'COV-OM-WILAYATS-2022','snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'63 reconciled legal wilayats.','special_cases':['Al Jabal Al Akhdar and Sinaw added after older 61-code scope.']})
  elif q['entity_type']=='om_niyaba':q.update({'verification_status':'pending','authority_name':'Ministry of Interior','denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'Selective ministerial decisions; no national denominator accepted.','special_cases':[]})
 man['pilot_layers']=[{'layer':'om_governorate','entity_types':['om_governorate'],'local_names':['محافظة'],'authority_name':'Ministry of Interior','denominator':11,'denominator_id':'DEN-OM-GOVERNORATES-2022','coverage_record_id':'COV-OM-GOVERNORATES-2022','snapshot_date':ASOF,'source_ids':[LAW],'license':LIC,'scope_status':'closed','notes':'Legal layer.','special_cases':[]},{'layer':'om_wilaya','entity_types':['om_wilaya'],'local_names':['ولاية'],'authority_name':'Ministry of Interior','denominator':63,'denominator_id':'DEN-OM-WILAYATS-2022','coverage_record_id':'COV-OM-WILAYATS-2022','snapshot_date':ASOF,'source_ids':[LAW,ONA],'license':LIC,'scope_status':'closed','notes':'Reconciled legal layer.','special_cases':['61 legacy codes plus two additions.']}];write_json(ROOT/'manifests/OM.yml',man);write_json(ROOT/'data/cultural/oman_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'OM','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_micro_pilot','known_register_count':5},'dialect':{'status':'documented_local_reported_unpublished','claims':11},'cuisine':{'status':'documented_local_reported_unpublished','claims':7},'dress':{'status':'documented_local_reported_unpublished','claims':3}},'notes':'Administrative micro pilot only.'});print(json.dumps({'entities':74,'aliases':74,'relationships':74,'claims':32,'sources':4}))
if __name__=='__main__':main()
