#!/usr/bin/env python3
"""Deterministic Kuwait governorate production import."""
import hashlib,json
from pathlib import Path
from model import ROOT,SCHEMA_VERSION,read_jsonl,record_id,write_json,write_jsonl
from build_kuwait_sources import main as build_sources
IMPORT=ROOT/'data/imports/kuwait'; FIX=IMPORT/'fixtures/census_governorates_2021.json'; WHC=IMPORT/'fixtures/world_heritage_scope_2026.json'; MAN=IMPORT/'snapshot_manifest.json'
DATE='2026-08-16'; ASOF='2021-01-01'; SNAP='SNP-KW-PRODUCTION-20260816'; SRC='SRC-KW-CSB-CENSUS-GOVERNORATES-2021'; LIC='Kuwait government statistical publication; factual extraction with attribution; reuse terms not stated'; WHCS='SRC-UNESCO-WHC-KW-2026'; WHCL='CC BY-SA 3.0 IGO for property descriptions'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def replace(path,pred,add): write_jsonl(path,[r for r in read_jsonl(path) if not pred(r)]+add)
def entity(eid,name,loc): return {'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'KW','canonical_name':name,'canonical_name_language':'ar','entity_type':'kw_governorate','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':SRC,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Current governorate in the official 2021 registration-census table; no address area, block, municipality, or polygon centroid is inferred.','verification_status':'source_verified','confidence':'high'}
def alias(eid,name,loc): return {'id':record_id('ALS-KW',eid,name),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':name,'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':SRC,'source_locator':loc,'valid_from':None,'valid_to':None}
def rel(eid,loc): return {'id':record_id('REL-KW','administrative_parent',eid,'ENT-KW-COUNTRY'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-KW-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':SRC,'source_locator':loc,'notes':'Governorate-to-country relation only; area and block address units are not inferred as municipalities.','verification_status':'source_verified','confidence':'high'}
def claim(eid,pop,loc): return {'id':record_id('CLM-KW','population',eid,ASOF),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'population','value':{'type':'integer','data':pop},'unit':'person','status':'verified','observed_at':ASOF,'valid_from':None,'valid_to':None,'source_id':SRC,'second_source_id':'SRC-KW-CSB-CENSUS-METHODOLOGY-2021','source_locator':loc,'sensitivity':'ordinary','notes':'2021 registration-census year precision normalized to 1 January. Six governorate rows exclude the separate Not Stated population row.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'official census index identifying Kuwait Registration Census 2021 and total 4,385,717','lexical_context':None}
def den(i,layer,value,asof,source,loc,lic,note): return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KW','layer':layer,'definition':note,'value':value,'as_of':asof,'status':'official','source_id':source,'source_locator':loc,'license':lic,'missing_reason':None,'notes':note,'denominator':value,'snapshot_date':asof}
def cov(i,layer,did,value,source,lic,note): return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KW','layer':layer,'snapshot_id':SNAP,'denominator_id':did,'source_id':source,'matched':value,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':value,'snapshot_date':DATE,'license':lic,'coverage_percentage':100.0,'exclusion_reasons':[]}
def main():
 build_sources(); x=load(FIX); w=load(WHC)
 if x['schema_version']!=SCHEMA_VERSION or len(x['records'])!=6 or sum(r['population'] for r in x['records'])+x['not_stated_population']!=x['total_population']: raise SystemExit('invalid Kuwait census fixture/reconciliation')
 if w['inscribed_properties']!=0: raise SystemExit('Kuwait WHC zero scope changed')
 entities=[];aliases=[];rels=[];claims=[]
 tokens={'العاصمة':'CAPITAL','حولي':'HAWALLI','الأحمدي':'AL-AHMADI','الجهراء':'AL-JAHRA','الفروانية':'AL-FARWANIYA','مبارك الكبير':'MUBARAK-AL-KABEER'}
 for r in x['records']:
  eid='ENT-KW-GOVERNORATE-'+tokens[r['name_ar']]; loc=f"2021 census Table 1 row: {r['name_ar']} / {r['name_en']}; total={r['population']}"
  entities.append(entity(eid,r['name_ar'],loc));aliases.append(alias(eid,r['name_en'],loc));rels.append(rel(eid,loc));claims.append(claim(eid,r['population'],loc))
 denoms=[den('DEN-KW-GOVERNORATES-2021','kw_governorate',6,ASOF,SRC,'six named governorate rows; Not Stated is not a governorate',LIC,'All six current governorates enumerated in the official 2021 registration-census table.'),den('DEN-KW-WHC-20260816','world_heritage_property',0,DATE,WHCS,'Kuwait State Party summary: zero inscribed properties',WHCL,'All inscribed World Heritage properties for Kuwait: zero. Six tentative-list sites are outside this denominator.')]
 covs=[cov('COV-KW-GOVERNORATES-2021','kw_governorate','DEN-KW-GOVERNORATES-2021',6,SRC,LIC,'Six matched governorates. Not Stated population is not an entity; areas and blocks are outside scope.'),cov('COV-KW-WHC-20260816','world_heritage_property','DEN-KW-WHC-20260816',0,WHCS,WHCL,'Zero matched of zero inscribed properties; six tentative-list sites excluded by definition.')]
 snapshot={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Kuwait production expansion — six governorates and World Heritage scope','captured_at':DATE,'source_id':SRC,'scope':'Six 2021 census governorates and the zero-property UNESCO inscribed scope','method':'Offline deterministic import from checksum-bound reconciled official census and UNESCO fixtures.','checksum':'sha256:'+hashlib.sha256(MAN.read_bytes()).hexdigest(),'notes':'Population table uses census-year precision. Differing page widgets are not imported. Address areas, blocks, populated places, broad culture, and dialect remain unclosed.'}
 replace(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='KW' and r.get('entity_type')!='country',entities)
 ids={r['id'] for r in entities}|{'ENT-KW-COUNTRY'}
 replace(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-KW-'),aliases);replace(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-KW-'),rels);replace(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,claims)
 replace(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='KW' and r.get('layer')!='country_scope',denoms);replace(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='KW' and r.get('layer')!='country_scope',covs);replace(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-KW-'),[snapshot])
 m=load(ROOT/'manifests/KW.yml');m.update({'status':'pilot_migrated','official_authority':{'name':'Central Statistical Bureau / Public Authority for Civil Information','source_ids':[SRC,'SRC-KW-CSB-CENSUS-METHODOLOGY-2021'],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-KW-COUNTRY-SCOPE','COV-KW-GOVERNORATES-2021','COV-KW-WHC-20260816'],'caveats':['Production status is recorded by the closeout; coarse manifest status retains pilot_migrated.','Areas and blocks are address/statistical units and are not automatically municipalities.','The 4,578 Not Stated census population is retained in source reconciliation but is not a geographic entity.','Tentative UNESCO sites are not inscribed properties.','No national denominator is asserted for populated places, broad culture, or dialect.'],'next_action':'Maintain six-governorate production scope; add areas/blocks only after a dated official topology and denominator.'})
 for l in m['hierarchy']:
  if l['entity_type']=='kw_governorate': l.update({'source_ids':[SRC],'verification_status':'verified','authority_name':'Central Statistical Bureau / Public Authority for Civil Information','denominator':6,'denominator_id':'DEN-KW-GOVERNORATES-2021','coverage_record_id':'COV-KW-GOVERNORATES-2021','snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'Six governorates in Registration Census 2021.','special_cases':['Not Stated population is not a seventh governorate.']})
  elif l['entity_type'] in {'kw_area','kw_block'}: l.update({'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'No accepted dated official denominator/topology in this cycle.','special_cases':['Do not infer municipal status from address/statistical labels.']})
 m['pilot_layers']=[{'layer':'kw_governorate','entity_types':['kw_governorate'],'local_names':['محافظة'],'authority_name':'Central Statistical Bureau / Public Authority for Civil Information','denominator':6,'denominator_id':'DEN-KW-GOVERNORATES-2021','coverage_record_id':'COV-KW-GOVERNORATES-2021','snapshot_date':ASOF,'source_ids':[SRC,'SRC-KW-CSB-CENSUS-METHODOLOGY-2021'],'license':LIC,'scope_status':'closed','notes':'Complete six-governorate census layer.','special_cases':['Not Stated excluded from entity denominator.']},{'layer':'world_heritage_property','entity_types':['cultural_site'],'local_names':['موقع تراث عالمي'],'authority_name':'UNESCO World Heritage Centre','denominator':0,'denominator_id':'DEN-KW-WHC-20260816','coverage_record_id':'COV-KW-WHC-20260816','snapshot_date':DATE,'source_ids':[WHCS],'license':WHCL,'scope_status':'closed','notes':'Zero inscribed properties; not broad cultural absence.','special_cases':['Six tentative-list sites excluded.']}]
 write_json(ROOT/'manifests/KW.yml',m);write_json(ROOT/'data/cultural/kuwait_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'KW','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented_zero_inscribed','claims':0,'denominator':0,'tentative_list_sites':6},'food':{'status':'not_documented_in_cycle','claims':0},'dress':{'status':'not_documented_in_cycle','claims':0},'custom':{'status':'not_documented_in_cycle','claims':0},'dialect':{'status':'not_documented_in_cycle','claims':0}},'notes':'Zero inscribed World Heritage properties is not cultural absence. No template claims invented.'})
 print(json.dumps({'entities_added':6,'aliases_added':6,'relationships_added':6,'claims_added':6,'sources':3,'denominators_added':2,'coverage_added':2},sort_keys=True))
if __name__=='__main__': main()
