#!/usr/bin/env python3
import hashlib,json
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/syria';F=I/'fixtures/governorates_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-SY-PRODUCTION-20260817';SIA='SRC-SY-SIA-ADMIN-DIVISIONS-2026';SANA='SRC-SY-SANA-GOVERNORATE-NAV-2026';CBS='SRC-SY-CBS-GOVERNORATES-2010';LIC='Official Syrian institutional/statistical material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,typ,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':typ,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['SY'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);assert len(f['governorates'])==14 and sum(x['profile']=='damascus_city_governorate' for x in f['governorates'])==1 and hashlib.sha256(F.read_bytes()).hexdigest()==m['records'][0]['sha256']
 S=[src(SIA,'Administrative divisions of Syria','Syrian Investment Authority','official_register',f['sources']['sia'],'Administrative divisions section: 14 governorates, 68 districts, 227 subdistricts, Damascus special case','Current government institutional hierarchy/count source; does not prove effective control.'),src(SANA,'Current governorate navigation and presidency appointments','Syrian Arab News Agency','official_register',f['sources']['sana'],'Governorate navigation categories: Damascus, Aleppo, Hama, Homs, Deir ez-Zor, Rural Damascus, Latakia, Sweida, Hasaka, Raqqa, Idlib, Quneitra, Daraa, Tartous','Current 14-name institutional enumeration, supported by 2026 governor appointment reporting; not a control map.'),src(CBS,'Labour force bulletin by governorate — 2010','Central Bureau of Statistics Syria','official_dataset',f['sources']['cbs'],'Fourteen governorate links','Historical exact statistical enumeration used only as continuity evidence.',pub='2010')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'SY','sources':S});E=[];R=[];C=[]
 for q in f['governorates']:
  eid='ENT-SY-GOVERNORATE-'+q['code'];loc=f"SANA governorate navigation category: {q['name_ar']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'SY','canonical_name':q['name_ar'],'canonical_name_language':'ar','entity_type':'sy_governorate','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':SANA,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Current legal/institutional governorate identity only; no effective-control, destruction, displacement, access, or dispute inference.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-SY',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-SY-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':SANA,'source_locator':loc,'notes':'Legal/institutional parent only; not an effective-control relation.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-SY','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':SIA,'second_source_id':SANA,'source_locator':'Administrative divisions: Damascus city is a governorate in its own right' if q['profile']=='damascus_city_governorate' else loc,'sensitivity':'ordinary','notes':'Profile does not encode current control or physical/humanitarian condition.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':loc,'lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-SY-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='SY' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-SY-') and r.get('entity_id')!='ENT-SY-COUNTRY',[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-SY-') and r.get('child_id')!='ENT-SY-COUNTRY',R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SY','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':SIA,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,matched,note,complete):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SY','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':SIA,'matched':matched,'unmatched':n-matched,'excluded':0,'missing':n-matched,'complete':complete,'missing_reason':None if complete else 'Record-level current register not yet accepted; official count is retained as an open denominator.','notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':round(matched*100/n,2),'exclusion_reasons':[]}
 specs=[('GOVERNORATES','sy_governorate',14,14,'Current institutional governorates.',True),('DAMASCUS-SPECIAL','sy_governorate_damascus_special',1,1,'Damascus city forms one governorate.',True),('OTHER-GOVERNORATES','sy_governorate_other',13,13,'Governorates other than Damascus special case.',True),('DISTRICTS','sy_district',68,0,'Current official count of districts, including 14 governorate-center districts; record layer open.',False),('SUBDISTRICTS','sy_subdistrict',227,0,'Current official count of subdistricts; record layer open.',False)]
 ds=[d('DEN-SY-'+a,l,n,note) for a,l,n,_,note,_ in specs];vs=[v('COV-SY-'+a,l,'DEN-SY-'+a,n,matched,note,complete) for a,l,n,matched,note,complete in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='SY' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='SY' and r.get('layer')!='country_scope',vs)
 snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Syria current legal/institutional governorates','captured_at':DATE,'source_id':SANA,'scope':'14 legal/institutional governorates; lower official denominators open','method':'Checksum-bound reconciliation of current SIA count/hierarchy and current SANA 14-name navigation against historical CBS continuity.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'No control, destruction, displacement, access, or contested-status overlay is inferred.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-SY-PRODUCTION-'),[snap])
 man=L(ROOT/'manifests/SY.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Syrian Investment Authority / Syrian Arab News Agency / Central Bureau of Statistics','source_ids':[SIA,SANA,CBS],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-SY-COUNTRY-SCOPE',*[f'COV-SY-{a}' for a,_,_,_,_,_ in specs]],'caveats':['Fourteen legal/institutional governorates are closed; this is not an effective-control map.','Official counts of 68 districts and 227 subdistricts are retained as open denominators without fabricated records.','Destroyed, displaced, disputed, access, and de facto statuses require independent dated overlays.'],'next_action':'Maintain 14 legal governorates; reconcile record-level district/subdistrict registers and dated status overlays separately.'})
 for x in man['hierarchy']:
  if x['entity_type']=='sy_governorate':x.update({'source_ids':[SIA,SANA,CBS],'verification_status':'verified','authority_name':'SIA / SANA / CBS','denominator':14,'denominator_id':'DEN-SY-GOVERNORATES','coverage_record_id':'COV-SY-GOVERNORATES','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'14 legal/institutional governorates.','special_cases':['Damascus city is a governorate in its own right; Rural Damascus is distinct.']})
  elif x['entity_type']=='sy_district':x.update({'source_ids':[SIA],'verification_status':'pending','authority_name':'Syrian Investment Authority','denominator':68,'denominator_id':'DEN-SY-DISTRICTS','coverage_record_id':'COV-SY-DISTRICTS','snapshot_date':DATE,'license':LIC,'scope_status':'open','notes':'Official count known; record-level register not accepted.','special_cases':['Count includes 14 governorate-center districts.']})
  elif x['entity_type']=='sy_subdistrict':x.update({'source_ids':[SIA],'verification_status':'pending','authority_name':'Syrian Investment Authority','denominator':227,'denominator_id':'DEN-SY-SUBDISTRICTS','coverage_record_id':'COV-SY-SUBDISTRICTS','snapshot_date':DATE,'license':LIC,'scope_status':'open','notes':'Official count known; record-level register not accepted.','special_cases':['Some subdistricts attach directly to governorate centers.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['sy_governorate'] if 'governorate' in l else [l],'local_names':['محافظة' if 'governorate' in l else ('منطقة' if l=='sy_district' else 'ناحية')],'authority_name':'SIA / SANA','denominator':n,'denominator_id':'DEN-SY-'+a,'coverage_record_id':'COV-SY-'+a,'snapshot_date':DATE,'source_ids':[SIA,SANA] if 'governorate' in l else [SIA],'license':LIC,'scope_status':'closed' if complete else 'open','notes':note,'special_cases':[]} for a,l,n,_,note,complete in specs];write_json(ROOT/'manifests/SY.yml',man);write_json(ROOT/'data/cultural/syria_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'SY','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_full_pilot_stage1'},'dialect':{'status':'not_documented_in_cycle','claims':0},'destruction_displacement':{'status':'requires_separate_dated_overlay'}}});print(json.dumps({'entities':14,'relationships':14,'claims':14,'sources':3,'denominators':5,'coverage':5}))
if __name__=='__main__':main()
