#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/mauritania';F=I/'fixtures/wilaya_profiles.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';SNAP='SNP-MR-PRODUCTION-20260816';DGAT='SRC-MR-DGAT-15-63-2026';RGPH='SRC-MR-ANSADE-RGPH5-2024';REV='SRC-MR-ANSADE-PEER-REVIEW-2024';LIC='Official Mauritania administrative/statistical material; factual extraction with attribution; reuse terms not stated'
D=I/'fixtures/cultural_depth_2026.json';DDATE='2026-09-21'
DS={'state':'SRC-UNESCO-ICH-MR-STATE-2026','theydinn':'SRC-UNESCO-ICH-THEYDINN-00524-2011','mahadra':'SRC-UNESCO-ICH-MAHADRA-01960-2023','samba':'SRC-UNESCO-ICH-SAMBA-GUELADIO-01692-2024','couscous':'SRC-UNESCO-ICH-COUSCOUS-01602-2020','calligraphy':'SRC-UNESCO-ICH-CALLIGRAPHY-01718-2021','datepalm':'SRC-UNESCO-ICH-DATE-PALM-01902-2022','engraving':'SRC-UNESCO-ICH-ENGRAVING-01951-2023','henna':'SRC-UNESCO-ICH-HENNA-02116-2024','zaffa':'SRC-UNESCO-ICH-MR-ZAFFA-02283-2025','ksour':'SRC-UNESCO-WH-MR-KSOUR-750-1996','whc_state':'SRC-UNESCO-WH-MR-STATE-2026','constitution':'SRC-MR-CONSTITUTION-2012','iso_mey':'SRC-MR-ISO639-3-HASSANIYA','iso_fuc':'SRC-MR-ISO639-3-PULAAR','iso_snk':'SRC-MR-ISO639-3-SONINKE','iso_wol':'SRC-MR-ISO639-3-WOLOF','iso_zen':'SRC-MR-ISO639-3-ZENAGA','iso_bam':'SRC-MR-ISO639-3-BAMBARA','iso_taq':'SRC-MR-ISO639-3-TAMASHEQ','iso_srr':'SRC-MR-ISO639-3-SERER','languages':'SRC-MR-LANGUAGES-MIRROR-2026','hassaniya':'SRC-MR-HASSANIYA-MIRROR-2026','cuisine':'SRC-MR-CUISINE-MIRROR-2026','dress':'SRC-MR-DRESS-MIRROR-2026','nouakchott':'SRC-MR-NOUAKCHOTT-MIRROR-2026','press2010':'SRC-MR-NOUAKCHOTT-ALKHALEEJ-2010','towns':'SRC-MR-TOWNS-MIRROR-2026','sites':'SRC-MR-SITES-MIRROR-2026'}
ILOC='UNESCO ICH and World Heritage pages and the Constitution as published by Constitute; factual extraction with attribution; CC BY-SA 3.0 IGO for the UNESCO descriptions'
WLOC='Mirror and press material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar-fr','country_codes':['MR'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+' Publication date unavailable.'}
def dsrc(i,key,title,pub,ty,loc,note,tier='E',lang='ar',lic=WLOC,pdate=None):
 return {'id':i,'schema_version':SCHEMA_VERSION,'title':title,'publisher':pub,'source_type':ty,'url':L(D)['sources'][key],'archive_url':None,'publication_date':pdate,'retrieved_at':DDATE,'license':lic,'language':lang,'country_codes':['MR'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(D.read_bytes()).hexdigest(),'quality_tier':tier,'notes':note+('' if pdate else ' Publication date unavailable.')}
def depth_sources():
 U='UNESCO Intangible Cultural Heritage';W='UNESCO World Heritage Centre';S='SIL International (ISO 639-3 registration authority)'
 return [dsrc(DS['state'],'state','Mauritania — UNESCO Intangible Cultural Heritage',U,'institutional_page','تسعة عناصر مُدرجة (2011 قائمة الصون العاجل و2011-2025 القائمة التمثيلية)؛ التصديق 15 نوفمبر 2006؛ عضو لجنة 2022-2026؛ ثلاثة ترشيحات 2026 معلنة','صفحة الدولة قُرئت 2026-09-21: قائمة العناصر وسنواتها وقوائمها وتاريخ التصديق والترشيحات الجارية.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['theydinn'],'theydinn','Moorish epic T’heydinn',U,'institutional_page','عنصر 00524؛ إدراج 2011 (6.COM) على قائمة الصون العاجل؛ موريتانيا الدولة المُقدِّمة الوحيدة','صفحة العنصر قُرئت 2026-09-21: وصف الملحمة والمديّاحين والآلات وتراجع الأداء.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['mahadra'],'mahadra','Mahadra, a community system for transmission of traditional knowledge and oral expressions',U,'institutional_page','عنصر 01960؛ إدراج 2023 (18.COM) على القائمة التمثيلية؛ موريتانيا وحدها','صفحة العنصر قُرئت 2026-09-21: وصف «جامعة الصحراء» والخيمة والموادّ المنقولة.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['samba'],'samba','The Epic of Samba Gueladio',U,'institutional_page','عنصر 01692؛ إدراج 2024 (19.COM) على القائمة التمثيلية؛ موريتانيا وحدها','صفحة العنصر قُرئت 2026-09-21: حكاية البطل وتحالفاته وقيم الملحمة.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['couscous'],'couscous','Knowledge, know-how and practices pertaining to the production and consumption of couscous',U,'institutional_page','عنصر 01602؛ إدراج 2020 (15.COM)؛ أربع دول: الجزائر وموريتانيا والمغرب وتونس','صفحة العنصر قُرئت 2026-09-21: عمليات الإعداد والأدوات والدلالات الاجتماعية.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['calligraphy'],'calligraphy','Arabic calligraphy: knowledge, skills and practices',U,'institutional_page','عنصر 01718؛ إدراج 2021 (16.COM)؛ ست عشرة دولة منها موريتانيا','صفحة العنصر قُرئت 2026-09-21: الحروف والأدوات والمواد والانتقال إلى الوسائط الحديثة.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['datepalm'],'datepalm','Date palm, knowledge, skills, traditions and practices',U,'institutional_page','عنصر 01902؛ إدراج 2022 (17.COM)؛ خمس عشرة دولة منها موريتانيا','صفحة العنصر قُرئت 2026-09-21: النخلة في الواحات والاستعمالات والحضور في الشعر.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['engraving'],'engraving','Arts, skills and practices associated with engraving on metals (gold, silver and copper)',U,'institutional_page','عنصر 01951؛ إدراج 2023 (18.COM)؛ عشر دول منها موريتانيا','صفحة العنصر قُرئت 2026-09-21: النقش اليدوي على المعادن وأدواته وأنماط نقله.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['henna'],'henna','Henna: rituals, aesthetic and social practices',U,'institutional_page','عنصر 02116؛ إدراج 2024 (19.COM)؛ ست عشرة دولة منها موريتانيا','صفحة العنصر قُرئت 2026-09-21: شجرة الحناء وعجينتها واستعمالاتها ومرافقاتها الشفهية.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['zaffa'],'zaffa','The zaffa in the traditional wedding',U,'institutional_page','عنصر 02283؛ إدراج 2025 (20.COM)؛ سبع دول منها موريتانيا','صفحة العنصر قُرئت في دورة جزر القمر 2026-09-20 وأُعيدت هنا لإكمال قائمة موريتانيا دون ادعاء حصرية.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['ksour'],'ksour','Ancient Ksour of Ouadane, Chinguetti, Tichitt and Oualata',W,'institutional_page','موقع 750؛ إدراج 1996؛ المعايير (iii) و(iv) و(v)؛ الوصف الرسمي بالعربية','صفحة الموقع قُرئت 2026-09-21: الوصف الرسمي العربي والمعايير وملاحظات الإدارة والحماية (قانون 46-2005).',tier='A',lang='ar',lic=ILOC),
 dsrc(DS['whc_state'],'whc_state','Mauritania — UNESCO World Heritage Convention',W,'institutional_page','موقعان مُدرجان (قصور 750 الثقافي 1996، وبانك دارغان 506 الطبيعي 1989)؛ ثلاث مواقع في القائمة المؤقتة (2001)؛ التصديق 2 مارس 1981','صفحة الدولة قُرئت 2026-09-21: قائمتا الإدراج والقائمة المؤقتة وتاريخ التصديق وتقارير حالة الحفظ.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['constitution'],'constitution','Mauritania 1991 (rev. 2012) Constitution (as published by Constitute)','Constitute Project — Comparative Constitutions Project','law','المواد 1 و5 و6 و7 و9؛ الديباجة: العربية الرسمية واللغات الوطنية ثروة مشتركة','نصّ دستوري منشور على مشروع «Constitute»؛ لا يُنسب تاريخ إصدار إلى الصفحة. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_mey'],'iso_mey','ISO 639-3 code registration — Hassaniyya',S,'standard','mey = Hassaniyya؛ 639-3؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_fuc'],'iso_fuc','ISO 639-3 code registration — Pulaar',S,'standard','fuc = Pulaar؛ عضو في لغة أم فالاful (ful)؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_snk'],'iso_snk','ISO 639-3 code registration — Soninke',S,'standard','snk = Soninke؛ 639-2/639-3؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_wol'],'iso_wol','ISO 639-3 code registration — Wolof',S,'standard','wol = Wolof؛ 639-1: wo؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_zen'],'iso_zen','ISO 639-3 code registration — Zenaga',S,'standard','zen = Zenaga؛ 639-2/639-3؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_bam'],'iso_bam','ISO 639-3 code registration — Bambara',S,'standard','bam = Bambara؛ 639-1: bm؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_taq'],'iso_taq','ISO 639-3 code registration — Tamasheq',S,'standard','taq = Tamasheq؛ عضو في لغة أم تماشق (tmh) مع thv وthz وttq؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_srr'],'iso_srr','ISO 639-3 code registration — Serer',S,'standard','srr = Serer؛ 639-2/639-3؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-21. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['languages'],'languages','Languages of Mauritania','Wikipedia (English mirror)','local_website','العربية الرسمية؛ اللغات الوطنية: العربية والبولارية والسوننكية والولوفية؛ الحسانية اللغة الدارجة؛ الزناغة والبمبارا والطوارقية والسيريرية أقليات؛ لغة إشارة فرنكوفونية؛ الفرنسية لغة عمل بحكم الأمر الواقع','مرآة إنجليزية لخريطة اللغات؛ تُستعمل للتصنيف والحضور فقط، ولا تُسجَّل أعداد المتحدثين ولا نسبها المطبوعة في الصفحة.',tier='E',lang='en'),
 dsrc(DS['hassaniya'],'hassaniya','لهجة حسانية','ويكيبيديا العربية (نسخة مرآة)','local_website','لهجة بدوية من لهجات بني حسان؛ أقرب اللهجات: الليبية وجنوب تونس ووادي سوف؛ لهجات نمادية وإمراغوية؛ كتابة عربية ورومانية في السنغال؛ رمز mey','مرآة عربية لوصف اللهجة وأصلها ولهجاتها الفرعية؛ تطبع عدد متحدثين لا يُسجَّل هنا.',tier='E',lang='ar'),
 dsrc(DS['cuisine'],'cuisine','مطبخ موريتاني','ويكيبيديا العربية (نسخة مرآة)','local_website','تأثيرات مغاربية وسنغالية وفرنسية؛ اثنا عشر طبقًا ومشروبًا؛ الشاي الأخضر بالنعناع يُصب من علٍ لإحداث الرغوة','مرآة عربية تصف المطبخ؛ الصفحة تحمل قالب نقص مصادر، فتُسجَّل كل مادة منها غير منشورة.',tier='E',lang='ar'),
 dsrc(DS['dress'],'dress','ملحفة','ويكيبيديا العربية (نسخة مرآة)','local_website','الملحفة للنساء والدراعة للرجال؛ العقدتان «الخلالين»؛ أربعة أمتار في متر ونصف؛ أنواع: الشَّكَّة وكنيبة وسَاغَامْبُو وكاز وكونتر وشيفون وتُوبِيتْ وصافانا وملاحف الشرق بالنيلة والشنظورة؛ دلالات شعبية للحب والغيرة','مرآة عربية للزي الموريتاني؛ لا يُستشهد بمقالة «دراعة» العباسية المنفصلة.',tier='E',lang='ar'),
 dsrc(DS['nouakchott'],'nouakchott','نواكشوط','ويكيبيديا العربية (نسخة مرآة)','local_website','اختيار الموقع 1957؛ وضع الحجر الأساس 5 مارس 1958؛ تحوّل من قرية صغيرة تفتقر لمياه جوفية صالحة للشرب؛ موقع 18°6′ شمالًا و15°57′ غربًا','مرآة عربية لسياق العاصمة؛ تطبع تقدير سكان 2013 لا يُسجَّل في أي دعوى.',tier='E',lang='ar'),
 dsrc(DS['press2010'],'press2010','نواكشوط أول عاصمة عربية مهددة بالغرق','صحيفة الخليج','local_press','رواية كبار السن عن العالم وبئر نواكشوط؛ روايتا التسمية «نوق الشط» و«نوكشوظ» أي بئر المحار؛ أسماء أحياء ومقاطعات','تقرير صحافي مؤرخ 25 مارس 2010: يُستعمل لرواية شعبية معلنة ورواية تسمية فقط.',tier='B',lang='ar',pdate='2010-03-25'),
 dsrc(DS['towns'],'towns','مدن القصور الأربع — ملخصات مرآة','ويكيبيديا العربية (نسخة مرآة)','local_website','شنقيط ووادان بولاية أدرار؛ تيشيت بولاية تكانت؛ ولاتة بولاية الحوض الشرقي','ملخصات صفحات المدن الأربع (نقطة نهاية الملخص في واجهة ويكيبيديا) لتثبيت الولاية، والعلاقة المكانية تُسجَّل local_reported.',tier='E',lang='ar'),
 dsrc(DS['sites'],'sites','مواقع أثرية موريتانية — ملخصات مرآة','ويكيبيديا (عربية وإنجليزية، نسخ مرآة)','local_website','أزوكي على هضبة آدرار؛ كمبي صالح جنوب شرق البلاد 60 كم جنوب تمبدغة؛ تگداوست في ولاية الحوض الغربي','ملخصات صفحات المواقع الثلاثة لتثبيت الموضع، بلا سكان وبلا نسبة وبلا دعاوى.',tier='E',lang='ar-en')]
def depth_items(dd):
 E2=[];R2=[];C2=[];COUNTRY='ENT-MR-COUNTRY'
 def clm(key,pred,val,sid,loc,cls,note,vs='local_reported',conf='low',st='reported',pub=False,second=None,second_loc=None,typ='json',unit=None,obs=DDATE):
  return {'id':record_id('CLM-MR-DEPTH',key),'schema_version':SCHEMA_VERSION,'subject_id':COUNTRY,'predicate':pred,'value':{'type':typ,'data':val},'unit':unit,'status':st,'observed_at':obs,'valid_from':None,'valid_to':None,'source_id':sid,'second_source_id':second,'source_locator':loc,'second_source_locator':second_loc,'sensitivity':'ordinary','notes':note,'verification_status':vs,'confidence':conf,'classification':cls,'published':pub,'lexical_context':None}
 def place(x,kind,key):
  iid=f'ENT-MR-{kind.upper()}-{x["latin"].upper().replace(" ","-")}';parent='ENT-MR-WILAYA-'+x['wilaya'] if x.get('wilaya') else COUNTRY
  sid=DS[key];loc=f"مكان بلا مقام: {x['name']} ({x['latin']}) — {x['note']}"
  E2.append({'id':iid,'schema_version':SCHEMA_VERSION,'country_code':'MR','canonical_name':x['name'],'canonical_name_language':'ar','entity_type':'city' if kind=='town' else 'archaeological_site','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':DS['ksour'] if kind=='town' else sid,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':loc,'verification_status':'source_verified' if kind=='town' else 'local_reported','confidence':'high' if kind=='town' else 'low'})
  R2.append({'id':record_id('REL-MR-LOCATED',iid,parent),'schema_version':SCHEMA_VERSION,'child_id':iid,'parent_id':parent,'relationship_type':'located_in','status':'historical' if kind=='town' else 'current','valid_from':None,'valid_to':None,'source_id':sid,'source_locator':loc,'notes':'علاقة مكانية فقط: لا أب إداري أدنى ولا سكان ولا نسبة، ولا يُنشأ مستوى مقاطعة أو بلدية في هذه الدورة.','verification_status':'local_reported','confidence':'low'})
  return iid
 for x in dd['places']['towns']:place(x,'town','towns')
 for x in dd['places']['sites']:place(x,'site','sites')
 for e in dd['ich_elements']:
  C2.append(clm('ich|'+e['reference'],'intangible_cultural_practice',{'name':e['name'],'official_title':e['official_title'],'reference':e['reference'],'year':e['year'],'list':e['list'],'url':dd['sources'][e['source']],'co_states':e['co_states'],'description':e['description']},DS[e['source']],f"قائمة اليونسكو للتراث الثقافي غير المادي: {e['official_title']} ({e['year']}, ref {e['reference']})",e['classification'],'عنصر مُدرج في قوائم اليونسكو؛ يُنشر بوصفه عنصرًا رسميًا مع تصنيف صريح: وطني لعنصر مُقدَّم من دولة واحدة، ومشترك لملف متعدد الدول. لا يُثبت عنوان عربي رسمي لهذا العنصر في هذه الدورة، والاسم العربي ترجمة وصفية للعنوان الرسمي.',vs='verified',conf='high',st='verified',pub=True))
 C2.append(clm('state|ratification','convention_ratification_date',{'convention':'اتفاقية صون التراث الثقافي غير المادي (2003)','date':'2006-11-15'},DS['state'],'صفحة الدولة: التصديق على الاتفاقية في 15 نوفمبر 2006','official','تاريخ التصديق كما ورد في صفحة الدولة، ودور موريتانيا كعضو في اللجنة 2022-2026.',vs='verified',conf='high',st='verified',pub=True))
 for p in dd['pending_nominations']:
  C2.append(clm('pending|'+p['official_title'],'unesco_pending_nomination',{'element':p['element'],'official_title':p['official_title'],'list':p['list'],'year':p['year'],'status':'قيد النظر'},DS['state'],f"الترشيحات الجارية: {p['year']} — {p['official_title']} (RL)",'official','ترشيح معلن على صفحة الدولة؛ ليس إدراجًا، ولا يجوز أن يُسجَّل عنصرًا مُدرجًا.',vs='verified',conf='high',st='verified',pub=True))
 for c in dd['constitution_provisions']:
  C2.append(clm(f"const|{c['article']}|{c['topic']}",'constitutional_provision',{'article':c['article'],'topic':c['topic'],'summary':c['summary'],'note':c['note']},DS['constitution'],f"دستور 1991 (المعدَّل 2012)، المادة {c['article']} — {c['topic']}",'official','نصّ دستوري من مصدر من الفئة A؛ يُسجَّل كما ورد ولا يُحوَّل إلى مقام إداري.',vs='verified',conf='high',st='verified',pub=True))
 for w in dd['world_heritage_properties']:
  C2.append(clm('wh|'+w['reference'],'world_heritage_property',{'name':w['name'],'reference':w['reference'],'year':w['year'],'category':w['category'],'criteria':w['criteria'],'description':w['description']},DS[w['source']],f"قائمة التراث العالمي: {w['name']} ({w['year']}, ref {w['reference']})",'official','موقع مُدرج على قائمة التراث العالمي؛ تُنشر المعايير كما وردت ولا يُضمَّن وصف ثقافي لموقع طبيعي.',vs='verified',conf='high',st='verified',pub=True))
 for t in dd['tentative_sites']:
  C2.append(clm('tent|'+t['reference'],'unesco_tentative_listing',{'name':t['name'],'reference':t['reference'],'year':t['year'],'status':'القائمة المؤقتة'},DS['whc_state'],f"القائمة المؤقتة: {t['name']} ({t['year']}, ref {t['reference']})",'official','القائمة المؤقتة ليست إدراجًا؛ تُسجَّل بوصفها نيّة ترشيح معلنة سنة 2001.',vs='verified',conf='high',st='verified',pub=True))
 for l in dd['language_presence']:
  off=bool(l['official']);nat=l['level']=='national';sec=DS[l['second']] if l.get('second') else None
  C2.append(clm('lang|'+l['name'],'language_presence',{'name':l['name'],'official':off,'level':l['level'],'iso_codes':l.get('codes',[]),'note':l['note']},DS[l['source']],f"حضور لغوي: {l['name']}",'official' if off else ('national' if nat else 'regional'),('لغة رسمية بنصّ المادة 6 من الدستور.' if off else ('لغة وطنية بنصّ المادة 6 من الدستور وهي ليست اللغة الرسمية.' if nat else 'لغة غير رسمية من مرآة/سجل؛ لا يُسجَّل عدد متحدثين ولا نسبة ولا نطاق إداري.')),vs='verified' if off or nat else 'local_reported',conf='high' if off or nat else 'low',st='verified' if off or nat else 'reported',pub=off or nat,second=sec,second_loc=('ISO 639-3 registry entry' if sec else None)))
 for p in dd['dialect_profiles']:
  C2.append(clm('dialect|'+p['variety'],'dialect_profile',{'variety':p['variety'],'group':p['group'],'features':p['features']},DS[p['source']],f"لهجة: {p['variety']}",'regional','وصف لهجي مصنَّف من مرآة؛ لا يُنسب إلى مقام ولا يُبنى عليه مقام ولا يُنشر.'))
 for p in dd['script_profiles']:
  C2.append(clm('script|'+p['name'],'script_profile',{'name':p['name'],'features':p['features']},DS[p['source']],f"كتابة: {p['name']}",'regional','وصف كتابة مصنَّف من مرآة؛ لا يُنشر ولا يُبنى عليه مقام.'))
 for x in dd['crafts']:
  C2.append(clm('craft|'+x['name'],'craft_custom',{'name':x['name'],'description':x['desc']},DS[x['source']],f"حرفة محلية: {x['name']}",'local','حرفة ونقل معرفة من مرجع رسمي أو مرآة؛ تُعرض وصفًا لا إحصاءً.',vs='local_reported',conf='low'))
 for x in dd['customs']:
  C2.append(clm('custom|'+x['name'],'custom_practice',{'name':x['name'],'description':x['desc']},DS[x['source']],f"عرف محلي: {x['name']}",'popular','عرف اجتماعي محلي مصنَّف وغير منشور؛ يُفصل عن عناصر اليونسكو ولا يُساوى بها.'))
 for x in dd['narratives']:
  folk=x['kind']=='folk_narrative'
  C2.append(clm('narr|'+x['name'],'place_name_narrative' if not folk else 'folk_narrative',{'name':x['name'],'description':x['desc']},DS[x['source']],f"رواية محلية: {x['name']}",'folk_narrative' if folk else 'local_reported',x['desc'],vs='folk_narrative' if folk else 'local_reported',conf='low',st='reported',pub=False))
 C2.append(clm('history|founding-nouakchott','city_founding',{'detail':dd['city_founding']['desc']},DS['nouakchott'],'تأسيس العاصمة: اختيار الموقع 1957 والحجر الأساس 5 مارس 1958','historical','سياق تاريخي للعاصمة من مرآة عربية؛ لا يُسجَّل فيه أي عدد سكان.',vs='local_reported',conf='low',st='historical',pub=False))
 for x in dd['dishes']:
  C2.append(clm('dish|'+x['name'],'food_dish',{'name':x['name'],'description':x['desc']},DS['cuisine'],f"طبق موريتاني: {x['name']}",'local','معرفة طعام محلية مصنَّفة وغير منشورة؛ لا تُنشر صفة «وطنية» إلا كما وردت في المصدر.'))
 for x in dd['dress']:
  C2.append(clm('dress|'+x['name'],'clothing_item',{'name':x['name'],'gender':x['gender'],'description':x['desc']},DS['dress'],f"زي محلي: {x['name']}",'popular','وصف لباس تقليدي مصنَّف وغير منشور.'))
 return E2,R2,C2
def depth_layers():
 return [{'layer':'unesco_intangible_heritage','entity_types':['cultural_site'],'local_names':['عنصر تراث غير مادي'],'authority_name':'UNESCO Intangible Cultural Heritage','denominator':9,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['state'],DS['theydinn'],DS['mahadra'],DS['samba'],DS['couscous'],DS['calligraphy'],DS['datepalm'],DS['engraving'],DS['henna'],DS['zaffa']],'license':ILOC,'scope_status':'closed','notes':'تسعة عناصر مُدرجة لموريتانيا: ثلاثة وطنية (الملحمة الموريّة 00524 على قائمة الصون العاجل 2011، والمحضرة 01960 وملحمة سامبا غيلاديو 01692 على القائمة التمثيلية) وستة مشتركة، وثلاثة ترشيحات 2026 معلنة.','special_cases':['الملفات المشتركة تبقى shared ولا يُدَّعى فيها حصرية.','تصنيف national محصور بالعناصر المُقدَّمة من موريتانيا وحدها.','الترشيح المعلن ليس إدراجًا.']},
 {'layer':'world_heritage_properties','entity_types':['city','archaeological_site'],'local_names':['موقع تراث عالمي'],'authority_name':'UNESCO World Heritage Centre','denominator':2,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['ksour'],DS['whc_state']],'license':ILOC,'scope_status':'closed','notes':'موقعان مُدرجان: قصور وادان وشنقيط وتشيت ووالاتا (ثقافي 1996، المعايير iii/iv/v) ومحمية بانك دارغان (طبيعي 1989)؛ وثلاثة مواقع في القائمة المؤقتة سنة 2001 تُسجَّل ولا تُعدّ إدراجًا.','special_cases':['لا يُوصف الموقع الطبيعي وصفًا ثقافيًا.','القائمة المؤقتة ليست إدراجًا.']},
 {'layer':'heritage_places','entity_types':['city','archaeological_site'],'local_names':['مكان بلا مقام'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['towns'],DS['sites']],'license':WLOC,'scope_status':'open','notes':'سبعة أماكن بلا مقام: أربع مدن قصور بمستوى city وثلاثة مواقع أثرية، كلها بعلاقة located_in واحدة فقط: بلا أب إداري وبلا سكان وبلا نسبة وبلا دعاوى.','special_cases':['لا يُنشأ مستوى مقاطعة أو بلدية ولا يُستنتج للأماكن أب أدنى.']},
 {'layer':'classified_local_knowledge','entity_types':['cultural_site'],'local_names':['معرفة محلية مصنَّفة'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['languages'],DS['hassaniya'],DS['cuisine'],DS['dress'],DS['nouakchott'],DS['press2010'],DS['state']],'license':WLOC,'scope_status':'open','notes':'معرفة محلية مصنَّفة وغير منشورة: أحد عشر ملفًا لغويًا، ولهجة وكتابة، وحرفة مرشَّحة، وعرفان، ورواية شعبية ورواية تسمية وتأسيس العاصمة، واثنا عشر طبقًا، وزيّان.','special_cases':['لا يُنشر أي ادعاء ضعيف المصدر ولا يُبنى عليه مقام.','لا تُسجَّل أعداد متحدثين ولا نسب ولا أعداد سكان.']}]
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['wilayas'])==15 and sum(x['profile']=='nouakchott_capital' for x in f['wilayas'])==3 and hashlib.sha256(b).hexdigest()==next(r['sha256'] for r in m['records'] if r['path']=='data/imports/mauritania/fixtures/wilaya_profiles.json')
 dd=L(D);assert hashlib.sha256(D.read_bytes()).hexdigest()==next(r['sha256'] for r in m['records'] if r['path']=='data/imports/mauritania/fixtures/cultural_depth_2026.json')
 assert (len(dd['ich_elements']),len(dd['pending_nominations']),len(dd['world_heritage_properties']),len(dd['tentative_sites']),len(dd['constitution_provisions']),len(dd['language_presence']),len(dd['dialect_profiles']),len(dd['script_profiles']),len(dd['crafts']),len(dd['customs']),len(dd['narratives']),len(dd['dishes']),len(dd['dress']))==(9,3,2,3,5,11,1,1,1,2,2,12,2)
 assert len(dd['places']['towns'])==4 and len(dd['places']['sites'])==3
 assert sum(1 for e in dd['ich_elements'] if e['classification']=='national')==3 and sum(1 for e in dd['ich_elements'] if e['classification']=='shared')==6
 S=[src(DGAT,'Découpage administratif de Mauritanie','Direction Générale de l’Administration Territoriale','official_register',f['sources']['dgat'],'15 wilayas and 63 moughataas','Current upper denominator.'),src(RGPH,'RGPH-5 — population by wilaya, moughataa and commune','ANSADE','census',f['sources']['ansade'],'bilingual 2024 census geography','Record-level census cross-check.'),src(REV,'Revue par les pairs du système statistique national','ANSADE','official_report',f['sources']['peer_review'],'15 regions, 63 moughataas, 219 communes','Current commune-count candidate; older 220 retained as conflict.')]+depth_sources()
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'MR','sources':S});E=[];R=[];C=[]
 for q in f['wilayas']:
  eid='ENT-MR-WILAYA-'+q['code'];loc=f"DGAT/RGPH-5 wilaya {q['code']}: {q['name_fr']}; profile {q['profile']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'MR','canonical_name':q['name_fr'],'canonical_name_language':'fr','entity_type':'mr_wilaya','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':DGAT,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Nouakchott wilayas remain wilayas, not inferred city neighborhoods.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-MR',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-MR-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':DGAT,'source_locator':loc,'notes':None,'verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-MR','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':DGAT,'second_source_id':RGPH,'source_locator':loc,'sensitivity':'ordinary','notes':'Profile controls future lower-topology import.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'RGPH-5 wilaya geography','lexical_context':None})
 DE,DR,DC=depth_items(dd);E+=DE;R+=DR;C+=DC
 ids={x['id'] for x in E}|{'ENT-MR-COUNTRY'}
 rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='MR' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-MR-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-MR-'),R)
 C.extend([{'id':record_id('CLM-MR','moughataa-count'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-MR-COUNTRY','predicate':'moughataa_count','value':{'type':'integer','data':63},'unit':'moughataa','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':DGAT,'second_source_id':REV,'source_locator':'DGAT current summary','sensitivity':'ordinary','notes':'Known count; records deferred.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'peer review administrative summary','lexical_context':None},{'id':record_id('CLM-MR','commune-count-conflict'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-MR-COUNTRY','predicate':'commune_count_candidates','value':{'type':'json','data':[219,220]},'unit':'commune','status':'disputed','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':REV,'second_source_id':RGPH,'source_locator':'peer review: 219 communes','sensitivity':'ordinary','notes':'Older official publications report 220; no denominator accepted.','verification_status':'source_verified','confidence':'medium','classification':'disputed','published':True,'second_source_locator':'RGPH/legacy commune universe requires legal reconciliation','lexical_context':None}])
 rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MR','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':DGAT,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MR','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':DGAT,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('WILAYAS','mr_wilaya',15),('NOUAKCHOTT-WILAYAS','mr_wilaya_nouakchott_profile',3),('REGIONAL-WILAYAS','mr_wilaya_regional_profile',12)];ds=[d('DEN-MR-'+a,l,n,f'Exact {l} denominator.') for a,l,n in specs];vs=[v('COV-MR-'+a,l,'DEN-MR-'+a,n,f'{n}/{n} matched.') for a,l,n in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='MR' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='MR' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Mauritania 15-wilaya profile pilot, extended with ICH/World Heritage and classified local knowledge','captured_at':DATE,'source_id':DGAT,'scope':'15 wilayas: three Nouakchott and twelve regional, plus nine ICH elements, two World Heritage properties and seven places without rank','method':'Checksum-bound DGAT/ANSADE reconciliation plus UNESCO/Constitute/ISO registry depth cycle 1.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'63 moughataas known/open; communes conflicted 219/220; depth layers carry no denominator.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-MR-'),[snap])
 man=L(ROOT/'manifests/MR.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'DGAT / ANSADE','source_ids':[DGAT,RGPH,REV],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-MR-COUNTRY-SCOPE',*[f'COV-MR-{a}' for a,_,_ in specs]],'caveats':['Nouakchott wilayas are not inferred neighborhoods.','63 moughataas known but records deferred.','Commune denominator conflicted 219/220.','Depth layers carry no denominator and no inherited population.'],'next_action':'Import 63 moughataas from current register; resolve commune count before commune entities; keep heritage places located_in-only.'})
 for x in man['hierarchy']:
  if x['entity_type']=='mr_wilaya':x.update({'source_ids':[DGAT,RGPH],'verification_status':'verified','authority_name':'DGAT / ANSADE','denominator':15,'denominator_id':'DEN-MR-WILAYAS','coverage_record_id':'COV-MR-WILAYAS','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'15 wilayas.','special_cases':['Three Nouakchott wilayas.']})
  elif x['entity_type']=='mr_moughataa':x.update({'verification_status':'pending','authority_name':'DGAT','denominator':63,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'open','notes':'Known count, records deferred.','special_cases':[]})
  elif x['entity_type']=='mr_commune':x.update({'verification_status':'pending','authority_name':'DGAT / ANSADE','denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'open','notes':'Conflicted 219/220.','special_cases':['No denominator until legal reconciliation.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['mr_wilaya'],'local_names':['wilaya'],'authority_name':'DGAT','denominator':n,'denominator_id':'DEN-MR-'+a,'coverage_record_id':'COV-MR-'+a,'snapshot_date':DATE,'source_ids':[DGAT,RGPH],'license':LIC,'scope_status':'closed','notes':'Profile layer.','special_cases':[]} for a,l,n in specs]+depth_layers();write_json(ROOT/'manifests/MR.yml',man);write_json(ROOT/'data/cultural/mauritania_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'MR','snapshot_date':DDATE,'domains':{'world_heritage':{'status':'documented_two_inscribed_one_natural','properties':['قصور وادان وشنقيط وتشيت ووالاتا (ثقافي 1996، ref 750)','محمية بانك دارغان الوطنية (طبيعي 1989، ref 506)'],'tentative_list_sites':3},'intangible_cultural_heritage':{'status':'documented_nine_elements_three_national','elements':9,'national':3,'shared':6,'pending_nomination':'العود · السعفيات وألياف النباتات · الحناء (2026)'},'languages':{'status':'documented_one_official_four_national_published_rest_unpublished','claims':11},'dialect':{'status':'documented_local_reported_unpublished','claims':1},'script':{'status':'documented_local_reported_unpublished','claims':1},'crafts':{'status':'documented_local_reported_unpublished','claims':1},'custom':{'status':'documented_local_reported_unpublished','claims':2},'narratives':{'status':'documented_folk_and_naming_narratives_unpublished','claims':2},'food':{'status':'documented_local_reported_unpublished','claims':12},'dress':{'status':'documented_local_reported_unpublished','claims':2},'capital_history':{'status':'documented_local_reported_unpublished','claims':1},'heritage_places':{'status':'documented_places_no_denominator','entities':7,'denominator':None},'language_institutions':{'status':'not_documented_in_cycle','claims':0}},'notes':'Nine inscribed elements, one of them on the Urgent Safeguarding List; no speaker counts, no population figures and no lower administrative levels in this cycle.'});print(json.dumps({'entities':len(E),'relationships':len(R),'claims':len(C),'depth_claims':len(DC),'places':len([e for e in E if e['entity_type'] in ('city','archaeological_site')]),'sources':len(S)}))
if __name__=='__main__':main()
