#!/usr/bin/env python3
import json,hashlib,re
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/palestine';F=I/'fixtures/statistical_governorates_2026.json';DP=I/'fixtures/depopulated_1948_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-PS-PRODUCTION-20260817';PCBS='SRC-PS-PCBS-16-GOVERNORATES';MOLG='SRC-PS-MOLG-LOCAL-GOVERNMENT';WHC='SRC-UNESCO-WHC-PS-2026';SEB='SRC-UNESCO-WHC-PS-SEBASTIA-2026';ARCH='SRC-PS-DEPOPULATED-ARCHIVE-2026';WAFA='SRC-PS-WAFA-PLO-DESTROYED-2026';LIC='Official Palestine statistical/government material; factual extraction with attribution; reuse terms not stated';WL='CC BY-SA 3.0 IGO for UNESCO descriptions'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def tok(s):return re.sub('[^A-Z0-9]+','-',s.upper()).strip('-')
def src(i,t,p,ty,u,loc,note,lic=LIC,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':lic,'language':'ar-en','country_codes':['PS'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();rec={r['path'].split('/')[-1]:r['sha256'] for r in m['records']};fd=L(DP)
 assert len(f['governorates'])==16 and len(f['world_heritage'])==6 and hashlib.sha256(b).hexdigest()==rec['statistical_governorates_2026.json']
 assert hashlib.sha256(DP.read_bytes()).hexdigest()==rec['depopulated_1948_2026.json'] and sum(len(q['sites']) for q in fd['qadas'])==584 and len(fd['qadas'])==8
 S=[src(PCBS,'PCBS 16-governorate statistical geography','Palestinian Central Bureau of Statistics','census',f['sources']['pcbs'],'11 West Bank and 5 Gaza Strip governorates','Statistical/legal scope; no effective-control claim.'),src(MOLG,'Ministry of Local Government mandate and legal framework','Ministry of Local Government','official_register',f['sources']['molg'],'local-government authority and entity semantics','Local authorities distinct from localities/camps.'),src(WHC,'World Heritage List — State of Palestine','UNESCO World Heritage Centre','institutional_dataset',f['sources']['whc'],'six inscribed properties through 2026','Current six-property denominator.',WL),src(SEB,'Sebastia emergency inscription and danger decision','UNESCO World Heritage Committee','institutional_page',f['sources']['sebastia'],'Decision 48 COM 8B.3; property 1809','Emergency inscription and List in Danger.',WL,pub='2026-07-29'),{'id':ARCH,'schema_version':SCHEMA_VERSION,'title':'Depopulated 1948 localities — documentary archive compilation, eight qada files','publisher':'Palestine Remembered documentary archive via project qada compilations','source_type':'archive','url':fd['sources']['archive_mirror'],'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['PS'],'locator':'Per-qada site tables: Safad 95, Acre 73, Tiberias 31, Haifa 92, Jenin 100, Ramla 70, Jerusalem 30, Beersheba 93','checksum':'sha256:'+hashlib.sha256(DP.read_bytes()).hexdigest(),'quality_tier':'C','notes':'Widely used documentary archive counting every inhabited locality (village, khirba, Bedouin camp, farm). Site identities carry probable status; per-site condition is never inferred; same-name sites in different qadas stay distinct. Publication date unavailable.'},{'id':WAFA,'schema_version':SCHEMA_VERSION,'title':'Destroyed villages 1948 — WAFA/PLO refugee department frame','publisher':'WAFA news agency / PLO Department of Refugee Affairs','source_type':'institutional_page','url':fd['sources']['wafa_plo'],'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['PS'],'locator':'531 fully destroyed localities; 805,067 refugees in 1948; qada distribution table totalling 377','checksum':'sha256:'+hashlib.sha256(DP.read_bytes()).hexdigest(),'quality_tier':'B','notes':'Official-institutional national frame. Count disputes (531/530/~520/775-seized) are recorded verbatim and never averaged; the administrative-village vs inhabited-locality definition difference is preserved. Publication date unavailable.'}]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'PS','sources':S});E=[];A=[];R=[];C=[]
 for q in f['governorates']:
  eid='ENT-PS-GOVERNORATE-'+q['code'];loc=f"PCBS governorate code {q['code']}: {q['name_ar']} / {q['name_en']}; region {q['statistical_region']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'PS','canonical_name':q['name_ar'],'canonical_name_language':'ar','entity_type':'ps_governorate','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':PCBS,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Current statistical/legal identity only; no assertion of effective control or current damage condition.','verification_status':'verified','confidence':'high'});A.append({'id':record_id('ALS-PS',eid,q['name_en']),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':q['name_en'],'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':PCBS,'source_locator':loc,'valid_from':None,'valid_to':None});R.append({'id':record_id('REL-PS',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-PS-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':PCBS,'source_locator':loc,'notes':'Statistical/legal parent only.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-PS','statistical-region',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'statistical_region','value':{'type':'string','data':q['statistical_region']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':PCBS,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':'Not an effective-control or access claim.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 for w in f['world_heritage']:
  eid='ENT-PS-CULTURAL-SITE-'+str(w['reference']);s=SEB if w['reference']==1809 else WHC;loc=f"UNESCO property {w['reference']}: {w['name']}; inscribed {w['inscription_year']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'PS','canonical_name':w['name'],'canonical_name_language':'en','entity_type':'cultural_site','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':s,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'World Heritage property identity; current conservation/access condition is not inferred.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-PS',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-PS-COUNTRY','relationship_type':'associated_with','status':'current','valid_from':None,'valid_to':None,'source_id':s,'source_locator':loc,'notes':'Country association only.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-PS','whc-year',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'world_heritage_inscription_year','value':{'type':'integer','data':w['inscription_year']},'unit':'year','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':s,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':None,'verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
  if w['reference']==1809:
   for pred in ['emergency_inscription','world_heritage_in_danger'] :C.append({'id':record_id('CLM-PS',pred,eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':pred,'value':{'type':'boolean','data':True},'unit':None,'status':'verified','observed_at':'2026-07-29','valid_from':'2026-07-29','valid_to':None,'source_id':SEB,'second_source_id':None,'source_locator':'Decision 48 COM 8B.3','sensitivity':'ordinary','notes':'UNESCO status only; no broader security inference.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 # 1948 depopulated-localities depth cycle: historical qadas + 584 archive-attested sites.
 from model import entity_id
 for q in fd['qadas']:
  qid='ENT-PS-HIST-QADA-'+q['token'];qloc=f"Historical qada frame (Mandate-era): {q['name_ar']}"
  E.append({'id':qid,'schema_version':SCHEMA_VERSION,'country_code':'PS','canonical_name':'قضاء '+q['name_ar'],'canonical_name_language':'ar','entity_type':'ps_historical_qada','status':'historical','valid_from':None,'valid_to':'1948-12-31','canonical_source_id':WAFA,'source_locator':qloc,'legacy_ids':[],'coordinates':None,'notes':'Mandate-era historical qada used as the 1948 documentation frame; entirely separate from the current 16-governorate structure.'+((' '+q['note']) if q['note'] else ''),'verification_status':'probable','confidence':'medium'})
  R.append({'id':record_id('REL-PS-HQ',qid),'schema_version':SCHEMA_VERSION,'child_id':qid,'parent_id':'ENT-PS-COUNTRY','relationship_type':'associated_with','status':'historical','valid_from':None,'valid_to':'1948-12-31','source_id':WAFA,'source_locator':qloc,'notes':'Historical frame association; not a current administrative parent.','verification_status':'probable','confidence':'medium'})
  if q['wafa_admin_count'] is not None:
   C.append({'id':record_id('CLM-PS-QADACOUNT',qid),'schema_version':SCHEMA_VERSION,'subject_id':qid,'predicate':'destroyed_villages_wafa_count','value':{'type':'integer','data':q['wafa_admin_count']},'unit':'village','status':'reported','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':WAFA,'second_source_id':None,'source_locator':f"WAFA qada distribution row: {q['name_ar']}",'sensitivity':'ordinary','notes':'Administrative-village count from the WAFA/PLO frame; differs by definition from the archive inhabited-locality count and both are preserved.','verification_status':'probable','confidence':'medium','classification':'historical','published':False,'second_source_locator':None,'lexical_context':None})
  for i,name in enumerate(q['sites']):
   sid=entity_id('PS','historical_place',name,f"{qid}|{i+1}")
   loc=f"Archive qada table {q['name_ar']}, seq {i+1}: {name}"
   E.append({'id':sid,'schema_version':SCHEMA_VERSION,'country_code':'PS','canonical_name':name,'canonical_name_language':'ar','entity_type':'historical_place','status':'historical','valid_from':None,'valid_to':None,'canonical_source_id':ARCH,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'1948-frame inhabited locality attested in the documentary archive; site identity only — physical condition, depopulation completeness, and present state are never inferred. Same-name sites in other qadas are distinct localities.','verification_status':'probable','confidence':'medium'})
   R.append({'id':record_id('REL-PS-SITE',sid,qid),'schema_version':SCHEMA_VERSION,'child_id':sid,'parent_id':qid,'relationship_type':'located_in','status':'historical','valid_from':None,'valid_to':None,'source_id':ARCH,'source_locator':loc,'notes':'Located in its Mandate-era qada frame; never attached to the current governorate tree.','verification_status':'probable','confidence':'medium'})
 C.append({'id':record_id('CLM-PS-NAKBA-FRAME'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-PS-COUNTRY','predicate':'depopulation_frame_1948','value':{'type':'json','data':{'plo_destroyed_total':531,'other_readings':[530,520],'seized_total':775,'refugees_1948':805067,'descendants_2009':6837000,'archive_attested_in_project':584}},'unit':None,'status':'reported','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':WAFA,'second_source_id':None,'source_locator':'WAFA/PLO national frame with recorded count disputes','sensitivity':'ordinary','notes':'National count disputes recorded verbatim; the seized/destroyed distinction explains divergence; no reading is averaged or adopted as a closed denominator.','verification_status':'probable','confidence':'medium','classification':'historical','published':False,'second_source_locator':None,'lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-PS-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='PS' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-PS-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-PS-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'PS','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':s,'source_locator':note,'license':lic,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'PS','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':lic,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('GOVERNORATES','ps_governorate',16,PCBS,LIC),('WEST-BANK','ps_governorate_west_bank',11,PCBS,LIC),('GAZA','ps_governorate_gaza',5,PCBS,LIC),('WHC','world_heritage_property',6,WHC,WL)];ds=[d('DEN-PS-'+a,l,n,s,lic,f'Exact {l} denominator.') for a,l,n,s,lic in specs];vs=[v('COV-PS-'+a,l,'DEN-PS-'+a,n,s,lic,f'{n}/{n} matched; legal/statistical or UNESCO scope only.') for a,l,n,s,lic in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='PS' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='PS' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Palestine statistical governorates and 2026 World Heritage','captured_at':DATE,'source_id':PCBS,'scope':'16 governorates and six World Heritage properties','method':'Checksum-bound statistical/legal and UNESCO scopes; no de facto overlay.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Localities/local authorities/camps and dated damage/displacement overlays deferred.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-PS-'),[snap])
 man=L(ROOT/'manifests/PS.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'PCBS / Ministry of Local Government','source_ids':[PCBS,MOLG,WHC,SEB],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-PS-COUNTRY-SCOPE',*[f'COV-PS-{a}' for a,_,_,_,_ in specs]],'caveats':['Governorates are legal/statistical scopes, not effective-control claims.','Local authorities, localities, and camps are distinct and deferred.','Damage/displacement requires separately dated evidence.'],'next_action':'Maintain 16 statistical governorates; add overlays/local units only with dated source-specific evidence.'})
 for x in man['hierarchy']:
  if x['entity_type']=='ps_governorate':x.update({'source_ids':[PCBS],'verification_status':'verified','authority_name':'PCBS','denominator':16,'denominator_id':'DEN-PS-GOVERNORATES','coverage_record_id':'COV-PS-GOVERNORATES','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Statistical/legal scope only.','special_cases':['No effective-control inference.']})
  elif x['entity_type']=='ps_local_government_unit':x.update({'verification_status':'pending','authority_name':'Ministry of Local Government','denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'Current atomic authority register not yet imported.','special_cases':['Do not merge locality/camp/local authority.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['ps_governorate' if l.startswith('ps_') else 'cultural_site'],'local_names':['scope'],'authority_name':'PCBS / UNESCO','denominator':n,'denominator_id':'DEN-PS-'+a,'coverage_record_id':'COV-PS-'+a,'snapshot_date':DATE,'source_ids':[s],'license':lic,'scope_status':'closed','notes':'Source-specific scope.','special_cases':[]} for a,l,n,s,lic in specs];write_json(ROOT/'manifests/PS.yml',man);write_json(ROOT/'data/cultural/palestine_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'PS','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented','denominator':6,'claims':8},'dialect':{'status':'not_documented_in_cycle','claims':0}},'notes':'No damage/displacement inference from heritage or statistical identity.'});print(json.dumps({'entities':614,'aliases':16,'relationships':614,'claims':31,'sources':6}))
if __name__=='__main__':main()
