#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,entity_id,norm_name
I=ROOT/'data/imports/libya';F=I/'fixtures/current_municipalities_2026.json';M=I/'snapshot_manifest_production.json';DATE='2026-08-17';SNAP='SNP-LY-MUNICIPALITIES-2026-08-17';MOLG='SRC-LY-MOLG-MUNICIPALITIES-2026';BSC='SRC-LY-BSC-CENSUS-2006';LIC='License not stated on source page'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['municipalities'])==141 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 source=L(ROOT/'data/sources/ly-molg-municipalities-2026.json');source.update({'retrieved_at':DATE,'checksum':'sha256:'+hashlib.sha256(b).hexdigest(),'locator':'Complete rendered municipalities catalogue: 141 named entries; numbering gaps 124 and 140 are presentation gaps, not missing records','notes':'Publication/content-effective date unavailable. The rendered catalogue was enumerated exactly on 2026-08-17; 141 names are accepted as the current source snapshot. Number labels skip 124 and 140 while the record count remains 141.'});write_json(ROOT/'data/sources/ly-molg-municipalities-2026.json',source);write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'LY','sources':[source,L(ROOT/'data/sources/ly-law-59-2012.json'),L(ROOT/'data/sources/ly-bsc-census-2006.json')]})
 all_e=read_jsonl(ROOT/'data/entities/entities.jsonl');ly=[r for r in all_e if r.get('country_code')=='LY'];country=next(r for r in ly if r['entity_type']=='country');hist=[r for r in ly if r['entity_type']=='ly_shabiya_historical'];existing={norm_name(r['canonical_name']):r for r in ly if r['entity_type']=='ly_municipality'};municip=[]
 for q in f['municipalities']:
  name=q['name_ar'];r=existing.get(norm_name(name),{'id':entity_id('LY','ly_municipality',name,'ENT-LY-COUNTRY'),'legacy_ids':[],'coordinates':None,'valid_from':None,'valid_to':None});r.update({'schema_version':SCHEMA_VERSION,'country_code':'LY','canonical_name':name,'canonical_name_language':'ar','entity_type':'ly_municipality','status':'current','canonical_source_id':MOLG,'source_locator':f"municipalities catalogue entry position {q['catalog_position']}: {name}",'notes':'Current municipality in exact 2026-08-17 Ministry catalogue; catalogue presence does not imply effective-control status.','verification_status':'source_verified','confidence':'high'});municip.append(r)
 write_jsonl(ROOT/'data/entities/entities.jsonl',[r for r in all_e if r.get('country_code')!='LY']+[country]+hist+municip)
 all_r=read_jsonl(ROOT/'data/relationships/relationships.jsonl');histids={r['id'] for r in hist};keep=[r for r in all_r if not r.get('child_id','').startswith('ENT-LY-') or r.get('child_id') in histids];rels=[]
 for r in municip:rels.append({'id':'REL-'+hashlib.sha256(('LY|'+r['id']).encode()).hexdigest()[:16].upper(),'schema_version':SCHEMA_VERSION,'child_id':r['id'],'parent_id':'ENT-LY-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':MOLG,'source_locator':r['source_locator'],'notes':'Current legal catalogue relation only; no effective-control inference.','verification_status':'source_verified','confidence':'high'})
 write_jsonl(ROOT/'data/relationships/relationships.jsonl',keep+rels)
 denoms=read_jsonl(ROOT/'data/coverage/denominators.jsonl');d=next(r for r in denoms if r['id']=='DEN-LY-CURRENT-MUNICIPALITIES');d.update({'value':141,'denominator':141,'as_of':DATE,'snapshot_date':DATE,'status':'official','source_locator':'Complete 141-name rendered catalogue captured 2026-08-17','missing_reason':None,'notes':'Exact source snapshot; no claim about effective control or mahallas.'});write_jsonl(ROOT/'data/coverage/denominators.jsonl',denoms)
 cov=read_jsonl(ROOT/'data/coverage/coverage.jsonl');c=next(r for r in cov if r['id']=='COV-LY-CURRENT-MUNICIPALITIES');c.update({'snapshot_id':SNAP,'matched':141,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':'141/141 exact Ministry catalogue names; numbering gaps are presentation gaps.','denominator':141,'snapshot_date':DATE,'coverage_percentage':100.0,'exclusion_reasons':[]});mah=next(r for r in cov if r['id']=='COV-LY-MAHALLAS');mah.update({'snapshot_id':SNAP,'snapshot_date':DATE});write_jsonl(ROOT/'data/coverage/coverage.jsonl',cov)
 snaps=read_jsonl(ROOT/'data/snapshots/snapshots.jsonl');snaps=[r for r in snaps if r['id'] not in {'SNP-LY-MUNICIPALITIES-2026-08-15',SNAP}];snaps.append({'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Libya exact Ministry municipality catalogue','captured_at':DATE,'source_id':MOLG,'scope':'141 current catalogue municipality names','method':'Exact rendered catalogue enumeration; no cross-authority union.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Effective control, mahallas, and alternate-authority lists remain separate/unavailable.'});write_jsonl(ROOT/'data/snapshots/snapshots.jsonl',snaps)
 man=L(ROOT/'manifests/LY.yml');man['snapshot']={'as_of':DATE,'snapshot_id':SNAP,'status':'verified'};man['official_authority']={'name':'وزارة الحكم المحلي / مصلحة الإحصاء والتعداد','source_ids':[MOLG,'SRC-LY-LAW-59-2012',BSC],'verification_status':'verified','missing_reason':None};man['caveats']=['141 municipalities close only the exact Ministry catalogue snapshot; no effective-control claim.','22 historical sha’biyat remain 2006-only and never parent current municipalities.','Mahalla denominator unavailable.'];man['next_action']='Maintain exact 141 catalogue; add effective-control or alternate-authority overlays only as dated Claims.'
 for x in man['hierarchy']:
  if x['entity_type']=='ly_municipality':x.update({'denominator':141,'denominator_id':'DEN-LY-CURRENT-MUNICIPALITIES','coverage_record_id':'COV-LY-CURRENT-MUNICIPALITIES','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Exact Ministry catalogue snapshot.','special_cases':['No effective-control inference.']})
  elif x['entity_type']=='ly_mahalla':x.update({'denominator':None,'denominator_id':'DEN-LY-MAHALLAS','coverage_record_id':'COV-LY-MAHALLAS','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'No complete national register.','special_cases':[]})
 man['pilot_layers']=[{'layer':'current_municipalities','entity_types':['ly_municipality'],'local_names':['بلدية'],'authority_name':'وزارة الحكم المحلي','denominator':141,'denominator_id':'DEN-LY-CURRENT-MUNICIPALITIES','coverage_record_id':'COV-LY-CURRENT-MUNICIPALITIES','snapshot_date':DATE,'source_ids':[MOLG],'license':LIC,'scope_status':'closed','notes':'Exact catalogue snapshot.','special_cases':['No effective-control inference.']},{'layer':'historical_shabiyat_2006','entity_types':['ly_shabiya_historical'],'local_names':['شعبية تاريخية'],'authority_name':'مصلحة الإحصاء والتعداد','denominator':22,'denominator_id':'DEN-LY-HISTORICAL-SHABIYAT-2006','coverage_record_id':'COV-LY-HISTORICAL-SHABIYAT-2006','snapshot_date':'2006-04-15','source_ids':[BSC],'license':LIC,'scope_status':'closed','notes':'Historical only.','special_cases':[]}];write_json(ROOT/'manifests/LY.yml',man);write_json(ROOT/'data/cultural/libya_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'LY','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_refresh'},'dialect':{'status':'not_documented_in_cycle','claims':0}},'notes':'Administrative refresh only.'});print(json.dumps({'municipalities':141,'historical_shabiyat':22,'new_municipalities':141-len(existing)}))
if __name__=='__main__':main()
