#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/mauritania';F=I/'fixtures/wilaya_profiles.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';SNAP='SNP-MR-PRODUCTION-20260816';DGAT='SRC-MR-DGAT-15-63-2026';RGPH='SRC-MR-ANSADE-RGPH5-2024';REV='SRC-MR-ANSADE-PEER-REVIEW-2024';LIC='Official Mauritania administrative/statistical material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar-fr','country_codes':['MR'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+' Publication date unavailable.'}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['wilayas'])==15 and sum(x['profile']=='nouakchott_capital' for x in f['wilayas'])==3 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(DGAT,'Découpage administratif de Mauritanie','Direction Générale de l’Administration Territoriale','official_register',f['sources']['dgat'],'15 wilayas and 63 moughataas','Current upper denominator.'),src(RGPH,'RGPH-5 — population by wilaya, moughataa and commune','ANSADE','census',f['sources']['ansade'],'bilingual 2024 census geography','Record-level census cross-check.'),src(REV,'Revue par les pairs du système statistique national','ANSADE','official_report',f['sources']['peer_review'],'15 regions, 63 moughataas, 219 communes','Current commune-count candidate; older 220 retained as conflict.')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'MR','sources':S});E=[];R=[];C=[]
 for q in f['wilayas']:
  eid='ENT-MR-WILAYA-'+q['code'];loc=f"DGAT/RGPH-5 wilaya {q['code']}: {q['name_fr']}; profile {q['profile']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'MR','canonical_name':q['name_fr'],'canonical_name_language':'fr','entity_type':'mr_wilaya','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':DGAT,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Nouakchott wilayas remain wilayas, not inferred city neighborhoods.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-MR',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-MR-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':DGAT,'source_locator':loc,'notes':None,'verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-MR','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':DGAT,'second_source_id':RGPH,'source_locator':loc,'sensitivity':'ordinary','notes':'Profile controls future lower-topology import.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'RGPH-5 wilaya geography','lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-MR-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='MR' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-MR-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-MR-'),R)
 C.extend([{'id':record_id('CLM-MR','moughataa-count'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-MR-COUNTRY','predicate':'moughataa_count','value':{'type':'integer','data':63},'unit':'moughataa','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':DGAT,'second_source_id':REV,'source_locator':'DGAT current summary','sensitivity':'ordinary','notes':'Known count; records deferred.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'peer review administrative summary','lexical_context':None},{'id':record_id('CLM-MR','commune-count-conflict'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-MR-COUNTRY','predicate':'commune_count_candidates','value':{'type':'json','data':[219,220]},'unit':'commune','status':'disputed','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':REV,'second_source_id':RGPH,'source_locator':'peer review: 219 communes','sensitivity':'ordinary','notes':'Older official publications report 220; no denominator accepted.','verification_status':'source_verified','confidence':'medium','classification':'disputed','published':True,'second_source_locator':'RGPH/legacy commune universe requires legal reconciliation','lexical_context':None}]);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MR','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':DGAT,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MR','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':DGAT,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('WILAYAS','mr_wilaya',15),('NOUAKCHOTT-WILAYAS','mr_wilaya_nouakchott_profile',3),('REGIONAL-WILAYAS','mr_wilaya_regional_profile',12)];ds=[d('DEN-MR-'+a,l,n,f'Exact {l} denominator.') for a,l,n in specs];vs=[v('COV-MR-'+a,l,'DEN-MR-'+a,n,f'{n}/{n} matched.') for a,l,n in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='MR' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='MR' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Mauritania 15-wilaya profile pilot','captured_at':DATE,'source_id':DGAT,'scope':'15 wilayas: three Nouakchott and twelve regional','method':'Checksum-bound DGAT/ANSADE reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'63 moughataas known/open; communes conflicted 219/220.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-MR-'),[snap])
 man=L(ROOT/'manifests/MR.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'DGAT / ANSADE','source_ids':[DGAT,RGPH,REV],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-MR-COUNTRY-SCOPE',*[f'COV-MR-{a}' for a,_,_ in specs]],'caveats':['Nouakchott wilayas are not inferred neighborhoods.','63 moughataas known but records deferred.','Commune denominator conflicted 219/220.'],'next_action':'Import 63 moughataas from current register; resolve commune count before commune entities.'})
 for x in man['hierarchy']:
  if x['entity_type']=='mr_wilaya':x.update({'source_ids':[DGAT,RGPH],'verification_status':'verified','authority_name':'DGAT / ANSADE','denominator':15,'denominator_id':'DEN-MR-WILAYAS','coverage_record_id':'COV-MR-WILAYAS','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'15 wilayas.','special_cases':['Three Nouakchott wilayas.']})
  elif x['entity_type']=='mr_moughataa':x.update({'verification_status':'pending','authority_name':'DGAT','denominator':63,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'open','notes':'Known count, records deferred.','special_cases':[]})
  elif x['entity_type']=='mr_commune':x.update({'verification_status':'pending','authority_name':'DGAT / ANSADE','denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'open','notes':'Conflicted 219/220.','special_cases':['No denominator until legal reconciliation.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['mr_wilaya'],'local_names':['wilaya'],'authority_name':'DGAT','denominator':n,'denominator_id':'DEN-MR-'+a,'coverage_record_id':'COV-MR-'+a,'snapshot_date':DATE,'source_ids':[DGAT,RGPH],'license':LIC,'scope_status':'closed','notes':'Profile layer.','special_cases':[]} for a,l,n in specs];write_json(ROOT/'manifests/MR.yml',man);write_json(ROOT/'data/cultural/mauritania_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'MR','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_micro_pilot'},'dialect':{'status':'not_documented_in_cycle','claims':0}}});print(json.dumps({'entities':15,'relationships':15,'claims':17,'sources':3}))
if __name__=='__main__':main()
