#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/comoros';F=I/'fixtures/current_hierarchy_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-KM-PRODUCTION-20260817';LAW='SRC-KM-LAW-11-006-AU-2011';INS='SRC-KM-INSEED-RGPH17-ADMIN';WHC='SRC-UNESCO-WHC-KM-1768-2026';LIC='Official Comoros public/statistical material; factual extraction with attribution; reuse terms not stated';WL='CC BY-SA 3.0 IGO for UNESCO descriptions'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,lic=LIC,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':lic,'language':'fr','country_codes':['KM'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['islands'])==3 and sum(len(i['prefectures']) for i in f['islands'])==16 and sum(len(p['communes']) for i in f['islands'] for p in i['prefectures'])==54 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(LAW,'Loi 11-006/AU — organisation territoriale','Ministère de la Justice, Union des Comores','law',f['sources']['law'],'three islands, sixteen prefectures, commune enumeration','Legal current administration; Mayotte excluded.',pub='2011-05-02'),src(INS,'INSEED administrative population table — RGPH 2017','INSEED Comores','census',f['sources']['inseed'],'population by island, prefecture and 54 communes','Record-level census cross-check.'),src(WHC,'The Medinas of the Historic Sultanates of the Comoros','UNESCO World Heritage Committee','institutional_page',f['sources']['unesco'],'Decision 48 COM 8B.13; property 1768; six serial components','2026 inscription; older zero-property page superseded.',WL,pub='2026-07-29')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'KM','sources':S});E=[];R=[];C=[]
 def ent(i,n,t,s,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KM','canonical_name':n,'canonical_name_language':'fr','entity_type':t,'status':'current','valid_from':None,'valid_to':None,'canonical_source_id':s,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'verified','confidence':'high'}
 def rel(ch,pa,s,loc,kind='administrative_parent'):return {'id':record_id('REL-KM',ch,pa),'schema_version':SCHEMA_VERSION,'child_id':ch,'parent_id':pa,'relationship_type':kind,'status':'current','valid_from':None,'valid_to':None,'source_id':s,'source_locator':loc,'notes':'Current Union-administered topology only.','verification_status':'verified','confidence':'high'}
 for island in f['islands']:
  iid='ENT-KM-ISLAND-'+island['token'];loc=f"Law 11-006/AU island {island['name']}; {len(island['prefectures'])} prefectures";E.append(ent(iid,island['name'],'km_island',LAW,loc,'Autonomous island administered by Union; Mayotte not included.'));R.append(rel(iid,'ENT-KM-COUNTRY',LAW,loc));prefcount=len(island['prefectures']);commcount=sum(len(p['communes']) for p in island['prefectures']);C.append({'id':record_id('CLM-KM','admin-count',iid),'schema_version':SCHEMA_VERSION,'subject_id':iid,'predicate':'administrative_child_counts','value':{'type':'json','data':{'prefectures':prefcount,'communes':commcount}},'unit':'administrative_unit','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':LAW,'second_source_id':INS,'source_locator':loc,'sensitivity':'ordinary','notes':None,'verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'INSEED census table','lexical_context':None})
  for p in island['prefectures']:
   pid='ENT-KM-PREFECTURE-'+p['token'];pl=f"Law prefecture {p['name']} under {island['name']}";E.append(ent(pid,p['name'],'km_prefecture',LAW,pl,'Administrative prefecture, not autonomous island/commune.'));R.append(rel(pid,iid,LAW,pl))
   for q in p['communes']:
    cid='ENT-KM-COMMUNE-'+q['token'];cl=f"Law/INSEED commune {q['name']} under {p['name']}";E.append(ent(cid,q['name'],'km_commune',LAW,cl,'Legal commune; village components not emitted.'));R.append(rel(cid,pid,LAW,cl))
 w=f['world_heritage'];wid=w['entity_id'];loc=f"UNESCO property {w['reference']}; inscribed {w['inscription_year']}; {w['serial_components']} components";E.append(ent(wid,w['name'],'cultural_site',WHC,loc,'One serial World Heritage property; components not separate entities.'));R.append(rel(wid,'ENT-KM-COUNTRY',WHC,loc,'associated_with'))
 for pred,val,typ in [('world_heritage_inscription_year',2026,'integer'),('world_heritage_category','cultural','string'),('serial_component_count',6,'integer')]:C.append({'id':record_id('CLM-KM',pred,wid),'schema_version':SCHEMA_VERSION,'subject_id':wid,'predicate':pred,'value':{'type':typ,'data':val},'unit':'year' if pred.endswith('year') else None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':WHC,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':None,'verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-KM-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='KM' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-KM-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-KM-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KM','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':s,'source_locator':note,'license':lic,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KM','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':lic,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('ISLANDS','km_island',3,LAW,LIC),('PREFECTURES','km_prefecture',16,LAW,LIC),('COMMUNES','km_commune',54,LAW,LIC),('WHC','world_heritage_property',1,WHC,WL)];ds=[d('DEN-KM-'+a,l,n,s,lic,f'Exact {l} denominator.') for a,l,n,s,lic in specs];vs=[v('COV-KM-'+a,l,'DEN-KM-'+a,n,s,lic,f'{n}/{n} matched.') for a,l,n,s,lic in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='KM' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='KM' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Comoros current Union hierarchy and 2026 World Heritage','captured_at':DATE,'source_id':LAW,'scope':'3 islands, 16 prefectures, 54 communes, one serial property','method':'Checksum-bound law/INSEED/UNESCO reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Mayotte excluded from current administration; claimed scope not modeled as current.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-KM-'),[snap])
 man=L(ROOT/'manifests/KM.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Ministry of Justice / INSEED','source_ids':[LAW,INS,WHC],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-KM-COUNTRY-SCOPE',*[f'COV-KM-{a}' for a,_,_,_,_ in specs]],'caveats':['Current Union administration covers three islands; Mayotte excluded.','Village components not communes.','UNESCO 2026 inscription supersedes older zero-property page.'],'next_action':'Maintain 3/16/54 current hierarchy and separate any claimed-territory representation.'})
 vals={l:(n,a) for a,l,n,_,_ in specs if l.startswith('km_')}
 for x in man['hierarchy']:
  if x['entity_type'] in vals:
   n,a=vals[x['entity_type']];x.update({'source_ids':[LAW,INS],'verification_status':'verified','authority_name':'Justice / INSEED','denominator':n,'denominator_id':'DEN-KM-'+a,'coverage_record_id':'COV-KM-'+a,'snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Current Union-administered scope.','special_cases':['Mayotte excluded.']})
 man['pilot_layers']=[{'layer':l,'entity_types':[l],'local_names':['administrative unit'],'authority_name':'Justice / INSEED','denominator':n,'denominator_id':'DEN-KM-'+a,'coverage_record_id':'COV-KM-'+a,'snapshot_date':DATE,'source_ids':[s],'license':lic,'scope_status':'closed','notes':'Current scope.','special_cases':[]} for a,l,n,s,lic in specs];write_json(ROOT/'manifests/KM.yml',man);write_json(ROOT/'data/cultural/comoros_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'KM','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented','denominator':1,'claims':3},'dialect':{'status':'not_documented_in_cycle','claims':0}}});print(json.dumps({'entities':74,'relationships':74,'claims':6,'sources':3}))
if __name__=='__main__':main()
