#!/usr/bin/env python3
import hashlib,json
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/somalia';F=I/'fixtures/federal_frames_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-SO-PRODUCTION-20260817';MOP='SRC-SO-MOP-FMS-2026';MOI='SRC-SO-MOIFAR-NORTHEAST-2026';SONNA='SRC-SO-SONNA-NORTHEAST-DECLARATION-2026';SEN='SRC-SO-SENATE-CONSTITUENCY';OLD='SRC-SO-MPWR-FIVE-FMS-2025';LIC='Official Somalia federal material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,typ,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':typ,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'en','country_codes':['SO'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);assert len(f['federal_member_states'])==7 and len(f['parallel_units'])==1 and hashlib.sha256(F.read_bytes()).hexdigest()==m['records'][0]['sha256']
 S=[src(MOP,'Federal Member States','Federal Government of Somalia, Ministry of Planning','official_register',f['sources']['mop'],'Seven named FMS plus Banadir Regional Administration','Authority-specific current federal planning frame; not a sovereignty or control adjudication.'),src(MOI,'Formal establishment of North Eastern State','Ministry of Interior, Federal Affairs and Reconciliation','official_report',f['sources']['moifar_ne'],'17 January 2026 inauguration and completion of formation','Records formal establishment of the new federal member state.',pub='2026-01-17'),src(SONNA,'President declares North East State a full Federal Member State','Somali National News Agency','official_report',f['sources']['sonna_ne'],'Presidential statement, 17 January 2026','Full-member declaration and equal federal status.',pub='2026-01-17'),src(SEN,'Senate constituency','Upper House of the Federal Parliament of Somalia','official_register',f['sources']['senate'],'Somaliland, Puntland, Jubaland, South West, Galmudug, Hirshabelle representation','Supports the FGS constitutional/representation narrative; does not resolve Somaliland de facto or sovereign status.'),src(OLD,'2025 project assessment: five Federal Member States','Federal Ministry of Public Works','official_report',f['sources']['older_five'],'Five FMS enumeration before North East completion; Somaliland treated separately','Temporal baseline for five standard operational FMS.',pub='2025-04-01')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'SO','sources':S});E=[];R=[];C=[]
 for q in f['federal_member_states']:
  eid='ENT-SO-FMS-'+q['code'];is_sl=q['profile']=='fgs_federal_planning_narrative';status='claimed' if is_sl else 'current';sid=SONNA if q['profile']=='new_fms' else MOP;loc=f"Ministry of Planning FMS entry: {q['name']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'SO','canonical_name':q['name'],'canonical_name_language':'en','entity_type':'so_federal_member_state','status':status,'valid_from':q['valid_from'],'valid_to':None,'canonical_source_id':sid,'source_locator':loc if sid==MOP else 'Presidential full-member declaration, 17 January 2026','legacy_ids':[],'coordinates':None,'notes':'Authority-specific FGS federal identity. This record does not adjudicate sovereignty, territorial claims, or effective control.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-SO',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-SO-COUNTRY','relationship_type':'administrative_parent','status':status,'valid_from':q['valid_from'],'valid_to':None,'source_id':sid,'source_locator':loc,'notes':'FGS federal/planning relationship only; no territorial-control inference.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-SO','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'federal_planning_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':q['valid_from'],'valid_to':None,'source_id':MOP if q['profile']!='new_fms' else MOI,'second_source_id':SEN if is_sl else (SONNA if q['profile']=='new_fms' else OLD),'source_locator':loc,'sensitivity':'sensitive' if is_sl or q['profile']=='new_fms' else 'ordinary','notes':'Classification is attributed to the cited FGS frame; competing claims/control remain separate.','verification_status':'verified','confidence':'high','classification':'disputed' if is_sl else 'official','published':True,'second_source_locator':'Senate representation narrative' if is_sl else ('Presidential declaration' if q['profile']=='new_fms' else 'Five-FMS 2025 baseline'),'lexical_context':None})
 b=f['parallel_units'][0];be='ENT-SO-REGION-BRA';E.append({'id':be,'schema_version':SCHEMA_VERSION,'country_code':'SO','canonical_name':b['name'],'canonical_name_language':'en','entity_type':'so_region','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':MOP,'source_locator':'Banadir Regional Administration listed separately after seven FMS','legacy_ids':[],'coordinates':None,'notes':'Parallel federal-capital regional administration; not silently promoted to FMS.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-SO',be,'country'),'schema_version':SCHEMA_VERSION,'child_id':be,'parent_id':'ENT-SO-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':MOP,'source_locator':'Banadir Regional Administration separate entry','notes':'Parallel regional-administration path.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-SO','profile',be),'schema_version':SCHEMA_VERSION,'subject_id':be,'predicate':'federal_planning_profile','value':{'type':'string','data':'banadir_regional_administration'},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':MOP,'second_source_id':None,'source_locator':'Banadir Regional Administration listed separately from seven FMS','sensitivity':'ordinary','notes':'Distinct type/path, not an FMS alias.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 ne='ENT-SO-FMS-07';C.append({'id':record_id('CLM-SO','northeast-transition'),'schema_version':SCHEMA_VERSION,'subject_id':ne,'predicate':'federal_member_transition','value':{'type':'json','data':{'constitution_adopted':'2025-07-30','parliament_formed':'2025-08-17','leadership_elected':'2025-08-30','full_member_declaration':'2026-01-17','predecessor_name':'SSC-Khaatumo'}},'unit':None,'status':'verified','observed_at':'2026-01-17','valid_from':'2025-07-30','valid_to':None,'source_id':MOI,'second_source_id':SONNA,'source_locator':'State formation completion and inauguration, 17 January 2026','sensitivity':'sensitive','notes':'SSC-Khaatumo is transition provenance, not a duplicate current entity.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'Presidential full-member declaration','lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-SO-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='SO' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-SO-') and r.get('entity_id')!='ENT-SO-COUNTRY',[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-SO-') and r.get('child_id')!='ENT-SO-COUNTRY',R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,note,status='official',missing=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SO','layer':l,'definition':note,'value':n,'as_of':DATE,'status':status,'source_id':s,'source_locator':note,'license':LIC,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,matched,s,note,complete,missing=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SO','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':matched,'unmatched':0 if n is None else n-matched,'excluded':0,'missing':None if n is None else n-matched,'complete':complete,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':None if n is None else round(matched*100/n,2),'exclusion_reasons':[]}
 specs=[('MOP-FMS','so_federal_member_state_mop_frame',7,7,MOP,'Seven FMS in current Ministry of Planning frame.'),('STANDARD-FIVE','so_federal_member_state_standard_five',5,5,OLD,'Five standard operational FMS in 2025 baseline.'),('SOMALILAND-NARRATIVE','so_fms_somaliland_fgs_narrative',1,1,SEN,'FGS planning/Senate narrative only.'),('NORTHEAST','so_fms_north_east_current',1,1,SONNA,'North East full member from 2026-01-17.'),('BANADIR','so_banadir_regional_administration',1,1,MOP,'Banadir parallel regional administration.')];ds=[d('DEN-SO-'+a,l,n,s,note) for a,l,n,_,s,note in specs];vs=[v('COV-SO-'+a,l,'DEN-SO-'+a,n,mt,s,note,True) for a,l,n,mt,s,note in specs]
 for a,l in [('REGIONS','so_region_record_universe'),('DISTRICTS','so_district_record_universe')]:
  reason='No authority-reconciled national denominator is accepted across overlapping federal, Somaliland, Puntland, North East, and Banadir structures.';ds.append(d('DEN-SO-'+a,l,None,MOP,l,'unavailable',reason));vs.append(v('COV-SO-'+a,l,'DEN-SO-'+a,None,0,MOP,l,False,reason))
 rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='SO' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='SO' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Somalia authority-specific federal planning frames','captured_at':DATE,'source_id':MOP,'scope':'Seven MOP FMS, one parallel Banadir administration, five-FMS baseline, Somaliland and North East narratives','method':'Checksum-bound authority/date-specific reconciliation; no territorial union or control map.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Region/district denominators and territorial/effective-control overlays unavailable.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-SO-PRODUCTION-'),[snap])
 man=L(ROOT/'manifests/SO.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Federal Ministries of Planning and Interior / SONNA / Upper House','source_ids':[MOP,MOI,SONNA,SEN,OLD],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-SO-COUNTRY-SCOPE',*[x['id'] for x in vs]],'caveats':['Seven-FMS denominator is explicitly the current Ministry of Planning frame, not a neutral sovereignty/control adjudication.','Banadir is a parallel regional administration.','Somaliland and North East records preserve FGS-attributed narratives; overlapping claims/control are not inferred.'],'next_action':'Maintain authority-specific federal frames; add regions/districts or claim/control overlays only after multi-authority reconciliation.'})
 for x in man['hierarchy']:
  if x['entity_type']=='so_federal_member_state':x.update({'source_ids':[MOP,MOI,SONNA,SEN,OLD],'verification_status':'verified','authority_name':'FGS authority-specific frame','denominator':7,'denominator_id':'DEN-SO-MOP-FMS','coverage_record_id':'COV-SO-MOP-FMS','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Seven entries in MOP frame; narrative-specific.','special_cases':['Somaliland claimed/FGS narrative; North East full-member transition 2026-01-17.']})
  elif x['entity_type']=='so_region':x.update({'source_ids':[MOP],'verification_status':'pending','authority_name':'Multiple authorities','denominator':None,'denominator_id':'DEN-SO-REGIONS','coverage_record_id':'COV-SO-REGIONS','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'Only Banadir parallel administration emitted; national region universe unreconciled.','special_cases':['Banadir is not an FMS.']})
  elif x['entity_type']=='so_district':x.update({'source_ids':[MOP],'verification_status':'pending','authority_name':'Multiple authorities','denominator':None,'denominator_id':'DEN-SO-DISTRICTS','coverage_record_id':'COV-SO-DISTRICTS','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'National district universe unreconciled.','special_cases':['No control-based parent inference.']})
 man['pilot_layers']=[{'layer':'so_federal_member_state_mop_frame','entity_types':['so_federal_member_state'],'local_names':['Federal Member State'],'authority_name':'Ministry of Planning','denominator':7,'denominator_id':'DEN-SO-MOP-FMS','coverage_record_id':'COV-SO-MOP-FMS','snapshot_date':DATE,'source_ids':[MOP],'license':LIC,'scope_status':'closed','notes':'Authority-specific frame.','special_cases':['Somaliland and North East require narrative context.']},{'layer':'so_banadir_regional_administration','entity_types':['so_region'],'local_names':['Regional Administration'],'authority_name':'Ministry of Planning','denominator':1,'denominator_id':'DEN-SO-BANADIR','coverage_record_id':'COV-SO-BANADIR','snapshot_date':DATE,'source_ids':[MOP],'license':LIC,'scope_status':'closed','notes':'Parallel unit.','special_cases':[]}];write_json(ROOT/'manifests/SO.yml',man);write_json(ROOT/'data/cultural/somalia_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'SO','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_full_pilot_stage1'},'dialect':{'status':'not_documented_in_cycle','claims':0},'territorial_control':{'status':'requires_separate_dated_overlay'}}});print(json.dumps({'entities':8,'relationships':8,'claims':9,'sources':5,'denominators':7,'coverage':7}))
if __name__=='__main__':main()
