#!/usr/bin/env python3
import hashlib,json
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/sudan';F=I/'fixtures/states_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-SD-PRODUCTION-20260817';PRES='SRC-SD-PRESIDENCY-STATES-CATALOGUE';EMB='SRC-SD-EMBASSY-QATAR-18-STATES';CBS='SRC-SD-CBS-AUTHORITY';LIC='Official Sudan government material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,typ,u,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':typ,'url':u,'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['SD'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+' Publication date unavailable.'}
def main():
 f=L(F);m=L(M);assert len(f['states'])==18 and hashlib.sha256(F.read_bytes()).hexdigest()==m['records'][0]['sha256']
 S=[src(PRES,'About the States — 18-state catalogue','Presidency of the Republic of Sudan','official_register',f['sources']['presidency'],'Indexed catalogue entries numbered 1–18','Exact official state enumeration; page currently returns 404, so retrieval limitation is explicit.'),src(EMB,'About Sudan — system of government','Embassy of Sudan in Qatar','official_report',f['sources']['embassy'],'Government system section: Sudan has 18 states','Live government count confirmation.'),src(CBS,'Central Bureau of Statistics','Central Bureau of Statistics Sudan','institutional_page',f['sources']['cbs'],'Official statistical authority and States navigation','Authority context; not used as a control map.')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'SD','sources':S});E=[];R=[];C=[]
 for q in f['states']:
  eid='ENT-SD-STATE-'+q['code'];loc=f"Presidency catalogue entry {q['code']}: {q['name_ar']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'SD','canonical_name':q['name_ar'],'canonical_name_language':'ar','entity_type':'sd_state','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':PRES,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Current legal state identity only; no effective-control, operation, destruction, displacement, access, or dispute inference.','verification_status':'verified','confidence':'medium'});R.append({'id':record_id('REL-SD',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-SD-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':PRES,'source_locator':loc,'notes':'Legal parent only; not a control relation.','verification_status':'verified','confidence':'medium'});C.append({'id':record_id('CLM-SD','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':'legal_state'},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':PRES,'second_source_id':EMB,'source_locator':loc,'sensitivity':'ordinary','notes':'Legal state profile; physical and operational status are separate overlays.','verification_status':'verified','confidence':'medium','classification':'official','published':True,'second_source_locator':'Government embassy: Sudan has 18 states','lexical_context':None})
 C.append({'id':record_id('CLM-SD','denominator-reconciliation'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-SD-COUNTRY','predicate':'administrative_denominator_reconciliation','value':{'type':'json','data':{'accepted_current':18,'stale_rejected':17,'reason':'exact Presidency catalogue and government embassy confirmation'}},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':PRES,'second_source_id':EMB,'source_locator':'Catalogue entries 1–18','sensitivity':'ordinary','notes':'Does not encode effective control.','verification_status':'verified','confidence':'medium','classification':'official','published':True,'second_source_locator':'Government system section','lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-SD-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='SD' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-SD-') and r.get('entity_id')!='ENT-SD-COUNTRY',[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-SD-') and r.get('child_id')!='ENT-SD-COUNTRY',R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def den(i,l,n,status,note,missing=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SD','layer':l,'definition':note,'value':n,'as_of':DATE,'status':status,'source_id':PRES,'source_locator':note,'license':LIC,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE}
 def cov(i,l,did,n,matched,complete,note,missing=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SD','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':PRES,'matched':matched,'unmatched':0 if n is None else n-matched,'excluded':0,'missing':None if n is None else n-matched,'complete':complete,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':None if n is None else matched*100/n,'exclusion_reasons':[]}
 ds=[den('DEN-SD-STATES','sd_state',18,'official','Exact current legal state catalogue.')];vs=[cov('COV-SD-STATES','sd_state','DEN-SD-STATES',18,18,True,'18/18 legal states.')]
 for a,l in [('LOCALITIES','sd_locality'),('ADMIN-UNITS','sd_administrative_unit')]:
  reason='No current authority-reconciled national denominator and record register was accepted during this cycle.';ds.append(den('DEN-SD-'+a,l,None,'unavailable',l,reason));vs.append(cov('COV-SD-'+a,l,'DEN-SD-'+a,None,0,False,l,reason))
 rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='SD' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='SD' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Sudan 18 legal states','captured_at':DATE,'source_id':PRES,'scope':'18 legal state identities; localities and war-time overlays unavailable','method':'Checksum-bound reconciliation of exact Presidency catalogue and government 18-state confirmation; stale 17-state pages rejected.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Abyei, control, operation, destruction, displacement, and access require separate dated narratives.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-SD-PRODUCTION-'),[snap])
 man=L(ROOT/'manifests/SD.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Presidency / Central Bureau of Statistics / Government Embassy','source_ids':[PRES,EMB,CBS],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-SD-COUNTRY-SCOPE','COV-SD-STATES','COV-SD-LOCALITIES','COV-SD-ADMIN-UNITS'],'caveats':['18 legal states closed; stale 17-state pages rejected.','Presidency page currently returns 404; exact indexed catalogue and live government count are retained with medium confidence.','Abyei and war-time control/operation/displacement/destruction require separate dated overlays.'],'next_action':'Maintain 18 legal states; add lower or war-time layers only from authority-reconciled dated evidence.'})
 for x in man['hierarchy']:
  if x['entity_type']=='sd_state':x.update({'source_ids':[PRES,EMB,CBS],'verification_status':'verified','authority_name':'Presidency / CBS','denominator':18,'denominator_id':'DEN-SD-STATES','coverage_record_id':'COV-SD-STATES','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'18 legal states.','special_cases':['Abyei not inserted as ordinary state.']})
  elif x['entity_type']=='sd_locality':x.update({'source_ids':[PRES],'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':'DEN-SD-LOCALITIES','coverage_record_id':'COV-SD-LOCALITIES','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'Current national register unreconciled.','special_cases':[]})
  elif x['entity_type']=='sd_administrative_unit':x.update({'source_ids':[PRES],'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':'DEN-SD-ADMIN-UNITS','coverage_record_id':'COV-SD-ADMIN-UNITS','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'Current national register unreconciled.','special_cases':[]})
 man['pilot_layers']=[{'layer':'sd_state','entity_types':['sd_state'],'local_names':['ولاية'],'authority_name':'Presidency / CBS','denominator':18,'denominator_id':'DEN-SD-STATES','coverage_record_id':'COV-SD-STATES','snapshot_date':DATE,'source_ids':[PRES,EMB],'license':LIC,'scope_status':'closed','notes':'Legal frame only.','special_cases':['No control inference.']}];write_json(ROOT/'manifests/SD.yml',man);write_json(ROOT/'data/cultural/sudan_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'SD','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_full_pilot_stage1'},'dialect':{'status':'not_documented_in_cycle','claims':0},'war_time_status':{'status':'requires_separate_dated_overlay'}}});print(json.dumps({'entities':18,'relationships':18,'claims':19,'sources':3,'denominators':3,'coverage':3}))
if __name__=='__main__':main()
