#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/djibouti';F=I/'fixtures/topology_2024.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';ASOF='2024-05-20';SNAP='SNP-DJ-PRODUCTION-20260816';LIC='Official Djibouti public material; factual extraction with attribution; reuse terms not stated'
SREG='SRC-DJ-PRESIDENCY-REGIONS-2026';SLAW='SRC-DJ-LAW-122-CITY-2005';SCEN='SRC-DJ-INSTAD-RGPH3-2024';SSUB='SRC-DJ-DECENTRALISATION-ROADMAP-2020';SINT='SRC-DJ-INTERIOR-PREFECTURES-2026'
D=I/'fixtures/cultural_depth_2026.json';DDATE='2026-09-21'
DS={'state':'SRC-UNESCO-ICH-DJ-STATE-2026','zaffa':'SRC-UNESCO-ICH-ZAFFA-02283-2025','xeer':'SRC-UNESCO-ICH-XEER-CIISE-02087-2024','xeedho':'SRC-UNESCO-ICH-XEEDHO-02001-2023','constitution':'SRC-DJ-CONSTITUTION-2010','iso_aar':'SRC-DJ-ISO639-3-AFAR','iso_som':'SRC-DJ-ISO639-3-SOMALI','cuisine':'SRC-DJ-CUISINE-MIRROR-2026','languages':'SRC-DJ-LANGUAGES-MIRROR-2026','city':'SRC-DJ-CITY-MIRROR-2026','quartiers_guide':'SRC-DJ-QUARTIERS-GUIDE-2026','city_history':'SRC-DJ-CITY-HISTORY-2026','sign':'SRC-DJ-SIGN-LANGUAGES-2021','wedding_press':'SRC-DJ-WEDDING-ALJAZIRAH-1999'}
ILOC='UNESCO ICH element and State page; factual extraction with attribution; CC BY-SA 3.0 IGO for the descriptions'
WLOC='Mirror, guide and press material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'fr','country_codes':['DJ'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}

def dsrc(i,t,pu,ty,u,loc,note,tier='E',lang='ar',lic=WLOC,pub=None):
 return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':pu,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DDATE,'license':lic,'language':lang,'country_codes':['DJ'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(D.read_bytes()).hexdigest(),'quality_tier':tier,'notes':note+('' if pub else ' Publication date unavailable.')}
def depth_sources():
 return [dsrc(DS['state'],'Djibouti — UNESCO Intangible Cultural Heritage','UNESCO Intangible Cultural Heritage','institutional_page','https://ich.unesco.org/en/state/djibouti-DJ','three inscribed elements (2023 USL, 2024 RL, 2025 RL); 2026 Madqa nomination pending; Convention ratified 30 August 2007','State page read 2026-09-21: element list, lists, years, ratification date and the pending 2026 nomination for the Madqa (Afar oral customary law). Publication date unavailable on the state page.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['zaffa'],'The zaffa in the traditional wedding','UNESCO Intangible Cultural Heritage','institutional_page','https://ich.unesco.org/en/RL/the-zaffa-in-the-traditional-wedding-02283','element 02283; inscribed 2025 (20.COM) on the Representative List; seven submitting States','Element page read 2026-09-20 in the Comoros cycle and reused here: Djibouti is one of the seven submitting States, so no exclusivity is claimed.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['xeer'],'Xeer Ciise: Oral customary laws of Somali-Issa communities in Ethiopia, Djibouti and Somalia','UNESCO Intangible Cultural Heritage','institutional_page','https://ich.unesco.org/en/RL/xeer-ciise-oral-customary-laws-of-somali-issa-communities-in-ethiopia-djibouti-and-somalia-02087','element 02087; inscribed 2024 (19.COM) on the Representative List; Ethiopia, Djibouti and Somalia','Element page read 2026-09-21: three components (political constitution, penal code, code of social conduct) and three submitting States.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['xeedho'],'Xeedho','UNESCO Intangible Cultural Heritage','institutional_page','https://ich.unesco.org/en/USL/xeedho-02001','element 02001; inscribed 2023 (18.COM) on the List of Intangible Cultural Heritage in Need of Urgent Safeguarding; Djibouti is the only submitting State','Element page read 2026-09-21: full description of the dish, its container, its decoration and its transmission inside families.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['constitution'],'Djibouti 1992 (rev. 2010) Constitution (as published by Constitute)','Constitute Project — Comparative Constitutions Project','law','https://www.constituteproject.org/constitution/Djibouti_2010','Article 1 official languages, state religion and motto; Article 2 capital and flag','Constitutional text as published by the Constitute Project. The page carries no publication date and the promulgation date is not asserted here. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_aar'],'ISO 639-3 code registration — Afar','SIL International (ISO 639-3 registration authority)','standard','https://iso639-3.sil.org/code/aar','aar Afar; 639-2/639-3; 639-1 equivalent aa; individual, living','Registration-authority entry read 2026-09-21. The registry page carries no publication date. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso_som'],'ISO 639-3 code registration — Somali','SIL International (ISO 639-3 registration authority)','standard','https://iso639-3.sil.org/code/som','som Somali; 639-2/639-3; 639-1 equivalent so; individual, living','Registration-authority entry read 2026-09-21. The registry page carries no publication date. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['cuisine'],'مطبخ جيبوتي','ويكيبيديا العربية (نسخة مرآة)','local_website','https://ar.wikipedia.org/wiki/مطبخ_جيبوتي','مزيج صومالي/عفاري/يمني/فرنسي؛ لاهوه؛ الفه فاه؛ ييتاكلت الرطب؛ الحلاوة الطحينية؛ السمبوسة؛ تيبس الإبل؛ الباري؛ الباستو','مرآة عربية تصف المطبخ الجيبوتي وأصوله وأطباقه؛ تُستعمل غير منشورة.',lang='ar'),
 dsrc(DS['languages'],'Languages of Djibouti','Wikipedia (English mirror)','local_website','https://en.wikipedia.org/wiki/Languages_of_Djibouti','official Arabic/French; indigenous Afar/Somali; Northern Somali main dialect; ta\'izzi-adeni and Omani Arabic, Amharic, Oromo, Greek, Hindi; Somali Sign Language; Latin and Arabic scripts; Qafar Feera; Regional Somali Language Academy 2013','Mirror page used for the language inventory, the scripts and the language academy. It also prints speaker counts, which this cycle does not record.',tier='E',lang='en'),
 dsrc(DS['city'],'Djibouti City','Wikipedia (English mirror)','local_website','https://en.wikipedia.org/wiki/Djibouti_City','three communes Ras-Dika/Boulaos/Balbala; 35 sub-prefectures row; founded 1888; old section of souks; Place of 27 June; Théâtre des Salines 1965','Mirror page used only for the city-context cross-check and the count discrepancy note; not for any denominator.',tier='E',lang='en'),
 dsrc(DS['quartiers_guide'],'Découverte de Djibouti : Quartiers','Petit Futé (local guide)','local_website','https://www.petitfute.com/v51482-djibouti/decouvrir/d2014-quartiers/','quartier européen and quartier africain; place du 27-Juin; marché central and souk; place Mahmoud Harbi; rue des Afars; cités Engueila and Arhiba; Marabout; Héron; Haramous; Boulaos','Travel guide describing the central quarters; used only for the unpublished places layer.',lang='fr'),
 dsrc(DS['city_history'],'La Ville de Djibouti','Page historique locale (lutin84.chez.com)','local_website','http://lutin84.chez.com/pages/djibouti/textedjib/djibouti.html','quartiers 1-7 and Gachamaleh/7bis/Gabode; Einguéla and Arrhiba meanings; Boulaos name; Ambouli; Balbala; place Mahmoud Harbi; rue des Mouches; sha with clove and cardamom; diri and gogara Thursday market; basketry, charcharis, fooh/jaawi/maskati','Local historical page on Djibouti City: quarter names, trade and dress details used in the classified body.',lang='fr'),
 dsrc(DS['sign'],'Djibouti — African Sign Languages Resource Center','African Sign Languages Resource Center','local_website','https://africansignlanguagesresourcecenter.com/dijbouti/','Djibouti Sign Language (DSC); Somali Sign Language; French and Standard Arabic as official languages','Sign-language reference page; used only to record that a sign language is reported for Djibouti, without any ISO code or count.',tier='E',lang='en'),
 dsrc(DS['wedding_press'],'عادات وتقاليد الشعوب في ليلة الزفاف .. في جيبوتي','جريدة الجزيرة','local_press','https://www.al-jazirah.com/1999/19990604/wn1.htm','احتفالات سبعة أيام؛ الجدائل؛ فتح الوعاء المعقود بالعصا؛ برد الأسنان بالمبرد الحديدي','Press report dated 1999: used for one dated local narrative and one folk narrative, both unpublished.',tier='B',pub='1999-06-04')]
def depth_items(dd):
 E2=[];R2=[];C2=[];CITY='ENT-DJ-DJIBOUTI-CITY'
 def clm(key,sub,pred,val,src,loc,cls,note,vs='local_reported',conf='low',st='reported',pub=False,second=None,second_loc=None,unit=None,typ='json',obs=DDATE):
  return {'id':record_id('CLM-DJ-DEPTH',key),'schema_version':SCHEMA_VERSION,'subject_id':sub,'predicate':pred,'value':{'type':typ,'data':val},'unit':unit,'status':st,'observed_at':obs,'valid_from':None,'valid_to':None,'source_id':src,'second_source_id':second,'source_locator':loc,'second_source_locator':second_loc,'sensitivity':'ordinary','notes':note,'verification_status':vs,'confidence':conf,'classification':cls,'published':pub,'lexical_context':None}
 def place(x,kind):
  iid=f'ENT-DJ-{kind.upper()}-'+x['token'];src=DS[x['source']];loc=f"مكان بلا مقام: {x['name']} ({x['latin']}) داخل مدينة جيبوتي"
  E2.append({'id':iid,'schema_version':SCHEMA_VERSION,'country_code':'DJ','canonical_name':x['name'],'canonical_name_language':'ar','entity_type':kind,'status':'historical','valid_from':None,'valid_to':None,'canonical_source_id':src,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':loc+' — '+x['note'],'verification_status':'local_reported','confidence':'low'})
  R2.append({'id':record_id('REL-DJ-LOCATED',iid,CITY),'schema_version':SCHEMA_VERSION,'child_id':iid,'parent_id':CITY,'relationship_type':'located_in','status':'historical','valid_from':None,'valid_to':None,'source_id':src,'source_locator':loc,'notes':'علاقة مكانية بالمدينة فقط: لا يُستنتج أب إداري أدنى ولا قسم من الأقسام الثلاثة، ولا يُسجَّل سكان ولا نسبة.','verification_status':'local_reported','confidence':'low'})
 for x in dd['places']['quarters']:place(x,'quarter')
 for x in dd['places']['markets']:place(x,'market')
 for e in dd['ich_elements']:
  C2.append(clm('ich|'+e['reference'],'ENT-DJ-COUNTRY','intangible_cultural_practice',{'name':e['name'],'official_title':e['official_title'],'official_title_ar':e['official_title_ar'],'reference':e['reference'],'year':e['year'],'list':e['list'],'url':e['url'],'co_states':e['co_states'],'description':e['description']},DS[{'02283':'zaffa','02087':'xeer','02001':'xeedho'}[e['reference']]],f"قائمة اليونسكو للتراث الثقافي غير المادي: {e['official_title']} ({e['year']}, ref {e['reference']})",e['classification'],'عنصر مُدرج في قوائم اليونسكو؛ يُنشر بوصفه عنصرًا رسميًا، مع تصنيف صريح: مشترك لملف متعدد الدول أو وطني لعنصر بدولة مُدرِجة واحدة.',vs='verified',conf='high',st='verified',pub=True))
 C2.append(clm('state|ratification','ENT-DJ-COUNTRY','convention_ratification_date',{'convention':'اتفاقية صون التراث الثقافي غير المادي (2003)','date':'2007-08-30'},DS['state'],'صفحة الدولة: التصديق على الاتفاقية في 30 أغسطس 2007','official','تاريخ التصديق كما ورد في صفحة الدولة.',vs='verified',conf='high',st='verified',pub=True,typ='json'))
 C2.append(clm('state|madqa','ENT-DJ-COUNTRY','unesco_pending_nomination',{'element':'The Madqa, the Afar system of oral customary law','list':'القائمة التمثيلية','year':2026,'status':'قيد النظر'},DS['state'],'الترشيحات الجارية: 2026 — The Madqa, the Afar system of oral customary law (RL)','official','ترشيح معلن لعام 2026 على صفحة الدولة؛ ليس إدراجًا، ويُسجَّل بوصفه ترشيحًا قيد النظر لا عنصرًا مُدرجًا.',vs='verified',conf='high',st='verified',pub=True))
 for c in dd['constitution_provisions']:
  C2.append(clm(f"const|{c['article']}|{c['topic']}",'ENT-DJ-COUNTRY','constitutional_provision',{'article':c['article'],'topic':c['topic'],'summary':c['summary'],'note':c['note']},DS['constitution'],f"دستور 1992 (المعدَّل 2010)، المادة {c['article']} — {c['topic']}",'official','نصّ دستوري من مصدر من الفئة A؛ تُسجَّل الأحكام كما وردت ولا تُحوَّل إلى مقام إداري.',vs='verified',conf='high',st='verified',pub=True))
 for l in dd['language_presence']:
  off=bool(l['official']);sec=DS[l['second']] if l.get('second') else None
  C2.append(clm('lang|'+l['name'],'ENT-DJ-COUNTRY','language_presence',{'name':l['name'],'official':off,'level':l['level'],'iso_codes':l.get('codes',[]),'note':l['note']},DS[l['source']],f"حضور لغوي: {l['name']}",'official' if off else ('regional' if l['level'].startswith('national') else 'local'),('لغة رسمية بنصّ الدستور' if off else 'لغة غير رسمية من مرآة/مرجع محلي؛ لا يُسجَّل عدد متحدثين ولا نطاق إداري.'),vs='verified' if off else 'local_reported',conf='high' if off else 'low',st='verified' if off else 'reported',pub=off,second=sec,second_loc=('ISO 639-3 registry entry' if sec else None)))
 for p in dd['dialect_profiles']:
  C2.append(clm('dialect|'+p['variety'],'ENT-DJ-COUNTRY','dialect_profile',{'variety':p['variety'],'group':p['group'],'features':p['features']},DS[p['source']],f"لهجة: {p['variety']}",'regional','وصف لهجي مصنَّف؛ لا يُنسب إلى مقام ولا يُبنى عليه مقام.',second=DS[p['second']] if p.get('second') else None,second_loc=None))
 for p in dd['script_profiles']:
  C2.append(clm('script|'+p['name'],'ENT-DJ-COUNTRY','script_profile',{'name':p['name'],'features':p['features']},DS[p['source']],f"كتابة: {p['name']}",'regional','وصف كتابة مصنَّف من مرآة؛ لا يُنشر.'))
 for p in dd['language_institutions']:
  C2.append(clm('langinst|'+p['name'],'ENT-DJ-COUNTRY','language_institution',{'name':p['name'],'features':p['features']},DS[p['source']],f"مؤسسة لغوية: {p['name']}",'regional','مؤسسة مشتركة ثلاث دول ومقرها مدينة جيبوتي؛ تُسجَّل وصفًا لا مقامًا.'))
 for x in dd['dishes']:
  C2.append(clm('dish|'+x['name'],'ENT-DJ-COUNTRY','food_dish',{'name':x['name'],'description':x['desc']},DS[x['source']],f"طبق جيبوتي: {x['name']}",x['classification'],'معرفة طعام محلية مصنَّفة وغير منشورة.',second=DS[x['second']] if x.get('second') else None,second_loc=x.get('second_locator')))
 for x in dd['dress']:
  C2.append(clm('dress|'+x['name'],'ENT-DJ-COUNTRY','clothing_item',{'name':x['name'],'gender':x['gender'],'description':x['desc']},DS[x['source']],f"زي محلي: {x['name']}",x['classification'],'وصف لباس محلي مصنَّف وغير منشور.',second=DS[x['second']] if x.get('second') else None,second_loc=x.get('second_locator')))
 for x in dd['crafts']:
  C2.append(clm('craft|'+x['name'],'ENT-DJ-COUNTRY','craft_custom',{'name':x['name'],'description':x['desc']},DS[x['source']],f"حرفة محلية: {x['name']}",x['classification'],'حرفة ومعيشة محلية من مصدر محلي؛ تُعرض وصفًا لا إحصاءً.'))
 for x in dd['customs']:
  folk=bool(x.get('folk'))
  C2.append(clm('custom|'+x['name'],'ENT-DJ-COUNTRY','custom_practice',{'name':x['name'],'description':x['desc']},DS[x['source']],f"عرف محلي: {x['name']}",x['classification'],('رواية شعبية معلنة (folk narrative) من تقرير صحافي مؤرخ؛ لا تُؤكَّد ولا تُنشر.' if folk else 'عرف اجتماعي محلي مصنَّف وغير منشور؛ يُفصل عن عنصر اليونسكو ولا يُساوى به.'),vs='folk_narrative' if folk else 'local_reported',second=DS[x['second']] if x.get('second') else None,second_loc=x.get('second_locator')))
 for a in dd['administrative_notes']:
  C2.append(clm('admin|'+a['topic'],'ENT-DJ-DJIBOUTI-CITY','administrative_counts_discrepancy',{'topic':a['topic'],'mirror_value':a['mirror_value'],'accepted_value':a['accepted_value'],'summary':a['summary']},DS[a['source']],'مفارقة عددية معلنة بين مرآة ومجموعة الادعاء المقبولة','official','المجموعة المقبولة تبقى المرجع؛ تُسجَّل مفارقة المرآة صريحة ولا يُبنى عليها مقام ولا نسبة.',vs='local_reported',conf='low',st='reported',pub=False))
 return E2,R2,C2
def depth_layers():
 return [{'layer':'unesco_intangible_heritage','entity_types':['cultural_site'],'local_names':['عنصر تراث غير مادي'],'authority_name':'UNESCO Intangible Cultural Heritage','denominator':3,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['state'],DS['zaffa'],DS['xeer'],DS['xeedho']],'license':ILOC,'scope_status':'closed','notes':'ثلاثة عناصر مُدرجة لجيبوتي: عنصر وطني واحد على قائمة الصون العاجل (الخيدو 02001، 2023) وعنصران مشتركان (الزير عيسى 02087 بثلاث دول 2024، والزفّة 02283 بسبع دول 2025)، والترشيح العفاري (المدقة) قيد النظر 2026.','special_cases':['الملفات المشتركة تبقى shared ولا يُدَّعى فيها حصرية.','عنصر واحد بدولة مُدرِجة واحدة هو الوحيد الذي يجوز فيه classification = national.']},
 {'layer':'world_heritage_medinas','entity_types':['quarter','market'],'local_names':['مكان داخل العاصمة'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['quartiers_guide'],DS['city_history']],'license':WLOC,'scope_status':'open','notes':'اثنا عشر مكانًا داخل مدينة جيبوتي (عشرة أحياء وسوقان) بـlocated_in فقط: بلا أب إداري وبلا سكان وبلا نسبة.','special_cases':['لا يُستنتج قسم أدنى للأحياء من الأقسام الثلاثة.']},
 {'layer':'classified_local_knowledge','entity_types':['cultural_site'],'local_names':['معرفة محلية مصنَّفة'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['cuisine'],DS['languages'],DS['city_history'],DS['sign'],DS['wedding_press']],'license':WLOC,'scope_status':'open','notes':'معرفة محلية مصنَّفة وغير منشورة: ثمانية ملفات لغوية، ولهجة وكتابة ومؤسسة لغوية، واثنا عشر طبقًا، وثلاثة أزياء، وحرفتان، وثلاثة أعراف.','special_cases':['لا يُنشر أي ادعاء ضعيف المصدر ولا يُبنى عليه مقام.','لا تُسجَّل أرقام متحدثين ولا أعداد سكان.']}]

def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['regions'])==5 and sum(len(r['subprefectures']) for r in f['regions'])==13 and len(f['city']['communes'])==3 and hashlib.sha256(b).hexdigest()==next(r['sha256'] for r in m['records'] if r['path']=='data/imports/djibouti/fixtures/topology_2024.json')
 dd=L(D);assert hashlib.sha256(D.read_bytes()).hexdigest()==next(r['sha256'] for r in m['records'] if r['path']=='data/imports/djibouti/fixtures/cultural_depth_2026.json')
 assert (len(dd['ich_elements']),len(dd['constitution_provisions']),len(dd['language_presence']),len(dd['dialect_profiles']),len(dd['script_profiles']),len(dd['language_institutions']),len(dd['dishes']),len(dd['dress']),len(dd['crafts']),len(dd['customs']),len(dd['administrative_notes']))==(3,3,8,1,1,1,12,3,2,3,1)
 assert len(dd['places']['quarters'])==10 and len(dd['places']['markets'])==2
 S=[src(SREG,'Régions de la République de Djibouti','Présidence de la République','official_register',f['sources']['regions'],'five decentralized regions and special Djibouti City','Five regions explicitly separate from special-status city.'),src(SLAW,'Loi 122 — Statut de la Ville de Djibouti','Journal officiel / République de Djibouti','law',f['sources']['city_law'],'Article 2 three communes and special city status','Exact commune topology.',pub='2005-11-01'),src(SCEN,'RGPH-3 2024 provisional regional results','INSTAD','census',f['sources']['census'],'Table 1 population by six region/statistical scopes at 20 May 2024','Five regions plus Djibouti-Ville reconcile to national total.'),src(SSUB,'Feuille de route de la décentralisation','Ministère délégué chargé de la décentralisation','official_report',f['sources']['subprefectures'],'Table 3 regions and thirteen sub-prefectures','Sub-prefecture enumeration; not communes.'),src(SINT,'Administration territoriale — Préfectures','Ministère de l’Intérieur','official_register','https://interieur.gouv.dj/service/administration-territoriale-2/','Djibouti-Ville and five regional prefectures','Current state territorial-administration cross-check.')]+depth_sources()
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'DJ','sources':S});E=[];R=[];C=[]
 def ent(i,n,t,s,l,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DJ','canonical_name':n,'canonical_name_language':'fr','entity_type':t,'status':'current','valid_from':None,'valid_to':None,'canonical_source_id':s,'source_locator':l,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'source_verified','confidence':'high'}
 def rel(ch,pa,kind,s,l):return {'id':record_id('REL-DJ',ch,pa),'schema_version':SCHEMA_VERSION,'child_id':ch,'parent_id':pa,'relationship_type':kind,'status':'current','valid_from':None,'valid_to':None,'source_id':s,'source_locator':l,'notes':'Special-capital and regional paths remain separate.','verification_status':'source_verified','confidence':'high'}
 def cl(e,pop,l):return {'id':record_id('CLM-DJ','population',e,ASOF),'schema_version':SCHEMA_VERSION,'subject_id':e,'predicate':'population','value':{'type':'integer','data':pop},'unit':'person','status':'reported','observed_at':ASOF,'valid_from':None,'valid_to':None,'source_id':SCEN,'second_source_id':None,'source_locator':l,'sensitivity':'ordinary','notes':'Provisional RGPH-3 result at end of collection.','verification_status':'source_verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None}
 for g in f['regions']:
  gid='ENT-DJ-REGION-'+g['token'];loc=f"Presidency region {g['name_fr']}; RGPH-3 population {g['population']}";E.append(ent(gid,g['name_fr'],'dj_region',SREG,loc,'Decentralized regional collectivity, not Djibouti City.'));R.append(rel(gid,'ENT-DJ-COUNTRY','administrative_parent',SREG,loc));C.append(cl(gid,g['population'],loc))
  for q in g['subprefectures']:
   sid='ENT-DJ-SUBPREFECTURE-'+q['token'];sl=f"Roadmap Table 3: {q['name_fr']} under {g['name_fr']}";E.append(ent(sid,q['name_fr'],'dj_subprefecture',SSUB,sl,'State sub-prefecture, not decentralized commune.'));R.append(rel(sid,gid,'administrative_parent',SSUB,sl))
 city='ENT-DJ-DJIBOUTI-CITY';E.append(ent(city,'Djibouti-Ville','djibouti_city',SLAW,'Law 122 special-status city','Special territorial collectivity parallel to five regions.'));R.append(rel(city,'ENT-DJ-COUNTRY','administrative_parent',SLAW,'Law 122'));C.append(cl(city,f['city_population'],'RGPH-3 Djibouti-Ville row'))
 for q in f['city']['communes']:
  cid='ENT-DJ-COMMUNE-'+q['token'];loc=f"Law 122 Article 2: commune {q['name_fr']}";E.append(ent(cid,q['name_fr'],'dj_commune',SLAW,loc,'Commune within special-status Djibouti City.'));R.append(rel(cid,city,'administrative_parent',SLAW,loc))
 DE,DR,DC=depth_items(dd);E+=DE;R+=DR;C+=DC;ids={x['id'] for x in E}|{'ENT-DJ-COUNTRY'}|{x['subject_id'] for x in C};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='DJ' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-DJ-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-DJ-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DJ','layer':l,'definition':note,'value':n,'as_of':ASOF,'status':'official','source_id':s,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':ASOF}
 def v(i,l,did,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DJ','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('REGIONS','dj_region',5,SREG),('SPECIAL-CITY','djibouti_city',1,SLAW),('CITY-COMMUNES','dj_commune',3,SLAW),('SUBPREFECTURES','dj_subprefecture',13,SSUB)];ds=[d('DEN-DJ-'+a,l,n,s,f'Exact {n}-record {l} scope.') for a,l,n,s in specs];vs=[v('COV-DJ-'+a,l,'DEN-DJ-'+a,n,s,f'{n}/{n} matched; topology-specific scope.') for a,l,n,s in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='DJ' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='DJ' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Djibouti special-capital and regional topology','captured_at':DATE,'source_id':SREG,'scope':'Five regions, special city, three city communes, thirteen sub-prefectures','method':'Checksum-bound official legal/statistical reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Arrondissements/zones and broad culture/dialect remain unclosed.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-DJ-'),[snap])
 man=L(ROOT/'manifests/DJ.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Présidence / Ministère de l’Intérieur / INSTAD','source_ids':[SREG,SLAW,SCEN,SINT],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-DJ-COUNTRY-SCOPE',*[f'COV-DJ-{a}' for a,_,_,_ in specs]],'caveats':['Djibouti-Ville is parallel to five regions.','Communes belong to special city; sub-prefectures belong to regions.','No arrondissement/zone denominator asserted.'],'next_action':'Maintain separate topology profiles; expand only from current legal enumerations.'})
 vals={'dj_region':(5,'REGIONS',SREG),'djibouti_city':(1,'SPECIAL-CITY',SLAW),'dj_commune':(3,'CITY-COMMUNES',SLAW),'dj_subprefecture':(13,'SUBPREFECTURES',SSUB)}
 for q in man['hierarchy']:
  if q['entity_type'] in vals:
   n,a,s=vals[q['entity_type']];q.update({'source_ids':[s],'verification_status':'verified','authority_name':'République de Djibouti','denominator':n,'denominator_id':'DEN-DJ-'+a,'coverage_record_id':'COV-DJ-'+a,'snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'Topology-specific closed scope.','special_cases':['Do not merge special-city and regional paths.']})
 man['pilot_layers']=[{'layer':l,'entity_types':[l],'local_names':['collectivité'],'authority_name':'République de Djibouti','denominator':n,'denominator_id':'DEN-DJ-'+a,'coverage_record_id':'COV-DJ-'+a,'snapshot_date':ASOF,'source_ids':[s],'license':LIC,'scope_status':'closed','notes':'Separate topology scope.','special_cases':[]} for a,l,n,s in specs]+depth_layers();write_json(ROOT/'manifests/DJ.yml',man);write_json(ROOT/'data/cultural/djibouti_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'DJ','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented_zero_inscribed','denominator':0,'tentative_list_sites':10},'intangible_cultural_heritage':{'status':'documented_three_elements_one_national','elements':['الخيدو 02001 (2023، قائمة الصون العاجل، جيبوتي وحدها)','الزير عيسى 02087 (2024، ثلاث دول)','الزفّة 02283 (2025، سبع دول)'],'pending_nomination':'المدقة العفارية (2026)'},'languages':{'status':'documented_two_official_two_national_unpublished','claims':8},'dialect':{'status':'documented_local_reported_unpublished','claims':1},'script':{'status':'documented_local_reported_unpublished','claims':1},'language_institutions':{'status':'documented_local_reported_unpublished','claims':1},'food':{'status':'documented_local_reported_unpublished','claims':12},'dress':{'status':'documented_local_reported_unpublished','claims':3},'crafts':{'status':'documented_local_reported_unpublished','claims':2},'custom':{'status':'documented_local_reported_unpublished','claims':3},'capital_places':{'status':'documented_places_no_denominator','entities':12,'denominator':None}},'notes':'Administrative micro pilot; zero inscribed is not cultural absence.'});print(json.dumps({'entities':len(E),'relationships':len(R),'claims':len(C),'depth_claims':sum(1 for c in C if c['id'].startswith('CLM-DJ-DEPTH')),'places':len([e for e in E if e['entity_type'] in ('quarter','market')]),'sources':len(S)}))
if __name__=='__main__':main()
