#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/morocco';F=I/'fixtures/territorial_division_2015.json';CD=I/'fixtures/cultural_depth_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';ASOF='2015-03-05';SNAP='SNP-MA-PRODUCTION-20260816';DEC='SRC-MA-DGCT-DECREE-2-15-10';DGCT='SRC-MA-DGCT-TERRITORIAL-COUNTS-2026';HCP='SRC-MA-HCP-RGPH-2024';CULT='SRC-MA-CULTURE-MIRROR-2026';LIC='Official Morocco public material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'fr','country_codes':['MA'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();rec={r['path'].split('/')[-1]:r['sha256'] for r in m['records']};fc=L(CD)
 children=[c for r in f['regions'] for c in r['children']];assert len(f['regions'])==12 and len(children)==75 and sum(c['entity_type']=='ma_prefecture' for c in children)==13 and hashlib.sha256(b).hexdigest()==rec['territorial_division_2015.json']
 assert hashlib.sha256(CD.read_bytes()).hexdigest()==rec['cultural_depth_2026.json'] and len(fc['dishes'])==9 and len(fc['amazigh_languages'])==4 and len(fc['dress'])==3
 S=[src(DEC,'Nouveau découpage territorial — Décret 2.15.10','Direction Générale des Collectivités Territoriales','law',f['sources']['decree'],'12 regions, capitals, constituent prefectures/provinces','Legal 2015 hierarchy.',pub='2015-03-05'),src(DGCT,'Présentation des collectivités territoriales','Direction Générale des Collectivités Territoriales','official_register',f['sources']['presentation'],'12 regions, 75 prefectures/provinces, 1503 communes','Current denominator cross-check; arrondissement-prefecture universe excluded.'),src(HCP,'RGPH 2024 population légale by territorial unit','Haut-Commissariat au Plan','census',f['sources']['census'],'legal population by region, province/prefecture and commune','Census scope cross-check; population values deferred from this hierarchy cycle.'),{'id':CULT,'schema_version':SCHEMA_VERSION,'title':'Moroccan Darija, Amazigh varieties, cuisine, and dress — encyclopedic mirror pages','publisher':'Encyclopedic mirror pages on Moroccan culture','source_type':'institutional_page','url':fc['sources']['dialect_mirror'],'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['MA'],'locator':'Darija profile, Amazigh variety scopes, dish and dress entries','checksum':'sha256:'+hashlib.sha256(CD.read_bytes()).hexdigest(),'quality_tier':'E','notes':'Depth-cycle weak/secondary mirror. Cultural claims stay local_reported/probable and unpublished; couscous carries shared classification via the quadripartite UNESCO 2020 file, never exclusive ownership. Publication date unavailable.'}]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'MA','sources':S});E=[];A=[];R=[];C=[]
 def ent(i,n,t,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MA','canonical_name':n,'canonical_name_language':'fr','entity_type':t,'status':'current','valid_from':ASOF,'valid_to':None,'canonical_source_id':DEC,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'verified','confidence':'high'}
 def rel(ch,pa,loc):return {'id':record_id('REL-MA',ch,pa),'schema_version':SCHEMA_VERSION,'child_id':ch,'parent_id':pa,'relationship_type':'administrative_parent','status':'current','valid_from':ASOF,'valid_to':None,'source_id':DEC,'source_locator':loc,'notes':'Prefecture and province semantics remain distinct.','verification_status':'verified','confidence':'high'}
 for g in f['regions']:
  gid='ENT-MA-REGION-'+g['token'];loc=f"Decree 2.15.10 region {g['name_fr']}; capital {g['capital_fr']}";E.append(ent(gid,g['name_fr'],'ma_region',loc,'Current legal region; no centroid invented.'));R.append(rel(gid,'ENT-MA-COUNTRY',loc));counts={'ma_prefecture':0,'ma_province':0}
  for q in g['children']:
   counts[q['entity_type']]+=1;eid=('ENT-MA-PREFECTURE-' if q['entity_type']=='ma_prefecture' else 'ENT-MA-PROVINCE-')+q['token'];ql=f"Decree 2.15.10: {q['name_fr']} in {g['name_fr']}";E.append(ent(eid,q['name_fr'],q['entity_type'],ql,'Legal second-level collectivity; arrondissement prefectures excluded.'));R.append(rel(eid,gid,ql))
  C.append({'id':record_id('CLM-MA','second-level-count',gid),'schema_version':SCHEMA_VERSION,'subject_id':gid,'predicate':'second_level_collectivity_count','value':{'type':'json','data':counts},'unit':'collectivity','status':'verified','observed_at':ASOF,'valid_from':ASOF,'valid_to':None,'source_id':DEC,'second_source_id':DGCT,'source_locator':loc,'sensitivity':'ordinary','notes':'Prefectures and provinces counted separately.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'national 75 prefectures/provinces denominator','lexical_context':None})
 # Cultural depth cycle: language presence, Darija profile+lexicon, dishes, dress. Unpublished, classified.
 def dc(key,subj,pred,val,loc,vs,cls,note):
  C.append({'id':record_id('CLM-MA-DEPTH',key),'schema_version':SCHEMA_VERSION,'subject_id':subj,'predicate':pred,'value':val,'unit':None,'status':'reported','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':CULT,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':note,'verification_status':vs,'confidence':'medium' if vs=='probable' else 'low','classification':cls,'published':False,'second_source_locator':None,'lexical_context':None})
 for q in fc['amazigh_languages']:
  dc('lang|'+q['name'],q['subject'],'language_presence',{'type':'json','data':{'language':q['name'],'description':q['desc']}},f"Language note: {q['name']}",'probable','regional','Amazigh is constitutionally official (2011); variety scopes from secondary mirrors; probable pending an academic atomic source; unpublished.')
 dp=fc['darija_profile']
 dc('darija',dp['subject'],'dialect_profile',{'type':'json','data':{'group':'الدارجة المغربية','features':dp['features'],'sample_words':dp['words']}},'Darija profile and 10-word lexicon','local_reported','national','Darija profile and lexicon from secondary mirrors; the Arabic-vs-hybrid linguistic debate is recorded neutrally; unpublished.')
 for q in fc['dishes']:
  dc('dish|'+q['name'],q['subject'],'food_dish',{'type':'json','data':{'name':q['name'],'description':q['desc'],'occasion':q['occasion'],'note':q['note']}},f"Dish entry: {q['name']}",'local_reported',q['classification'],'Culinary knowledge from weak/secondary mirrors; unpublished. Couscous stays shared via the quadripartite UNESCO 2020 file.')
 for q in fc['dress']:
  dc('dress|'+q['name'],q['subject'],'clothing_item',{'type':'json','data':{'name':q['name'],'gender':q['gender'],'description':q['desc']}},f"Dress entry: {q['name']}",'local_reported',q['classification'],'Dress knowledge from weak/secondary mirrors; regional variant names attested, never invented; unpublished.')
 ids={x['id'] for x in E}|{'ENT-MA-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='MA' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-MA-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-MA-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MA','layer':l,'definition':note,'value':n,'as_of':ASOF,'status':'official','source_id':DEC,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':ASOF}
 def v(i,l,did,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'MA','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':DEC,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('REGIONS','ma_region',12),('PREFECTURES','ma_prefecture',13),('PROVINCES','ma_province',62)];ds=[d('DEN-MA-'+a,l,n,f'Exact legal {l} denominator.') for a,l,n in specs];vs=[v('COV-MA-'+a,l,'DEN-MA-'+a,n,f'{n}/{n} matched.') for a,l,n in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='MA' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='MA' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Morocco 2015 territorial hierarchy','captured_at':DATE,'source_id':DEC,'scope':'12 regions, 13 prefectures, 62 provinces','method':'Checksum-bound decree/DGCT reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'1503 communes deferred; arrondissement prefectures excluded.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-MA-'),[snap])
 man=L(ROOT/'manifests/MA.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Direction Générale des Collectivités Territoriales','source_ids':[DEC,DGCT,HCP],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-MA-COUNTRY-SCOPE',*[f'COV-MA-{a}' for a,_,_ in specs]],'caveats':['Prefectures, provinces, and prefectures of arrondissements are distinct.','1503 communes deferred until second-level acceptance.','No broad culture/dialect denominator asserted.'],'next_action':'Maintain 12/13/62 hierarchy; begin communes only with RGPH/DGCT atomic register.'})
 vals={l:(n,a) for a,l,n in specs}
 for q in man['hierarchy']:
  if q['entity_type'] in vals:
   n,a=vals[q['entity_type']];q.update({'source_ids':[DEC,DGCT],'verification_status':'verified','authority_name':'DGCT','denominator':n,'denominator_id':'DEN-MA-'+a,'coverage_record_id':'COV-MA-'+a,'snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'Legal 2015 scope.','special_cases':['Arrondissement prefectures excluded from 75.']})
  elif q['entity_type']=='ma_commune':q.update({'verification_status':'pending','authority_name':'DGCT','denominator':1503,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'open','notes':'Known count; record-level import deferred.','special_cases':[]})
 man['pilot_layers']=[{'layer':l,'entity_types':[l],'local_names':['collectivité'],'authority_name':'DGCT','denominator':n,'denominator_id':'DEN-MA-'+a,'coverage_record_id':'COV-MA-'+a,'snapshot_date':ASOF,'source_ids':[DEC,DGCT],'license':LIC,'scope_status':'closed','notes':'Legal hierarchy.','special_cases':[]} for a,l,n in specs];write_json(ROOT/'manifests/MA.yml',man);write_json(ROOT/'data/cultural/morocco_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'MA','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_micro_pilot'},'dialect':{'status':'documented_local_reported_unpublished','claims':5},'cuisine':{'status':'documented_local_reported_unpublished','claims':9},'dress':{'status':'documented_local_reported_unpublished','claims':3}},'notes':'Administrative micro pilot only.'});print(json.dumps({'entities':87,'relationships':87,'claims':29,'sources':4}))
if __name__=='__main__':main()
