#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/comoros';F=I/'fixtures/current_hierarchy_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-KM-PRODUCTION-20260817';LAW='SRC-KM-LAW-11-006-AU-2011';INS='SRC-KM-INSEED-RGPH17-ADMIN';WHC='SRC-UNESCO-WHC-KM-1768-2026';LIC='Official Comoros public/statistical material; factual extraction with attribution; reuse terms not stated';WL='CC BY-SA 3.0 IGO for UNESCO descriptions'
def L(p):return json.loads(p.read_text(encoding='utf8'))

D=I/'fixtures/cultural_depth_2026.json';DDATE='2026-09-20'
DS={'ich':'SRC-UNESCO-ICH-KM-ZAFFA-2025','constitution':'SRC-KM-CONSTITUTION-2018','iso':'SRC-KM-ISO639-3-COMORIAN','medinas_wiki':'SRC-KM-MEDINAS-WIKI-2026','languages_mirror':'SRC-KM-LANGUAGES-MIRROR-2026','comorian_langs':'SRC-KM-COMORIAN-LANGS-WIKI-2026','cuisine_mirror':'SRC-KM-CUISINE-MIRROR-2026','food_travel':'SRC-KM-FOOD-TRAVEL-2021','food_youm7':'SRC-KM-FOOD-YOUM7-2022','culture_raseef22':'SRC-KM-CULTURE-RASEEF22-2023','custom_jazeera':'SRC-KM-CUSTOM-JAZEERA-2025','custom_midad':'SRC-KM-CUSTOM-MIDAD-2016','economy_mirror':'SRC-KM-ECONOMY-MIRROR-2015','vocab_quizlet':'SRC-KM-VOCAB-QUIZLET-2016','culture_alayyam':'SRC-KM-CULTURE-ALAYYAM-2024'}
ELOC='Official Comoros material; factual extraction with attribution; reuse terms not stated';ILOC='UNESCO ICH element page; factual extraction with attribution';WLOC='Mirror and press material; factual extraction with attribution; reuse terms not stated'
def dsrc(i,t,pu,ty,u,loc,note,tier='E',lang='ar',lic=ELOC,pub=None):
 return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':pu,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DDATE,'license':lic,'language':lang,'country_codes':['KM'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(D.read_bytes()).hexdigest(),'quality_tier':tier,'notes':note+('' if pub else ' Publication date unavailable.')}
def depth_sources():
 return [dsrc(DS['ich'],'The zaffa in the traditional wedding','UNESCO Intangible Cultural Heritage','institutional_page','https://ich.unesco.org/en/RL/the-zaffa-in-the-traditional-wedding-02283',"element 02283; inscribed 2025 (20.COM) on the Representative List; seven submitting States",'Element page read 2026-09-20: description, year, and submitting States. Publication date unavailable on the element page.',tier='A',lang='en',lic=ILOC),
 dsrc(DS['constitution'],'Comoros 2018 Constitution (as published by Constitute)','Constitute Project — Comparative Constitutions Project','law','https://www.constituteproject.org/constitution/Comoros_2018','Article 6 territory; Article 9 official languages; Article 10 capital','Constitutional text as published by the Constitute Project. The page carries no publication date and the promulgation date is not asserted here. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['iso'],'ISO 639-3 code set for the Comorian varieties','SIL International (ISO 639-3 registration authority)','standard','https://iso639-3.sil.org/code/zdj','zdj Ngazidja; wni Ndzwani; swb Maore; wlc Mwali','Registration-authority code set recorded with the four variety codes. The registry page carries no publication date. Publication date unavailable.',tier='A',lang='en'),
 dsrc(DS['medinas_wiki'],'مدن الموقع المتسلسل 1768 — قائمة المكوّنات','ويكيبيديا الإنجليزية / ويكي بيانات','local_website',"https://en.wikipedia.org/wiki/Moroni,_Comoros",'criteria (iii)(iv); reference 1768; Q65724639 parts: Moroni, N Tsoudjini, Itsandra, Iconi, Mutsamudu, Domoni','Mirror and Wikidata list of the six component medinas: the UNESCO description names six historic towns without enumerating them, so the names stay local_reported and unpublished.',lang='ar',lic=WLOC),
 dsrc(DS['languages_mirror'],'لغات جزر القمر','ويكيبيديا العربية (نسخة مرآة)','local_website','https://ar.wikipedia.org/wiki/لغات_جزر_القمر','اللغات الرسمية الثلاث، واللهجات الأربع، واللغات الأقلية (الملغاشية والسواحيلية)','مرآة عربية: تصف اللغات الرسمية ولهجات الشيكوموري الأربع واللغات الأقلية محدودة الاستخدام.',lang='ar',lic=WLOC),
 dsrc(DS['comorian_langs'],'Comorian languages — codes, groupings and numerals','Wikipedia (English mirror)','local_website','https://en.wikipedia.org/wiki/Comorian_languages','dialects Maore/Ngazidja/Mwali/Ndzwani; ISO codes; numerals 1-10; Sabaki/Bantu classification','Mirror page used for the language family classification, the two dialect groups, the code list, and the numeral table.',tier='E',lang='en',lic=WLOC),
 dsrc(DS['cuisine_mirror'],'مطبخ قمري','ويكيبيديا العربية (نسخة مرآة)','local_website','https://ar.wikipedia.org/wiki/مطبخ_قمري','روتي يا هوما بامبا؛ متسولولا؛ الماتافا؛ الروجيل','مرآة عربية لأمثلة الأطباق القمرية ووصفها.',lang='ar',lic=WLOC),
 dsrc(DS['food_travel'],'أفضل أكلات جزر القمر: لا تفوت فرصة التعرف عليها','موضوع مسافر','local_website','https://travel.mawdoo3.com/s/2767','مكاترا فوترا؛ جراد البحر بالفانيليا؛ كاري الدجاج؛ أرز جزر القمر؛ شوربة البازلاء','مادة طعام محلية بمكونات كل طبق؛ تُستعمل غير منشورة.',lang='ar',lic=WLOC,pub='2021-12-05'),
 dsrc(DS['food_youm7'],'أشهر 7 أكلات شعبية في جزر القمر','اليوم السابع','local_press','https://www.youm7.com/story/2022/1/26/5632646','لانجوست آ لا فانيل؛ مكاترا فطرة؛ مشاكيكي؛ حساء البازلاء بالكاري','مادة صحفية محلية تسمّي الأطباق بمكوناتها، وتذكر تقديم مكاترا فطرة مع القهوة العربية المحلاة بالعسل.',lang='ar',lic=WLOC,pub='2022-01-26'),
 dsrc(DS['culture_raseef22'],'ما لا يحدث إلا في جزر القمر... عن أغرب العادات في الأرخبيل المذهل','رصيف22','local_website','https://raseef22.net/article/1093056','الشيروميني؛ السارونج؛ تسولولا؛ ميتساميولي؛ مجلس الذكر','شهادة صحفية محلية تصف اللباس والطعام والعادات في ميتساميولي.',lang='ar',lic=WLOC,pub='2023-05-05'),
 dsrc(DS['custom_jazeera'],'السلطان و«الزواج الكبير» في جزر القمر.. إرث ثقافي يتوّج الهوية الاجتماعية','الجزيرة نت','local_press','https://www.aljazeera.net/culture/2025/8/7','مجلس الذكر؛ المهر 10-30 قطعة ذهبية؛ أوكومبي؛ النسب الأمومي والإقامة في بيت الزوجة','تقرير صحفي مفصّل عن الزواج الكبير في موروني؛ يُسجَّل بوصفه مصدرًا من الفئة B (وكالة/صحيفة كبرى) مع بقاء الدعوى مصنَّفة.',tier='B',lang='ar',lic=WLOC,pub='2025-08-07'),
 dsrc(DS['custom_midad'],'في جزر القمر إما الزواج الكبير وإما الحرمان من هذه الأشياء','مِداد','local_website','https://midad.com/article/218038','زواج العفة مقابل الزواج الكبير؛ ما يُحجب عن غير المتزوج؛ مراسم مجلس الذكر والوفود والدف','مادة محلية تصف مراسم الزواج الكبير وما يرتبط به من مكانة؛ تُستعمل غير منشورة.',lang='ar',lic=WLOC),
 dsrc(DS['economy_mirror'],'اقتصاد جزر القمر','ويكيبيديا العربية (نسخة مرآة)','local_website','https://ar.wikipedia.org/wiki/اقتصاد_جزر_القمر','الفانيليا والقرنفل وجوز الهند؛ اليلنغ يلانغ؛ ترتيب الإنتاج عالميًا','مرآة عربية لأوصاف الاقتصاد الزراعي؛ تُسجَّل وصفًا لا إحصاءً مؤرخًا.',lang='ar',lic=WLOC,pub='2015-07-08'),
 dsrc(DS['vocab_quizlet'],'Shikomori — مجموعة تعليمية للمفردات والعبارات','Quizlet (مجموعة تعلم محلية)','forum','https://quizlet.com/84861856/shikomori-flash-cards/','عبارات أساسية بمعانيها الإنجليزية مثل Eledzina lahaho ndo? وNtsudjuwa','مجموعة تعليمية محلية لا تميّز اللهجات وتضمّ مفردات ذات أثر سواحيلي؛ تُستعمل لمفردات مصنَّفة غير منشورة فقط.',lang='ar',lic=WLOC),
 dsrc(DS['culture_alayyam'],'المسلمون في جزر القمر','صحيفة الأيام','local_press','https://www.alayyam.info/news/9RQHMT5F-HEOPIO-839E','التشيروماني: قطعة قماش مطبوع تُلفّ حول الجسم في المناسبات','مادة صحفية محلية تصف التشيروماني ضمن اللباس النسائي في المناسبات.',lang='ar',lic=WLOC,pub='2024-07-04')]
def depth_items(dd):
 E2=[];R2=[];C2=[];wid='ENT-KM-CULTURAL-SITE-HISTORIC-SULTANATES-MEDINAS'
 def clm(key,sub,pred,val,src,loc,cls,note,vs='local_reported',conf='low',st='reported',pub=False,second=None,second_loc=None,unit=None,typ='json',obs=DDATE):
  return {'id':record_id('CLM-KM-DEPTH',key),'schema_version':SCHEMA_VERSION,'subject_id':sub,'predicate':pred,'value':{'type':typ,'data':val},'unit':unit,'status':st,'observed_at':obs,'valid_from':None,'valid_to':None,'source_id':src,'second_source_id':second,'source_locator':loc,'second_source_locator':second_loc,'sensitivity':'ordinary','notes':note,'verification_status':vs,'confidence':conf,'classification':cls,'published':pub,'lexical_context':None}
 for x in dd['places']['medinas']:
  iid='ENT-KM-MEDINA-'+x['token'];loc=f"مكوّن الموقع المتسلسل 1768: {x['name']} ({x['latin']}) على جزيرة {x['island']}"
  E2.append({'id':iid,'schema_version':SCHEMA_VERSION,'country_code':'KM','canonical_name':x['name'],'canonical_name_language':'ar','entity_type':'quarter','status':'historical','valid_from':None,'valid_to':None,'canonical_source_id':DS['medinas_wiki'],'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':loc+' — مكان تاريخي داخل نطاق الموقع المسجَّل؛ لا صفة إدارية حالية ولا أب إداري ولا سكان ولا نسبة.','verification_status':'local_reported','confidence':'low'})
  R2.append({'id':record_id('REL-KM-LOCATED',iid,'ENT-KM-ISLAND-'+x['island']),'schema_version':SCHEMA_VERSION,'child_id':iid,'parent_id':'ENT-KM-ISLAND-'+x['island'],'relationship_type':'located_in','status':'historical','valid_from':None,'valid_to':None,'source_id':DS['medinas_wiki'],'source_locator':loc,'notes':'علاقة مكانية مع الجزيرة فقط: مجموعة البلديات المقبولة لا تشمل كل أسماء المدن التاريخية، فلا يُستنتج أب إداري أدنى.','verification_status':'local_reported','confidence':'low'})
 for e in dd['ich_elements']:
  C2.append(clm('ich|'+e['name'],'ENT-KM-COUNTRY','intangible_cultural_practice',{'name':e['name'],'official_title':e['official_title'],'official_title_ar':e['official_title_ar'],'reference':e['reference'],'year':e['year'],'list':e['list'],'url':e['url'],'co_states':e['co_states'],'description':e['description']},DS['ich'],f"قائمة اليونسكو للتراث الثقافي غير المادي: {e['official_title']} ({e['year']}, ref {e['reference']}) — ملف بتقديم سبع دول",e['classification'],'عنصر مدرج في القائمة التمثيلية بتقديم سبع دول، فلا يُنسب حصريًا إلى جزر القمر؛ والوصف هو الوصف المسجَّل.',vs='verified',conf='high',st='verified',pub=True))
 w=dd['world_heritage_extra'];wloc=f"الموقع المتسلسل 1768: {w['criteria']}؛ {w['area_hectares']} هكتار ومنطقة عازلة {w['buffer_zone_hectares']} هكتار"
 C2.append(clm('whc|criteria',wid,'world_heritage_criteria',w['criteria'],'SRC-UNESCO-WHC-KM-1768-2026',wloc,'official','معايير الإدراج كما وردت في صفحة الموقع.',vs='verified',conf='high',st='verified',pub=True,typ='string'))
 C2.append(clm('whc|area',wid,'world_heritage_area_hectares',w['area_hectares'],'SRC-UNESCO-WHC-KM-1768-2026',wloc,'official','مساحة الموقع بالهكتار كما وردت في صفحة الموقع.',vs='verified',conf='high',st='verified',pub=True,unit='hectare',typ='number'))
 C2.append(clm('whc|buffer',wid,'world_heritage_buffer_zone_hectares',w['buffer_zone_hectares'],'SRC-UNESCO-WHC-KM-1768-2026',wloc,'official','مساحة المنطقة العازلة بالهكتار كما وردت في صفحة الموقع.',vs='verified',conf='high',st='verified',pub=True,unit='hectare',typ='number'))
 C2.append(clm('whc|components',wid,'serial_component_names',[{'name':c['name'],'latin':c['latin'],'island':c['island']} for c in w['components']],DS['medinas_wiki'],w['note'],'local','أسماء المكوّنات الستة من المرآة وويكي بيانات؛ صفحة اليونسكو المقروءة تذكر ست مدن دون تعداد، فتبقى الأسماء غير منشورة.'))
 for c in dd['constitution_provisions']:
  C2.append(clm('const|'+c['topic'],'ENT-KM-COUNTRY','constitutional_provision',{'article':c['article'],'topic':c['topic'],'summary':c['summary'],'note':c.get('note')},DS['constitution'],f"دستور 2018، المادة {c['article']}",'official','نصّ دستوري موثَّق من مصدر من الفئة A؛ تُسجَّل الأحكام كما وردت ولا تُحوَّل إلى مقام إداري.',vs='verified',conf='high',st='verified',pub=True))
 for l in dd['languages']:
  src=DS[l['source']];second=DS[l['second']] if l.get('second') else None
  C2.append(clm('lang|'+l['name'],'ENT-KM-COUNTRY','language_presence',{'name':l['name'],'official':l['official'],'iso_codes':l.get('codes',[]),'note':l['note']},src,f"حضور لغوي: {l['name']}",'official' if l['official'] else 'regional','لغة رسمية مسنودة بالمادة 9 من الدستور' if l['official'] else 'لغة أقلية غير رسمية من مرآة محلية؛ لا أرقام متحدثين ولا نطاق إداري.',vs='verified' if l['official'] else 'local_reported',conf='high' if l['official'] else 'low',st='verified' if l['official'] else 'reported',pub=bool(l['official']),second=second,second_loc=('ISO 639-3 registry codes' if second else None)))
 for p in dd['dialect_profiles']:
  src=DS[p['source']];payload={'variety':p['variety'],'island':p['island'],'group':p['group'],'features':p['features']}
  if p.get('numerals'):payload['numerals']=p['numerals']
  if p.get('phrases'):payload['phrases']=p['phrases']
  C2.append(clm('dialect|'+p['variety'],'ENT-KM-COUNTRY','dialect_profile',payload,src,f"لهجة/معجم: {p['variety']} — {p['group']}",'regional' if p['island']!=None else 'local','وصف لهجي مصنَّف؛ التصنيف إلى مجموعتين شرقية وغربية من المرآة، والمفردات بمعانيها ولا تُنسب إلى مقام.',second=DS[p['vocabulary_source']] if p.get('vocabulary_source') else None,second_loc=('مجموعة تعليمية للعبارات بمعانيها' if p.get('vocabulary_source') else None)))
 for x in dd['dishes']:
  C2.append(clm('dish|'+x['name'],'ENT-KM-COUNTRY','food_dish',{'name':x['name'],'description':x['desc']},DS[x['source']],f"طبق قمري: {x['name']}",x['classification'],'معرفة طعام محلية مصنَّفة وغير منشورة؛ تُفصل عن عنصر اليونسكو العام.',second=DS[x['second']] if x.get('second') else None,second_loc=x.get('second_locator')))
 for x in dd['dress']:
  C2.append(clm('dress|'+x['name'],'ENT-KM-COUNTRY','clothing_item',{'name':x['name'],'gender':x['gender'],'description':x['desc']},DS[x['source']],f"زي قمري: {x['name']}",x['classification'],'وصف لباس محلي مصنَّف وغير منشور.',second=DS[x['second']] if x.get('second') else None,second_loc=x.get('second_locator')))
 for x in dd['crafts']:
  C2.append(clm('craft|'+x['name'],'ENT-KM-COUNTRY','craft_custom',{'name':x['name'],'description':x['desc']},DS[x['source']],f"حرفة/اقتصاد ثقافي: {x['name']}",x['classification'],'حرفة واقتصاد ثقافي من مرآة محلية؛ يُعرض وصفًا لا إحصاءً مؤرخًا.'))
 for x in dd['customs']:
  C2.append(clm('custom|'+x['name'],'ENT-KM-COUNTRY','custom_practice',{'name':x['name'],'description':x['desc']},DS[x['source']],f"عرف محلي: {x['name']}",x['classification'],'عرف اجتماعي محلي مصنَّف وغير منشور؛ يُفصل عن عنصر الزفّة المسجَّل عند اليونسكو ولا يُساوى به.',second=DS[x['second']] if x.get('second') else None,second_loc=x.get('second_locator')))
 return E2,R2,C2
def depth_layers():
 return [{'layer':'unesco_intangible_heritage','entity_types':['cultural_site'],'local_names':['عنصر تراث غير مادي'],'authority_name':'UNESCO Intangible Cultural Heritage','denominator':1,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['ich']],'license':ILOC,'scope_status':'closed','notes':'العنصر الوحيد المدرج لجزر القمر (زفّة العرس التقليدي 02283) ملف بتقديم سبع دول، وقائمته هي مقامه بلا سجل تغطية.','special_cases':['كل عنصر قمري حالي ملف متعدد الدول: التصنيف يبقى shared ولا تُدَّعى حصرية.']},
 {'layer':'world_heritage_medinas','entity_types':['quarter'],'local_names':['مدينة تاريخية'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS['medinas_wiki']],'license':WLOC,'scope_status':'open','notes':'ست مدن تاريخية مدرجة في الموقع المتسلسل 1768 كأماكن بلا مقام، بلا أب إداري وبلا سكان وبلا نسبة.','special_cases':['لا يُنشأ كيان لكل مكوّن إداري، وتُربط المدن بالجزيرة فقط.']},
 {'layer':'classified_local_knowledge','entity_types':['cultural_site'],'local_names':['معرفة محلية مصنَّفة'],'authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':DDATE,'source_ids':[DS[k] for k in ('languages_mirror','comorian_langs','cuisine_mirror','food_travel','food_youm7','culture_raseef22','custom_jazeera','custom_midad','economy_mirror','vocab_quizlet','culture_alayyam')],'license':WLOC,'scope_status':'open','notes':'معرفة محلية مصنَّفة وغير منشورة: خمس دعاوى لغوية ولهجية، وعشرة أطباق، وثلاثة أزياء، وحرفة، وعرفان.','special_cases':['لا يُنشر أي ادعاء ضعيف المصدر ولا يُبنى عليه مقام.','لا تُسجَّل أرقام متحدثين ولا تُبنى نسب على المرآة.']}]

def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,lic=LIC,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':lic,'language':'fr','country_codes':['KM'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['islands'])==3 and sum(len(i['prefectures']) for i in f['islands'])==16 and sum(len(p['communes']) for i in f['islands'] for p in i['prefectures'])==54 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(LAW,'Loi 11-006/AU — organisation territoriale','Ministère de la Justice, Union des Comores','law',f['sources']['law'],'three islands, sixteen prefectures, commune enumeration','Legal current administration; Mayotte excluded.',pub='2011-05-02'),src(INS,'INSEED administrative population table — RGPH 2017','INSEED Comores','census',f['sources']['inseed'],'population by island, prefecture and 54 communes','Record-level census cross-check.'),src(WHC,'The Medinas of the Historic Sultanates of the Comoros','UNESCO World Heritage Committee','institutional_page',f['sources']['unesco'],'Decision 48 COM 8B.13; property 1768; six serial components','2026 inscription; older zero-property page superseded.',WL,pub='2026-07-29')]+depth_sources()
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'KM','sources':S});E=[];R=[];C=[]
 def ent(i,n,t,s,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KM','canonical_name':n,'canonical_name_language':'fr','entity_type':t,'status':'current','valid_from':None,'valid_to':None,'canonical_source_id':s,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'verified','confidence':'high'}
 def rel(ch,pa,s,loc,kind='administrative_parent'):return {'id':record_id('REL-KM',ch,pa),'schema_version':SCHEMA_VERSION,'child_id':ch,'parent_id':pa,'relationship_type':kind,'status':'current','valid_from':None,'valid_to':None,'source_id':s,'source_locator':loc,'notes':'Current Union-administered topology only.','verification_status':'verified','confidence':'high'}
 for island in f['islands']:
  iid='ENT-KM-ISLAND-'+island['token'];loc=f"Law 11-006/AU island {island['name']}; {len(island['prefectures'])} prefectures";E.append(ent(iid,island['name'],'km_island',LAW,loc,'Autonomous island administered by Union; Mayotte not included.'));R.append(rel(iid,'ENT-KM-COUNTRY',LAW,loc));prefcount=len(island['prefectures']);commcount=sum(len(p['communes']) for p in island['prefectures']);C.append({'id':record_id('CLM-KM','admin-count',iid),'schema_version':SCHEMA_VERSION,'subject_id':iid,'predicate':'administrative_child_counts','value':{'type':'json','data':{'prefectures':prefcount,'communes':commcount}},'unit':'administrative_unit','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':LAW,'second_source_id':INS,'source_locator':loc,'sensitivity':'ordinary','notes':None,'verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'INSEED census table','lexical_context':None})
  for p in island['prefectures']:
   pid='ENT-KM-PREFECTURE-'+p['token'];pl=f"Law prefecture {p['name']} under {island['name']}";E.append(ent(pid,p['name'],'km_prefecture',LAW,pl,'Administrative prefecture, not autonomous island/commune.'));R.append(rel(pid,iid,LAW,pl))
   for q in p['communes']:
    cid='ENT-KM-COMMUNE-'+q['token'];cl=f"Law/INSEED commune {q['name']} under {p['name']}";E.append(ent(cid,q['name'],'km_commune',LAW,cl,'Legal commune; village components not emitted.'));R.append(rel(cid,pid,LAW,cl))
 w=f['world_heritage'];wid=w['entity_id'];loc=f"UNESCO property {w['reference']}; inscribed {w['inscription_year']}; {w['serial_components']} components";E.append(ent(wid,w['name'],'cultural_site',WHC,loc,'One serial World Heritage property; components not separate entities.'));R.append(rel(wid,'ENT-KM-COUNTRY',WHC,loc,'associated_with'))
 for pred,val,typ in [('world_heritage_inscription_year',2026,'integer'),('world_heritage_category','cultural','string'),('serial_component_count',6,'integer')]:C.append({'id':record_id('CLM-KM',pred,wid),'schema_version':SCHEMA_VERSION,'subject_id':wid,'predicate':pred,'value':{'type':typ,'data':val},'unit':'year' if pred.endswith('year') else None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':WHC,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':None,'verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 dd=L(D)
 assert dd['schema_version']==SCHEMA_VERSION and dd['country_code']=='KM'
 assert (len(dd['ich_elements']),len(dd['constitution_provisions']),len(dd['languages']),len(dd['dialect_profiles']),len(dd['dishes']),len(dd['dress']),len(dd['crafts']),len(dd['customs']))==(1,3,5,5,10,3,1,2)
 assert len(dd['places']['medinas'])==6 and len(dd['world_heritage_extra']['components'])==6
 assert hashlib.sha256(D.read_bytes()).hexdigest()==next(r['sha256'] for r in m['records'] if r['path']=='data/imports/comoros/fixtures/cultural_depth_2026.json')
 DE,DR,DC=depth_items(dd);E+=DE;R+=DR;C+=DC
 ids={x['id'] for x in E}|{'ENT-KM-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='KM' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-KM-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-KM-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KM','layer':l,'definition':note,'value':n,'as_of':DATE,'status':'official','source_id':s,'source_locator':note,'license':lic,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'KM','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':lic,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('ISLANDS','km_island',3,LAW,LIC),('PREFECTURES','km_prefecture',16,LAW,LIC),('COMMUNES','km_commune',54,LAW,LIC),('WHC','world_heritage_property',1,WHC,WL)];ds=[d('DEN-KM-'+a,l,n,s,lic,f'Exact {l} denominator.') for a,l,n,s,lic in specs];vs=[v('COV-KM-'+a,l,'DEN-KM-'+a,n,s,lic,f'{n}/{n} matched.') for a,l,n,s,lic in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='KM' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='KM' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Comoros current Union hierarchy and 2026 World Heritage','captured_at':DATE,'source_id':LAW,'scope':'3 islands, 16 prefectures, 54 communes, one serial property','method':'Checksum-bound law/INSEED/UNESCO reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Mayotte excluded from current administration; claimed scope not modeled as current.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-KM-'),[snap])
 man=L(ROOT/'manifests/KM.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Ministry of Justice / INSEED','source_ids':[LAW,INS,WHC],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-KM-COUNTRY-SCOPE',*[f'COV-KM-{a}' for a,_,_,_,_ in specs]],'caveats':['Current Union administration covers three islands; Mayotte excluded.','Village components not communes.','UNESCO 2026 inscription supersedes older zero-property page.'],'next_action':'Maintain 3/16/54 current hierarchy and separate any claimed-territory representation.'})
 vals={l:(n,a) for a,l,n,_,_ in specs if l.startswith('km_')}
 for x in man['hierarchy']:
  if x['entity_type'] in vals:
   n,a=vals[x['entity_type']];x.update({'source_ids':[LAW,INS],'verification_status':'verified','authority_name':'Justice / INSEED','denominator':n,'denominator_id':'DEN-KM-'+a,'coverage_record_id':'COV-KM-'+a,'snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Current Union-administered scope.','special_cases':['Mayotte excluded.']})
 man['pilot_layers']=[{'layer':l,'entity_types':[l],'local_names':['administrative unit'],'authority_name':'Justice / INSEED','denominator':n,'denominator_id':'DEN-KM-'+a,'coverage_record_id':'COV-KM-'+a,'snapshot_date':DATE,'source_ids':[s],'license':lic,'scope_status':'closed','notes':'Current scope.','special_cases':[]} for a,l,n,s,lic in specs]+depth_layers();write_json(ROOT/'manifests/KM.yml',man);write_json(ROOT/'data/cultural/comoros_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'KM','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented','denominator':1,'claims':3},'dialect':{'status':'documented_local_reported_unpublished','claims':5},'languages':{'status':'documented_official_three','claims':5},'food':{'status':'documented_local_reported_unpublished','claims':10},'dress':{'status':'documented_local_reported_unpublished','claims':3},'crafts':{'status':'documented_local_reported_unpublished','claims':1},'custom':{'status':'documented_local_reported_unpublished','claims':2},'intangible_cultural_heritage':{'status':'documented_published_unesco','claims':1,'elements':['زفّة العرس التقليدي 02283 (2025) ملف بتقديم سبع دول']},'world_heritage_medinas':{'status':'documented_heritage_layer_no_denominator','entities':6,'denominator':None}}});print(json.dumps({'entities':len(E),'relationships':len(R),'claims':len(C),'depth_claims':sum(1 for c in C if c['id'].startswith('CLM-KM-DEPTH')),'medinas':len([e for e in E if e['entity_type']=='quarter']),'sources':len(S)}))
if __name__=='__main__':main()
