#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/qatar';F=I/'fixtures/municipalities_census_2020.json';O=I/'fixtures/official_scope_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';ASOF='2020-12-31';SNAP='SNP-QA-PRODUCTION-20260816';PSA='SRC-QA-PSA-CENSUS-MUNICIPALITIES-2020';QNMP='SRC-QA-QNMP-EIGHT-MUNICIPALITIES-2026';WHC='SRC-UNESCO-WHC-QA-1402';GL='Qatar government statistical publication; factual extraction with attribution; reuse terms not stated';WL='CC BY-SA 3.0 IGO for property descriptions'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,lang,loc,lic,fixture,note):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':lic,'language':lang,'country_codes':['QA'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(fixture.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+' Publication date unavailable.'}
def main():
 f=L(F);o=L(O);sm=L(M)
 for r in sm['records']:
  p=ROOT/r['path'];b=p.read_bytes();assert len(b)==r['bytes'] and hashlib.sha256(b).hexdigest()==r['sha256']
 assert len(f['records'])==8 and sum(r['population'] for r in f['records'])==f['total_population']==2846118 and o['world_heritage']['denominator']==1
 sources=[src(PSA,'Qatar Census 2020 — Population by Municipality','Planning and Statistics Authority','census',f['url'],'ar-en','eight municipality population rows; total at end December 2020',GL,F,'Checksum binds exact census rows.'),src(QNMP,'Municipality Spatial Development Plans — eight municipalities','Qatar National Master Plan / Ministry of Municipality','official_report',o['qnmp_url'],'en','statement and enumeration of each of the eight municipalities',GL,O,'Independent current eight-municipality cross-check.'),src(WHC,'Al Zubarah Archaeological Site','UNESCO World Heritage Centre','institutional_page',o['unesco_url'],'ar-en','property 1402; cultural; inscribed 2013',WL,O,'Checksum binds exact property selection.')]
 for r in sources:write_json(ROOT/'data/sources'/f"{r['id']}.json",r)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'QA','sources':sources})
 toks={'الدوحة':'DOHA','الريان':'AL-RAYYAN','الوكرة':'AL-WAKRA','أم صلال':'UMM-SLAL','الخور والذخيرة':'AL-KHOR-AL-THAKHIRA','الشمال':'AL-SHAMAL','الظعاين':'AL-DAAYEN','الشحانية':'AL-SHEEHANIYA'};E=[];A=[];R=[];C=[]
 for x in f['records']:
  eid='ENT-QA-MUNICIPALITY-'+toks[x['name_ar']];loc=f"Census 2020 municipality row: {x['name_ar']} / {x['name_en']}; population={x['population']}"
  E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'QA','canonical_name':x['name_ar'],'canonical_name_language':'ar','entity_type':'qa_municipality','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':PSA,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Municipality, not city/zone/block/fareej; no centroid invented.','verification_status':'source_verified','confidence':'high'})
  A.append({'id':record_id('ALS-QA',eid,x['name_en']),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':x['name_en'],'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':PSA,'source_locator':loc,'valid_from':None,'valid_to':None})
  R.append({'id':record_id('REL-QA',eid,'ENT-QA-COUNTRY'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-QA-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':QNMP,'source_locator':'one of eight national municipality MSDPs','notes':'Municipality-country only.','verification_status':'source_verified','confidence':'high'})
  C.append({'id':record_id('CLM-QA','population',eid,ASOF),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'population','value':{'type':'integer','data':x['population']},'unit':'person','status':'verified','observed_at':ASOF,'valid_from':None,'valid_to':None,'source_id':PSA,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':'Census reference is end December 2020.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 w=o['world_heritage'];eid=w['entity_id'];loc='UNESCO property 1402; cultural; inscribed 2013';E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'QA','canonical_name':w['name_en'],'canonical_name_language':'en','entity_type':'archaeological_site','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':WHC,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'World Heritage property entity, not municipality/city.','verification_status':'source_verified','confidence':'high'});A.append({'id':record_id('ALS-QA',eid,w['name_ar']),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':w['name_ar'],'language':'ar','script':'Arab','kind':'official_variant','status':'current','source_id':WHC,'source_locator':loc,'valid_from':None,'valid_to':None});R.append({'id':record_id('REL-QA',eid,'associated_with'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-QA-COUNTRY','relationship_type':'associated_with','status':'current','valid_from':None,'valid_to':None,'source_id':WHC,'source_locator':loc,'notes':'Country association; no local parent guessed.','verification_status':'source_verified','confidence':'high'})
 for pred,val,unit in [('world_heritage_inscription_year',2013,'year'),('world_heritage_category','cultural',None)]:C.append({'id':record_id('CLM-QA',pred,eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':pred,'value':{'type':'integer' if isinstance(val,int) else 'string','data':val},'unit':unit,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':WHC,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':None,'verification_status':'source_verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 ids={r['id'] for r in E}|{'ENT-QA-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='QA' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-QA-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-QA-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,dt,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'QA','layer':l,'definition':note,'value':n,'as_of':dt,'status':'official','source_id':s,'source_locator':note,'license':lic,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':dt}
 def c(i,l,did,n,s,lic,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'QA','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':lic,'coverage_percentage':100.0,'exclusion_reasons':[]}
 ds=[d('DEN-QA-MUNICIPALITIES-2020','qa_municipality',8,ASOF,PSA,GL,'All eight Census 2020 municipalities, independently cross-checked by QNMP.'),d('DEN-QA-WHC-20260816','world_heritage_property',1,DATE,WHC,WL,'Al Zubarah, property 1402.')];vs=[c('COV-QA-MUNICIPALITIES-2020','qa_municipality','DEN-QA-MUNICIPALITIES-2020',8,PSA,GL,'Eight matched municipalities; zones/blocks excluded.'),c('COV-QA-WHC-20260816','world_heritage_property','DEN-QA-WHC-20260816',1,WHC,WL,'One matched inscribed property.')];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='QA' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='QA' and r.get('layer')!='country_scope',vs)
 snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Qatar production — eight municipalities and Al Zubarah','captured_at':DATE,'source_id':PSA,'scope':'Eight Census 2020 municipalities and one World Heritage property','method':'Checksum-bound official fixtures.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Zones, blocks, cities, fareej, broad culture and dialect remain unclosed.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-QA-'),[snap])
 m=L(ROOT/'manifests/QA.yml');m.update({'status':'pilot_migrated','official_authority':{'name':'Planning and Statistics Authority / Ministry of Municipality','source_ids':[PSA,QNMP],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-QA-COUNTRY-SCOPE','COV-QA-MUNICIPALITIES-2020','COV-QA-WHC-20260816'],'caveats':['Municipality is not city, zone, block, district, or fareej.','Historical ten-municipality topology is not current.','No lower or broad cultural denominator asserted.'],'next_action':'Maintain eight municipalities; add zones only with current official topology/denominator.'})
 for q in m['hierarchy']:
  if q['entity_type']=='qa_municipality':q.update({'source_ids':[PSA,QNMP],'verification_status':'verified','authority_name':'Planning and Statistics Authority / Ministry of Municipality','denominator':8,'denominator_id':'DEN-QA-MUNICIPALITIES-2020','coverage_record_id':'COV-QA-MUNICIPALITIES-2020','snapshot_date':ASOF,'license':GL,'scope_status':'closed','notes':'Eight current municipalities.','special_cases':['Spelling variants are aliases.']})
  elif q['entity_type'] in {'qa_zone','qa_district'}:q.update({'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'No accepted current denominator/topology.','special_cases':['Do not infer from historical topology.']})
 m['pilot_layers']=[{'layer':'qa_municipality','entity_types':['qa_municipality'],'local_names':['بلدية'],'authority_name':'PSA / Ministry of Municipality','denominator':8,'denominator_id':'DEN-QA-MUNICIPALITIES-2020','coverage_record_id':'COV-QA-MUNICIPALITIES-2020','snapshot_date':ASOF,'source_ids':[PSA,QNMP],'license':GL,'scope_status':'closed','notes':'Eight municipalities.','special_cases':[]},{'layer':'world_heritage_property','entity_types':['archaeological_site'],'local_names':['موقع تراث عالمي'],'authority_name':'UNESCO','denominator':1,'denominator_id':'DEN-QA-WHC-20260816','coverage_record_id':'COV-QA-WHC-20260816','snapshot_date':DATE,'source_ids':[WHC],'license':WL,'scope_status':'closed','notes':'Al Zubarah only.','special_cases':[]}];write_json(ROOT/'manifests/QA.yml',m);write_json(ROOT/'data/cultural/qatar_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'QA','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented','claims':2,'denominator':1},'food':{'status':'not_documented_in_cycle','claims':0},'dress':{'status':'not_documented_in_cycle','claims':0},'custom':{'status':'not_documented_in_cycle','claims':0},'dialect':{'status':'not_documented_in_cycle','claims':0}}});print(json.dumps({'entities':9,'aliases':9,'relationships':9,'claims':10,'sources':3}))
if __name__=='__main__':main()
