#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/djibouti';F=I/'fixtures/topology_2024.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';ASOF='2024-05-20';SNAP='SNP-DJ-PRODUCTION-20260816';LIC='Official Djibouti public material; factual extraction with attribution; reuse terms not stated'
SREG='SRC-DJ-PRESIDENCY-REGIONS-2026';SLAW='SRC-DJ-LAW-122-CITY-2005';SCEN='SRC-DJ-INSTAD-RGPH3-2024';SSUB='SRC-DJ-DECENTRALISATION-ROADMAP-2020';SINT='SRC-DJ-INTERIOR-PREFECTURES-2026'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'fr','country_codes':['DJ'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['regions'])==5 and sum(len(r['subprefectures']) for r in f['regions'])==13 and len(f['city']['communes'])==3 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(SREG,'Régions de la République de Djibouti','Présidence de la République','official_register',f['sources']['regions'],'five decentralized regions and special Djibouti City','Five regions explicitly separate from special-status city.'),src(SLAW,'Loi 122 — Statut de la Ville de Djibouti','Journal officiel / République de Djibouti','law',f['sources']['city_law'],'Article 2 three communes and special city status','Exact commune topology.',pub='2005-11-01'),src(SCEN,'RGPH-3 2024 provisional regional results','INSTAD','census',f['sources']['census'],'Table 1 population by six region/statistical scopes at 20 May 2024','Five regions plus Djibouti-Ville reconcile to national total.'),src(SSUB,'Feuille de route de la décentralisation','Ministère délégué chargé de la décentralisation','official_report',f['sources']['subprefectures'],'Table 3 regions and thirteen sub-prefectures','Sub-prefecture enumeration; not communes.'),src(SINT,'Administration territoriale — Préfectures','Ministère de l’Intérieur','official_register','https://interieur.gouv.dj/service/administration-territoriale-2/','Djibouti-Ville and five regional prefectures','Current state territorial-administration cross-check.')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'DJ','sources':S});E=[];R=[];C=[]
 def ent(i,n,t,s,l,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DJ','canonical_name':n,'canonical_name_language':'fr','entity_type':t,'status':'current','valid_from':None,'valid_to':None,'canonical_source_id':s,'source_locator':l,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'source_verified','confidence':'high'}
 def rel(ch,pa,kind,s,l):return {'id':record_id('REL-DJ',ch,pa),'schema_version':SCHEMA_VERSION,'child_id':ch,'parent_id':pa,'relationship_type':kind,'status':'current','valid_from':None,'valid_to':None,'source_id':s,'source_locator':l,'notes':'Special-capital and regional paths remain separate.','verification_status':'source_verified','confidence':'high'}
 def cl(e,pop,l):return {'id':record_id('CLM-DJ','population',e,ASOF),'schema_version':SCHEMA_VERSION,'subject_id':e,'predicate':'population','value':{'type':'integer','data':pop},'unit':'person','status':'reported','observed_at':ASOF,'valid_from':None,'valid_to':None,'source_id':SCEN,'second_source_id':None,'source_locator':l,'sensitivity':'ordinary','notes':'Provisional RGPH-3 result at end of collection.','verification_status':'source_verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None}
 for g in f['regions']:
  gid='ENT-DJ-REGION-'+g['token'];loc=f"Presidency region {g['name_fr']}; RGPH-3 population {g['population']}";E.append(ent(gid,g['name_fr'],'dj_region',SREG,loc,'Decentralized regional collectivity, not Djibouti City.'));R.append(rel(gid,'ENT-DJ-COUNTRY','administrative_parent',SREG,loc));C.append(cl(gid,g['population'],loc))
  for q in g['subprefectures']:
   sid='ENT-DJ-SUBPREFECTURE-'+q['token'];sl=f"Roadmap Table 3: {q['name_fr']} under {g['name_fr']}";E.append(ent(sid,q['name_fr'],'dj_subprefecture',SSUB,sl,'State sub-prefecture, not decentralized commune.'));R.append(rel(sid,gid,'administrative_parent',SSUB,sl))
 city='ENT-DJ-DJIBOUTI-CITY';E.append(ent(city,'Djibouti-Ville','djibouti_city',SLAW,'Law 122 special-status city','Special territorial collectivity parallel to five regions.'));R.append(rel(city,'ENT-DJ-COUNTRY','administrative_parent',SLAW,'Law 122'));C.append(cl(city,f['city_population'],'RGPH-3 Djibouti-Ville row'))
 for q in f['city']['communes']:
  cid='ENT-DJ-COMMUNE-'+q['token'];loc=f"Law 122 Article 2: commune {q['name_fr']}";E.append(ent(cid,q['name_fr'],'dj_commune',SLAW,loc,'Commune within special-status Djibouti City.'));R.append(rel(cid,city,'administrative_parent',SLAW,loc))
 ids={x['id'] for x in E}|{'ENT-DJ-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='DJ' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-DJ-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-DJ-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DJ','layer':l,'definition':note,'value':n,'as_of':ASOF,'status':'official','source_id':s,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':ASOF}
 def v(i,l,did,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DJ','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('REGIONS','dj_region',5,SREG),('SPECIAL-CITY','djibouti_city',1,SLAW),('CITY-COMMUNES','dj_commune',3,SLAW),('SUBPREFECTURES','dj_subprefecture',13,SSUB)];ds=[d('DEN-DJ-'+a,l,n,s,f'Exact {n}-record {l} scope.') for a,l,n,s in specs];vs=[v('COV-DJ-'+a,l,'DEN-DJ-'+a,n,s,f'{n}/{n} matched; topology-specific scope.') for a,l,n,s in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='DJ' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='DJ' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Djibouti special-capital and regional topology','captured_at':DATE,'source_id':SREG,'scope':'Five regions, special city, three city communes, thirteen sub-prefectures','method':'Checksum-bound official legal/statistical reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Arrondissements/zones and broad culture/dialect remain unclosed.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-DJ-'),[snap])
 man=L(ROOT/'manifests/DJ.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Présidence / Ministère de l’Intérieur / INSTAD','source_ids':[SREG,SLAW,SCEN,SINT],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-DJ-COUNTRY-SCOPE',*[f'COV-DJ-{a}' for a,_,_,_ in specs]],'caveats':['Djibouti-Ville is parallel to five regions.','Communes belong to special city; sub-prefectures belong to regions.','No arrondissement/zone denominator asserted.'],'next_action':'Maintain separate topology profiles; expand only from current legal enumerations.'})
 vals={'dj_region':(5,'REGIONS',SREG),'djibouti_city':(1,'SPECIAL-CITY',SLAW),'dj_commune':(3,'CITY-COMMUNES',SLAW),'dj_subprefecture':(13,'SUBPREFECTURES',SSUB)}
 for q in man['hierarchy']:
  if q['entity_type'] in vals:
   n,a,s=vals[q['entity_type']];q.update({'source_ids':[s],'verification_status':'verified','authority_name':'République de Djibouti','denominator':n,'denominator_id':'DEN-DJ-'+a,'coverage_record_id':'COV-DJ-'+a,'snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'Topology-specific closed scope.','special_cases':['Do not merge special-city and regional paths.']})
 man['pilot_layers']=[{'layer':l,'entity_types':[l],'local_names':['collectivité'],'authority_name':'République de Djibouti','denominator':n,'denominator_id':'DEN-DJ-'+a,'coverage_record_id':'COV-DJ-'+a,'snapshot_date':ASOF,'source_ids':[s],'license':LIC,'scope_status':'closed','notes':'Separate topology scope.','special_cases':[]} for a,l,n,s in specs];write_json(ROOT/'manifests/DJ.yml',man);write_json(ROOT/'data/cultural/djibouti_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'DJ','snapshot_date':DATE,'domains':{'world_heritage':{'status':'documented_zero_inscribed','denominator':0,'tentative_list_sites':10},'dialect':{'status':'not_documented_in_cycle','claims':0}},'notes':'Administrative micro pilot; zero inscribed is not cultural absence.'});print(json.dumps({'entities':22,'relationships':22,'claims':6,'sources':5}))
if __name__=='__main__':main()
