#!/usr/bin/env python3
import hashlib,json
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id,entity_id,norm_name
I=ROOT/'data/imports/yemen'; F=I/'fixtures/first_level_2026.json'; D=I/'fixtures/districts_2026.json'; M=I/'snapshot_manifest.json'; DATE='2026-08-17'; SNAP='SNP-YE-PRODUCTION-20260817'
CSO='SRC-YE-CSO-ADMIN-DEFINITION-LEGACY'; NIC='SRC-YE-NIC-GOVERNORATES-LEGACY'; LAW='SRC-YE-LAW-31-SOCOTRA-REPORT-2013'; MIR='SRC-YE-NIC-DISTRICT-CATALOGUE-MIRROR'; CEN='SRC-YE-CENSUS-2004-LEGACY-FRAME'
LIC='Factual extraction with attribution; publisher reuse terms not stated'
def L(p): return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a): write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def source(i,title,publisher,typ,url,locator,notes,tier='A',pub=None):
 return {'id':i,'schema_version':SCHEMA_VERSION,'title':title,'publisher':publisher,'source_type':typ,'url':url,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'ar','country_codes':['YE'],'locator':locator,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':tier,'notes':notes+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F); m=L(M); fd=L(D); assert len(f['units'])==22 and sum(x['kind']=='governorate' for x in f['units'])==21 and sum(x['kind']=='capital_municipality' for x in f['units'])==1
 rec={r['path']:r['sha256'] for r in m['records']}
 assert hashlib.sha256(F.read_bytes()).hexdigest()==rec['fixtures/first_level_2026.json']
 assert hashlib.sha256(D.read_bytes()).hexdigest()==rec['fixtures/districts_2026.json']
 assert sum(len(g['districts']) for g in fd['governorates'])==333 and len(fd['governorates'])==22
 S=[source(CSO,'Administrative divisions definition: 20 governorates plus Capital Municipality','Central Statistical Organization Yemen','official_report',f['sources']['cso_legacy'],'Administrative divisions, item 1-A','Official legacy frame; explicitly predates Socotra Governorate.'),source(NIC,'Governorates of the Republic — enumerated legacy catalogue','National Information Center Yemen','official_register',f['sources']['nic_legacy_list'],'Governorates page: 21 units including Amanat Al Asimah','Official enumeration of the legacy 20-governorate-plus-capital frame.'),source(LAW,'Report of Law 31/2013 establishing Socotra Archipelago Governorate','Yafa News, reporting the issued Republic of Yemen law','institutional_page',f['sources']['socotra_law_report'],'18 December 2013; title and Article 2 extracts','Contemporaneous verbatim report identifies Law 31/2013, creation date, capital Hadibo, territory, and two districts. Complete official gazette text was not retrievable; effective-clause wording is not asserted.',tier='B',pub='2013-12-18'),source(MIR,'District catalogue of the Republic of Yemen — encyclopedic mirror of the NIC frame','Marefa encyclopedic mirror citing the National Information Center','institutional_page',fd['sources']['nic_mirror'],'Per-governorate district lists; national total 333 cited to the CSO administrative-definitions page','Encyclopedic mirror used because the NIC origin is not directly retrievable; district identities from this source carry probable status pending an atomic official coded register.',tier='C'),source(CEN,'Census 2004 administrative frame — archived CSO administrative definitions','Central Statistical Organization Yemen via Internet Archive','archive',fd['sources']['census_2004_frame'],'Archived capture, 30 September 2018, of the CSO administrative divisions page','Archived official page anchoring the 333-district national frame and the census-2004 district universe.',tier='B',pub='2018-09-30')]
 for s in S: write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'YE','sources':S})
 E=[];R=[];C=[]
 for q in f['units']:
  eid='ENT-YE-'+('CAPITAL-MUNICIPALITY' if q['kind']=='capital_municipality' else 'GOVERNORATE')+'-'+q['code']; sid=LAW if q['code']=='22' else NIC
  et='ye_capital_municipality' if q['kind']=='capital_municipality' else 'ye_governorate'; loc=('Law 31/2013, issued 18 December 2013, Article 2 extract' if q['code']=='22' else f"Governorates catalogue entry: {q['name_ar']}")
  E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'YE','canonical_name':q['name_ar'],'canonical_name_language':'ar','entity_type':et,'status':'current','valid_from':q['valid_from'],'valid_to':None,'canonical_source_id':sid,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Current legal/statistical first-level identity reconstructed from the official legacy frame plus Law 31/2013; no effective-control, destruction, displacement, or dispute inference.','verification_status':'verified','confidence':'high' if q['code']!='22' else 'medium'})
  R.append({'id':record_id('REL-YE',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-YE-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':q['valid_from'],'valid_to':None,'source_id':sid,'source_locator':loc,'notes':'Legal/statistical parent only; not an effective-control assertion.','verification_status':'verified','confidence':'high' if q['code']!='22' else 'medium'})
  C.append({'id':record_id('CLM-YE','first-level-kind',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':q['kind']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':q['valid_from'],'valid_to':None,'source_id':sid,'second_source_id':CSO if q['code']!='22' else None,'source_locator':loc,'sensitivity':'ordinary','notes':'Amanat Al Asimah remains a parallel capital-municipality type, never a governorate alias.','verification_status':'verified','confidence':'high' if q['code']!='22' else 'medium','classification':'official','published':True,'second_source_locator':'20 governorates plus Capital Municipality definition' if q['code']!='22' else None,'lexical_context':None})
 soc='ENT-YE-GOVERNORATE-22'; C.append({'id':record_id('CLM-YE','socotra-law-31'),'schema_version':SCHEMA_VERSION,'subject_id':soc,'predicate':'establishment_instrument','value':{'type':'json','data':{'instrument_type':'law','law_number':31,'year':2013,'issuance_date':'2013-12-18','capital':'حديبو','district_count':2,'effective_clause_verified':False}},'unit':None,'status':'verified','observed_at':'2013-12-18','valid_from':'2013-12-18','valid_to':None,'source_id':LAW,'second_source_id':None,'source_locator':'Report title and Article 2 extract, 18 December 2013','sensitivity':'ordinary','notes':'The establishment and issuance date are supported. The complete official-gazette text/effective-clause wording remains unavailable and is not fabricated.','verification_status':'verified','confidence':'medium','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 # District layer (Maximum Arabic Knowledge Coverage cycle): attested identities, probable status.
 code2eid={q['code']:('ENT-YE-'+('CAPITAL-MUNICIPALITY' if q['kind']=='capital_municipality' else 'GOVERNORATE')+'-'+q['code']) for q in f['units']}
 for g in fd['governorates']:
  peid=code2eid[g['code']]
  for name in g['districts']:
   did=entity_id('YE','ye_district',name,peid); loc=f"District catalogue, governorate {g['name_ar']}: {name}"
   E.append({'id':did,'schema_version':SCHEMA_VERSION,'country_code':'YE','canonical_name':name,'canonical_name_language':'ar','entity_type':'ye_district','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':MIR,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Attested district identity from the NIC catalogue mirror anchored to the archived CSO 333-district frame; probable pending an atomic official coded register. No control, damage, or displacement inference.','verification_status':'probable','confidence':'medium'})
   R.append({'id':record_id('REL-YE',did,peid),'schema_version':SCHEMA_VERSION,'child_id':did,'parent_id':peid,'relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':MIR,'source_locator':loc,'notes':'Catalogue parentage; legal/statistical only.','verification_status':'probable','confidence':'medium'})
 ids={x['id'] for x in E}|{'ENT-YE-COUNTRY'}
 rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='YE' and r.get('entity_type')!='country',E); rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-YE-') and r.get('child_id')!='ENT-YE-COUNTRY',R); rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 # No unsourced English aliases are emitted; preserve the ISO country alias only.
 rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-YE-') and r.get('entity_id')!='ENT-YE-COUNTRY',[])
 def d(i,l,n,s,note,status='official',missing=None): return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'YE','layer':l,'definition':note,'value':n,'as_of':DATE,'status':status,'source_id':s,'source_locator':note,'license':LIC,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,s,note): return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'YE','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('FIRST-LEVEL','ye_first_level_current',22,LAW,'Reconciled legal universe: legacy 21 plus Socotra under Law 31/2013.'),('GOVERNORATES','ye_governorate_current',21,LAW,'Twenty legacy governorates plus Socotra; excludes Amanat Al Asimah.'),('CAPITAL-MUNICIPALITY','ye_capital_municipality_current',1,NIC,'Amanat Al Asimah is one parallel first-level capital municipality.'),('LEGACY-FIRST-LEVEL','ye_first_level_legacy_pre_socotra',21,CSO,'Historical source frame: 20 governorates plus Capital Municipality; Socotra absent.'),('DISTRICTS','ye_district_current',333,CEN,'National 333-district frame from the archived official CSO administrative-definitions page; identities attested via the NIC catalogue mirror and carry probable status pending an atomic official coded register.')]
 ds=[d('DEN-YE-'+a,l,n,s,note) for a,l,n,s,note in specs]; vs=[v('COV-YE-'+a,l,'DEN-YE-'+a,n,s,note) for a,l,n,s,note in specs]
 rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='YE' and r.get('layer')!='country_scope',ds); rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='YE' and r.get('layer')!='country_scope',vs)
 snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Yemen legal first-level reconciliation','captured_at':DATE,'source_id':LAW,'scope':'21 governorates plus Amanat Al Asimah; 22 first-level legal/statistical identities','method':'Checksum-bound reconciliation of official legacy CSO/NIC frame with Law 31/2013 Socotra establishment report.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Official-gazette full text/effective clause, districts, uzlas, and conflict overlays are deferred.'}; rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-YE-PRODUCTION-'),[snap])
 man=L(ROOT/'manifests/YE.yml'); man.update({'status':'pilot_migrated','official_authority':{'name':'Central Statistical Organization / National Information Center / Republic of Yemen Law 31/2013','source_ids':[CSO,NIC,LAW],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-YE-COUNTRY-SCOPE',*[f'COV-YE-{a}' for a,_,_,_,_ in specs]],'caveats':['Current legal first-level universe is reconstructed from a legacy official 20-governorate-plus-capital frame and Law 31/2013 adding Socotra.','The complete official-gazette copy and its effective-clause wording were not retrievable; no wording is inferred.','Legal identity is not effective control, destruction, displacement, or dispute status.','District identities are attested from a mirror of the NIC catalogue anchored to the archived official 333-district frame; they carry probable status, not verified, until an atomic official coded register is reconciled.'],'next_action':'Deepen the district layer toward verified status via an atomic official coded register; collect populated places, lanes, and classified local knowledge under the Maximum Arabic Knowledge Coverage policy; add conflict overlays only from dated authoritative sources.'})
 for x in man['hierarchy']:
  if x['entity_type']=='ye_governorate': x.update({'level':1,'source_ids':[NIC,LAW],'verification_status':'verified','authority_name':'CSO / NIC / Law 31/2013','denominator':21,'denominator_id':'DEN-YE-GOVERNORATES','coverage_record_id':'COV-YE-GOVERNORATES','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'21 legal governorates including Socotra.','special_cases':['Socotra established by Law 31/2013; full effective-clause text unavailable.']})
  elif x['entity_type']=='ye_capital_municipality': x.update({'level':1,'source_ids':[CSO,NIC],'verification_status':'verified','authority_name':'CSO / NIC','denominator':1,'denominator_id':'DEN-YE-CAPITAL-MUNICIPALITY','coverage_record_id':'COV-YE-CAPITAL-MUNICIPALITY','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Parallel first-level unit, not a governorate alias.','special_cases':['Amanat Al Asimah.']})
  elif x['entity_type']=='ye_district': x.update({'level':2,'verification_status':'partial','authority_name':'CSO archived frame / NIC catalogue mirror','denominator':333,'denominator_id':'DEN-YE-DISTRICTS','coverage_record_id':'COV-YE-DISTRICTS','snapshot_date':DATE,'license':LIC,'scope_status':'bounded','notes':'333 attested district identities; probable pending an atomic official coded register.','special_cases':['Identities from a tier-C mirror anchored to the archived official frame; no coded register yet.']})
  elif x['entity_type']=='ye_uzla': x.update({'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'Current authoritative coded register not reconciled.','special_cases':['No uzla records emitted.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['ye_governorate','ye_capital_municipality'],'local_names':['first-level'],'authority_name':'CSO / NIC / Law 31/2013','denominator':n,'denominator_id':'DEN-YE-'+a,'coverage_record_id':'COV-YE-'+a,'snapshot_date':DATE,'source_ids':[s],'license':LIC,'scope_status':'closed','notes':note,'special_cases':[]} for a,l,n,s,note in specs]; write_json(ROOT/'manifests/YE.yml',man)
 write_json(ROOT/'data/cultural/yemen_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'YE','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_full_pilot_stage1'},'dialect':{'status':'not_documented_in_cycle','claims':0}}})
 print(json.dumps({'entities':355,'relationships':355,'claims':23,'sources':5,'denominators':5,'coverage':5}))
if __name__=='__main__': main()
