#!/usr/bin/env python3
import json,hashlib,re
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/algeria';F=I/'fixtures/wilaya_transition.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';CURRENT='2021-03-29';FUTURE='2027-01-01';SNAP='SNP-DZ-PRODUCTION-20260816';ONS='SRC-DZ-ONS-CGN-2021';MIC='SRC-DZ-INTERIOR-58-WILAYAS';MIF='SRC-DZ-INTERIOR-69-TRANSITION-2025';LIC='Official Algeria legal/statistical material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def tok(s):return re.sub('[^A-Z0-9]+','-',s.upper().replace('É','E').replace('È','E').replace('Ï','I').replace('Î','I').replace('Â','A').replace('’','-')).strip('-')
def src(i,t,p,ty,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'ar-fr','country_codes':['DZ'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['current_wilayas'])==58 and len(f['future_promotions'])==11 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(ONS,'Code Géographique National 2021','Office National des Statistiques','official_dataset',f['sources']['ons'],'58 wilayas and 1541 communes; bilingual geographic codes','Current code universe.',pub=CURRENT),src(MIC,'Installation des nouvelles wilayas du Sud','Ministère de l’Intérieur','official_report',f['sources']['interior_current'],'Law 19-12 and operational current 58-wilaya structure','Ten southern additions are already current.'),src(MIF,'Projet de loi — 69 wilayas à compter de 2027','Ministère de l’Intérieur','law',f['sources']['interior_future'],'eleven named promotions; full prerogatives 1 January 2027','Future transition source.',pub='2025-12-18')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'DZ','sources':S});E=[];R=[];A=[]
 def ent(i,n,status,vf,s,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DZ','canonical_name':n,'canonical_name_language':'fr','entity_type':'dz_wilaya','status':status,'valid_from':vf,'valid_to':None,'canonical_source_id':s,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'verified' if status=='current' else 'source_verified','confidence':'high'}
 def rel(i,status,vf,s,loc):return {'id':record_id('REL-DZ',i,'country'),'schema_version':SCHEMA_VERSION,'child_id':i,'parent_id':'ENT-DZ-COUNTRY','relationship_type':'administrative_parent','status':status,'valid_from':vf,'valid_to':None,'source_id':s,'source_locator':loc,'notes':'Future status does not enter current denominator.','verification_status':'verified' if status=='current' else 'source_verified','confidence':'high'}
 for q in f['current_wilayas']:
  eid='ENT-DZ-WILAYA-'+q['code'];loc=f"CGN 2021 wilaya code {q['code']}: {q['name_fr']}";E.append(ent(eid,q['name_fr'],'current',None,ONS,loc,'Current wilaya in 58-code universe.'));R.append(rel(eid,'current',None,ONS,loc))
 for q in f['future_promotions']:
  eid='ENT-DZ-WILAYA-FUTURE-'+tok(q['name_fr']);loc=f"2025 bill: {q['name_fr']} promoted from {q['current_parent_wilaya_fr']}; full prerogatives 2027-01-01";E.append(ent(eid,q['name_fr'],'proposed',FUTURE,MIF,loc,'Future wilaya; not current before effective date.'));R.append(rel(eid,'proposed',FUTURE,MIF,loc))
 ids={x['id'] for x in E}|{'ENT-DZ-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='DZ' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-DZ-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-DZ-'),R)
 claims=[]
 for key,val,obs,s,loc in [('current_wilaya_count',58,CURRENT,ONS,'CGN 2021 summary'),('future_wilaya_count',69,FUTURE,MIF,'2025 bill and 2027 effective date'),('commune_count',1541,CURRENT,ONS,'CGN 2021 unchanged commune total')]:claims.append({'id':record_id('CLM-DZ',key),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-DZ-COUNTRY','predicate':key,'value':{'type':'integer','data':val},'unit':'administrative_unit','status':'reported' if obs==FUTURE else 'verified','observed_at':obs,'valid_from':obs if obs==FUTURE else None,'valid_to':None,'source_id':s,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':'Future count is not current coverage.' if obs==FUTURE else None,'verification_status':'source_verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,claims)
 def d(i,l,n,dt,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DZ','layer':l,'definition':note,'value':n,'as_of':dt,'status':'official','source_id':s,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':dt}
 def v(i,l,did,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'DZ','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 ds=[d('DEN-DZ-WILAYAS-CURRENT-2021','dz_wilaya_current',58,CURRENT,ONS,'Current 58-wilaya denominator.'),d('DEN-DZ-WILAYAS-FUTURE-2027','dz_wilaya_future',69,FUTURE,MIF,'Future 69-wilaya planned denominator.')];vs=[v('COV-DZ-WILAYAS-CURRENT-2021','dz_wilaya_current','DEN-DZ-WILAYAS-CURRENT-2021',58,ONS,'58 current identities; proposed excluded.'),v('COV-DZ-WILAYAS-FUTURE-2027','dz_wilaya_future','DEN-DZ-WILAYAS-FUTURE-2027',69,MIF,'58 retained plus 11 proposed identities; this is planning coverage, not current status.')];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='DZ' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='DZ' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Algeria current and 2027 wilaya transition','captured_at':DATE,'source_id':ONS,'scope':'58 current and 11 proposed future wilayas','method':'Checksum-bound current/future separation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'1541 communes known but deferred; future wilayas not current.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-DZ-'),[snap])
 man=L(ROOT/'manifests/DZ.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Ministère de l’Intérieur / ONS','source_ids':[ONS,MIC,MIF],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-DZ-COUNTRY-SCOPE','COV-DZ-WILAYAS-CURRENT-2021','COV-DZ-WILAYAS-FUTURE-2027'],'caveats':['58 current wilayas; 11 proposed cannot become current before 2027-01-01.','1541 communes deferred.','Daïras are state administrative extensions, not wilayas/communes.'],'next_action':'Maintain temporal separation; import communes only from current CGN.'})
 for q in man['hierarchy']:
  if q['entity_type']=='dz_wilaya':q.update({'source_ids':[ONS,MIF],'verification_status':'verified','authority_name':'Ministry / ONS','denominator':58,'denominator_id':'DEN-DZ-WILAYAS-CURRENT-2021','coverage_record_id':'COV-DZ-WILAYAS-CURRENT-2021','snapshot_date':CURRENT,'license':LIC,'scope_status':'closed','notes':'Current layer only.','special_cases':['11 proposed records effective 2027 are outside current denominator.']})
  elif q['entity_type'] in {'dz_daira','dz_commune'}:q.update({'verification_status':'pending','authority_name':'Ministry / ONS','denominator':1541 if q['entity_type']=='dz_commune' else None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'open' if q['entity_type']=='dz_commune' else 'unavailable','notes':'Record-level import deferred.','special_cases':[]})
 man['pilot_layers']=[{'layer':'dz_wilaya_current','entity_types':['dz_wilaya'],'local_names':['wilaya'],'authority_name':'Ministry / ONS','denominator':58,'denominator_id':'DEN-DZ-WILAYAS-CURRENT-2021','coverage_record_id':'COV-DZ-WILAYAS-CURRENT-2021','snapshot_date':CURRENT,'source_ids':[ONS,MIC],'license':LIC,'scope_status':'closed','notes':'Current status only.','special_cases':[]},{'layer':'dz_wilaya_future','entity_types':['dz_wilaya'],'local_names':['future wilaya'],'authority_name':'Ministry','denominator':69,'denominator_id':'DEN-DZ-WILAYAS-FUTURE-2027','coverage_record_id':'COV-DZ-WILAYAS-FUTURE-2027','snapshot_date':FUTURE,'source_ids':[MIF],'license':LIC,'scope_status':'closed','notes':'Planning universe; not current.','special_cases':['11 proposed until 2027.']}];write_json(ROOT/'manifests/DZ.yml',man);write_json(ROOT/'data/cultural/algeria_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'DZ','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_micro_pilot'},'dialect':{'status':'not_documented_in_cycle','claims':0}}});print(json.dumps({'entities':69,'relationships':69,'claims':3,'sources':3}))
if __name__=='__main__':main()
