#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/egypt';F=I/'fixtures/governorate_profiles.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';ASOF='2021-01-01';SNAP='SNP-EG-PRODUCTION-20260816';CAP='SRC-EG-CAPMAS-27-GOVERNORATES-2021';MLD='SRC-EG-MLD-27-GOVERNORATES-2026';COD='SRC-EG-CAPMAS-GOVERNORATE-CODES';LIC='Official Egypt statistical/government material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':None,'retrieved_at':DATE,'license':LIC,'language':'ar-en','country_codes':['EG'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+' Publication date unavailable.'}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['governorates'])==27 and sum(x['profile']=='urban_only' for x in f['governorates'])==4 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(CAP,'Egypt Family Health Survey 2021 — administrative geography','CAPMAS','census',f['sources']['capmas'],'27 governorates; four urban-only and 23 urban/rural','Profile authority.'),src(MLD,'Ministry of Local Development — 27 governorates','Ministry of Local Development','official_register',f['sources']['mld'],'government mandate across 27 governorates','Current denominator cross-check.'),src(COD,'CAPMAS governorate code values','CAPMAS','official_dataset',f['sources']['capmas_codes'],'official numeric governorate categories','Code identity cross-check.')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'EG','sources':S});E=[];A=[];R=[];C=[]
 for q in f['governorates']:
  eid='ENT-EG-GOVERNORATE-'+q['code'];loc=f"CAPMAS governorate code {q['code']}: {q['name_ar']} / {q['name_en']}; profile={q['profile']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'EG','canonical_name':q['name_ar'],'canonical_name_language':'ar','entity_type':'eg_governorate','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':CAP,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':'Governorate profile does not create markaz/qism entities.','verification_status':'verified','confidence':'high'});A.append({'id':record_id('ALS-EG',eid,q['name_en']),'schema_version':SCHEMA_VERSION,'entity_id':eid,'name':q['name_en'],'language':'en','script':'Latn','kind':'official_variant','status':'current','source_id':CAP,'source_locator':loc,'valid_from':None,'valid_to':None});R.append({'id':record_id('REL-EG',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-EG-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':MLD,'source_locator':loc,'notes':'Lower rural/urban paths remain separate and unavailable.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-EG','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'administrative_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':ASOF,'valid_from':None,'valid_to':None,'source_id':CAP,'second_source_id':None,'source_locator':loc,'sensitivity':'ordinary','notes':'urban_only means no rural population in cited survey geography; it is not a city identity.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-EG-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='EG' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-EG-'),A);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-EG-'),R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'EG','layer':l,'definition':note,'value':n,'as_of':ASOF,'status':'official','source_id':CAP,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':ASOF}
 def v(i,l,did,n,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'EG','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':CAP,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('GOVERNORATES','eg_governorate',27),('URBAN-PROFILES','eg_governorate_urban_profile',4),('MIXED-PROFILES','eg_governorate_mixed_profile',23)];ds=[d('DEN-EG-'+a,l,n,f'Exact {l} profile denominator.') for a,l,n in specs];vs=[v('COV-EG-'+a,l,'DEN-EG-'+a,n,f'{n}/{n} matched profile records.') for a,l,n in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='EG' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='EG' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Egypt 27-governorate profile pilot','captured_at':DATE,'source_id':CAP,'scope':'27 governorates: four urban-only, 23 mixed urban/rural','method':'Checksum-bound CAPMAS/MLD profile reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Cairo/Giza selected for later lower-topology proof; no lower records imported.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-EG-'),[snap])
 man=L(ROOT/'manifests/EG.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'CAPMAS / Ministry of Local Development','source_ids':[CAP,MLD,COD],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-EG-COUNTRY-SCOPE',*[f'COV-EG-{a}' for a,_,_ in specs]],'caveats':['Governorate is not city.','Markaz/local-unit and qism/shiyakha paths are parallel.','No lower denominator accepted in this cycle.'],'next_action':'Maintain 27/profile closure; prove Cairo and Giza lower topology before national depth.'})
 for x in man['hierarchy']:
  if x['entity_type']=='eg_governorate':x.update({'source_ids':[CAP,MLD],'verification_status':'verified','authority_name':'CAPMAS / MLD','denominator':27,'denominator_id':'DEN-EG-GOVERNORATES','coverage_record_id':'COV-EG-GOVERNORATES','snapshot_date':ASOF,'license':LIC,'scope_status':'closed','notes':'27 governorates.','special_cases':['Four urban-only profiles.']})
  elif x['entity_type']!='country':x.update({'verification_status':'pending','authority_name':None,'denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'Lower topology not yet accepted.','special_cases':['Do not cross rural/urban paths.']})
 man['pilot_layers']=[{'layer':l,'entity_types':['eg_governorate'],'local_names':['محافظة'],'authority_name':'CAPMAS','denominator':n,'denominator_id':'DEN-EG-'+a,'coverage_record_id':'COV-EG-'+a,'snapshot_date':ASOF,'source_ids':[CAP,MLD],'license':LIC,'scope_status':'closed','notes':'Profile layer.','special_cases':[]} for a,l,n in specs];write_json(ROOT/'manifests/EG.yml',man);write_json(ROOT/'data/cultural/egypt_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'EG','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_full_pilot_stage1'},'dialect':{'status':'not_documented_in_cycle','claims':0}},'notes':'Administrative profile stage only.'});print(json.dumps({'entities':27,'aliases':27,'relationships':27,'claims':27,'sources':3}))
if __name__=='__main__':main()
