#!/usr/bin/env python3
import json,hashlib
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/lebanon';F=I/'fixtures/current_hierarchy.json';M=I/'snapshot_manifest.json';DATE='2026-08-16';LAWDATE='2017-09-07';SNAP='SNP-LB-PRODUCTION-20260816';CAS='SRC-LB-CAS-26-DISTRICTS-2019';MOIM='SRC-LB-MOIM-ADMINISTRATION-2026';LAW='SRC-LB-LAW-52-2017';LIC='Official Lebanon public/statistical material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,ty,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':ty,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'ar-en','country_codes':['LB'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);b=F.read_bytes();assert len(f['current_governorates'])==9 and sum(len(g['districts']) for g in f['current_governorates'])==26 and hashlib.sha256(b).hexdigest()==m['records'][0]['sha256']
 S=[src(CAS,'Lebanon District Statistics — LFHLCS 2018-2019','Central Administration of Statistics','census',f['sources']['cas'],'26 districts and eight-governorate survey frame','Historical survey topology; not current parent authority.'),src(MOIM,'Ministry oversight of governorates and districts','Ministry of Interior and Municipalities','official_register',f['sources']['moim'],'current oversight of governorates, districts, municipalities','Current administration cross-check.'),src(LAW,'Law 52/2017 — Keserwan-Jbeil Governorate','Lebanese Parliament / Official Gazette','law','https://www.lp.gov.lb/','Law 52, Official Gazette 7 September 2017; Keserwan and Jbeil','Current ninth-governorate transition.',pub=LAWDATE)]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'LB','sources':S});E=[];R=[];C=[]
 def ent(i,n,t,s,loc,note,vf=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'LB','canonical_name':n,'canonical_name_language':'en','entity_type':t,'status':'current','valid_from':vf,'valid_to':None,'canonical_source_id':s,'source_locator':loc,'legacy_ids':[],'coordinates':None,'notes':note,'verification_status':'verified','confidence':'high'}
 def rel(ch,pa,s,loc,vf=None):return {'id':record_id('REL-LB',ch,pa),'schema_version':SCHEMA_VERSION,'child_id':ch,'parent_id':pa,'relationship_type':'administrative_parent','status':'current','valid_from':vf,'valid_to':None,'source_id':s,'source_locator':loc,'notes':'Current legal parent only; survey-time parent preserved as Claim where changed.','verification_status':'verified','confidence':'high'}
 for g in f['current_governorates']:
  gid='ENT-LB-GOVERNORATE-'+g['token'];isnew=g['token']=='KESERWAN-JBEIL';loc=f"Current governorate {g['name_en']}; {len(g['districts'])} district records";E.append(ent(gid,g['name_en'],'lb_governorate',LAW if isnew else MOIM,loc,'Current governorate.',LAWDATE if isnew else None));R.append(rel(gid,'ENT-LB-COUNTRY',LAW if isnew else MOIM,loc,LAWDATE if isnew else None));C.append({'id':record_id('CLM-LB','district-count',gid),'schema_version':SCHEMA_VERSION,'subject_id':gid,'predicate':'district_count','value':{'type':'integer','data':len(g['districts'])},'unit':'district','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':MOIM,'second_source_id':CAS,'source_locator':loc,'sensitivity':'ordinary','notes':'Current parent count; CAS survey frame differs for moved districts.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'CAS 26-district report universe','lexical_context':None})
  for q in g['districts']:
   did='ENT-LB-DISTRICT-'+q['token'];moved=q['name_en'] in f['transition']['moved_districts'];dl=f"District {q['name_en']} current parent {g['name_en']}";E.append(ent(did,q['name_en'],'lb_district',LAW if moved else CAS,dl,'District current identity.',LAWDATE if moved else None));R.append(rel(did,gid,LAW if moved else CAS,dl,LAWDATE if moved else None))
   if moved:C.append({'id':record_id('CLM-LB','previous-parent',did),'schema_version':SCHEMA_VERSION,'subject_id':did,'predicate':'previous_governorate','value':{'type':'string','data':'Mount Lebanon'},'unit':None,'status':'historical','observed_at':'2019-01-01','valid_from':None,'valid_to':LAWDATE,'source_id':CAS,'second_source_id':LAW,'source_locator':'LFHLCS 2018-2019 survey frame under Mount Lebanon','sensitivity':'ordinary','notes':'Historical survey parent; current relation points only to Keserwan-Jbeil.','verification_status':'verified','confidence':'high','classification':'historical','published':True,'second_source_locator':'Law 52 current reassignment','lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-LB-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='LB' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-LB-'),[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-LB-'),R);C.extend([{'id':record_id('CLM-LB','current-governorates'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-LB-COUNTRY','predicate':'current_governorate_count','value':{'type':'integer','data':9},'unit':'governorate','status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':MOIM,'second_source_id':LAW,'source_locator':'current administrative frame','sensitivity':'ordinary','notes':None,'verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'Law 52 ninth governorate','lexical_context':None},{'id':record_id('CLM-LB','survey-governorates'),'schema_version':SCHEMA_VERSION,'subject_id':'ENT-LB-COUNTRY','predicate':'survey_governorate_count','value':{'type':'integer','data':8},'unit':'governorate','status':'historical','observed_at':'2019-01-01','valid_from':None,'valid_to':LAWDATE,'source_id':CAS,'second_source_id':LAW,'source_locator':'LFHLCS survey frame','sensitivity':'ordinary','notes':'Historical survey geography only.','verification_status':'verified','confidence':'high','classification':'historical','published':True,'second_source_locator':'Law 52 transition','lexical_context':None}]);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 def d(i,l,n,dt,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'LB','layer':l,'definition':note,'value':n,'as_of':dt,'status':'official','source_id':s,'source_locator':note,'license':LIC,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':dt}
 def v(i,l,did,n,s,note):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'LB','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':n,'unmatched':0,'excluded':0,'missing':0,'complete':True,'missing_reason':None,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':100.0,'exclusion_reasons':[]}
 specs=[('GOVERNORATES-CURRENT','lb_governorate',9,DATE,MOIM),('DISTRICTS-CURRENT','lb_district',26,DATE,MOIM),('GOVERNORATES-SURVEY-2019','lb_governorate_survey_frame',8,'2019-01-01',CAS)];ds=[d('DEN-LB-'+a,l,n,dt,s,f'Exact {l} denominator.') for a,l,n,dt,s in specs];vs=[v('COV-LB-'+a,l,'DEN-LB-'+a,n,s,f'{n}/{n} identities represented; survey layer is historical where applicable.') for a,l,n,dt,s in specs];rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='LB' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='LB' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Lebanon current 9-governorate / 26-district hierarchy','captured_at':DATE,'source_id':MOIM,'scope':'Current hierarchy plus historical CAS survey-frame claims','method':'Checksum-bound temporal reconciliation.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Municipalities deferred.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-LB-'),[snap])
 man=L(ROOT/'manifests/LB.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Ministry of Interior and Municipalities / CAS','source_ids':[MOIM,CAS,LAW],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-LB-COUNTRY-SCOPE',*[f'COV-LB-{a}' for a,_,_,_,_ in specs]],'caveats':['Current 9-governorate frame differs from CAS 8-governorate survey frame.','Keserwan/Jbeil current parent is Keserwan-Jbeil only.','Municipalities deferred.'],'next_action':'Maintain temporal parent claims; import municipalities only from current Ministry register.'})
 vals={'lb_governorate':(9,'GOVERNORATES-CURRENT'),'lb_district':(26,'DISTRICTS-CURRENT')}
 for x in man['hierarchy']:
  if x['entity_type'] in vals:
   n,a=vals[x['entity_type']];x.update({'source_ids':[MOIM,CAS,LAW],'verification_status':'verified','authority_name':'MOIM / CAS','denominator':n,'denominator_id':'DEN-LB-'+a,'coverage_record_id':'COV-LB-'+a,'snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Current hierarchy.','special_cases':['Historical survey parent kept as Claim.']})
  elif x['entity_type']=='lb_municipality':x.update({'verification_status':'pending','authority_name':'MOIM','denominator':None,'denominator_id':None,'coverage_record_id':None,'snapshot_date':None,'license':None,'scope_status':'unavailable','notes':'No current atomic national register accepted.','special_cases':[]})
 man['pilot_layers']=[{'layer':l,'entity_types':['lb_governorate' if 'governorate' in l else 'lb_district'],'local_names':['administrative unit'],'authority_name':'MOIM / CAS','denominator':n,'denominator_id':'DEN-LB-'+a,'coverage_record_id':'COV-LB-'+a,'snapshot_date':dt,'source_ids':[s,LAW],'license':LIC,'scope_status':'closed','notes':'Temporal frame explicit.','special_cases':[]} for a,l,n,dt,s in specs];write_json(ROOT/'manifests/LB.yml',man);write_json(ROOT/'data/cultural/lebanon_domain_status.json',{'schema_version':SCHEMA_VERSION,'country_code':'LB','snapshot_date':DATE,'domains':{'world_heritage':{'status':'not_imported_in_micro_pilot'},'dialect':{'status':'not_documented_in_cycle','claims':0}}});print(json.dumps({'entities':35,'relationships':35,'claims':13,'sources':3}))
if __name__=='__main__':main()
