#!/usr/bin/env python3
import hashlib,json
from model import ROOT,SCHEMA_VERSION,read_jsonl,write_jsonl,write_json,record_id
I=ROOT/'data/imports/somalia';F=I/'fixtures/federal_frames_2026.json';M=I/'snapshot_manifest.json';DATE='2026-08-17';SNAP='SNP-SO-PRODUCTION-20260817';MOP='SRC-SO-MOP-FMS-2026';MOI='SRC-SO-MOIFAR-NORTHEAST-2026';SONNA='SRC-SO-SONNA-NORTHEAST-DECLARATION-2026';SEN='SRC-SO-SENATE-CONSTITUENCY';OLD='SRC-SO-MPWR-FIVE-FMS-2025';LIC='Official Somalia federal material; factual extraction with attribution; reuse terms not stated'
def L(p):return json.loads(p.read_text(encoding='utf8'))
def rep(p,fn,a):write_jsonl(p,[r for r in read_jsonl(p) if not fn(r)]+a)
def src(i,t,p,typ,u,loc,note,pub=None):return {'id':i,'schema_version':SCHEMA_VERSION,'title':t,'publisher':p,'source_type':typ,'url':u,'archive_url':None,'publication_date':pub,'retrieved_at':DATE,'license':LIC,'language':'en','country_codes':['SO'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(F.read_bytes()).hexdigest(),'quality_tier':'A','notes':note+('' if pub else ' Publication date unavailable.')}
def main():
 f=L(F);m=L(M);assert len(f['federal_member_states'])==7 and len(f['parallel_units'])==1 and hashlib.sha256(F.read_bytes()).hexdigest()==next(r['sha256'] for r in m['records'] if r['path'].endswith('federal_frames_2026.json'))
 S=[src(MOP,'Federal Member States','Federal Government of Somalia, Ministry of Planning','official_register',f['sources']['mop'],'Seven named FMS plus Banadir Regional Administration','Authority-specific current federal planning frame; not a sovereignty or control adjudication.'),src(MOI,'Formal establishment of North Eastern State','Ministry of Interior, Federal Affairs and Reconciliation','official_report',f['sources']['moifar_ne'],'17 January 2026 inauguration and completion of formation','Records formal establishment of the new federal member state.',pub='2026-01-17'),src(SONNA,'President declares North East State a full Federal Member State','Somali National News Agency','official_report',f['sources']['sonna_ne'],'Presidential statement, 17 January 2026','Full-member declaration and equal federal status.',pub='2026-01-17'),src(SEN,'Senate constituency','Upper House of the Federal Parliament of Somalia','official_register',f['sources']['senate'],'Somaliland, Puntland, Jubaland, South West, Galmudug, Hirshabelle representation','Supports the FGS constitutional/representation narrative; does not resolve Somaliland de facto or sovereign status.'),src(OLD,'2025 project assessment: five Federal Member States','Federal Ministry of Public Works','official_report',f['sources']['older_five'],'Five FMS enumeration before North East completion; Somaliland treated separately','Temporal baseline for five standard operational FMS.',pub='2025-04-01')]
 for s in S:write_json(ROOT/'data/sources'/f"{s['id']}.json",s)
 write_json(I/'source_catalog.json',{'schema_version':SCHEMA_VERSION,'country_code':'SO','sources':S});E=[];R=[];C=[]
 for q in f['federal_member_states']:
  eid='ENT-SO-FMS-'+q['code'];is_sl=q['profile']=='fgs_federal_planning_narrative';status='claimed' if is_sl else 'current';sid=SONNA if q['profile']=='new_fms' else MOP;loc=f"Ministry of Planning FMS entry: {q['name']}";E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'SO','canonical_name':q['name'],'canonical_name_language':'en','entity_type':'so_federal_member_state','status':status,'valid_from':q['valid_from'],'valid_to':None,'canonical_source_id':sid,'source_locator':loc if sid==MOP else 'Presidential full-member declaration, 17 January 2026','legacy_ids':[],'coordinates':None,'notes':'Authority-specific FGS federal identity. This record does not adjudicate sovereignty, territorial claims, or effective control.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-SO',eid,'country'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':'ENT-SO-COUNTRY','relationship_type':'administrative_parent','status':status,'valid_from':q['valid_from'],'valid_to':None,'source_id':sid,'source_locator':loc,'notes':'FGS federal/planning relationship only; no territorial-control inference.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-SO','profile',eid),'schema_version':SCHEMA_VERSION,'subject_id':eid,'predicate':'federal_planning_profile','value':{'type':'string','data':q['profile']},'unit':None,'status':'verified','observed_at':DATE,'valid_from':q['valid_from'],'valid_to':None,'source_id':MOP if q['profile']!='new_fms' else MOI,'second_source_id':SEN if is_sl else (SONNA if q['profile']=='new_fms' else OLD),'source_locator':loc,'sensitivity':'sensitive' if is_sl or q['profile']=='new_fms' else 'ordinary','notes':'Classification is attributed to the cited FGS frame; competing claims/control remain separate.','verification_status':'verified','confidence':'high','classification':'disputed' if is_sl else 'official','published':True,'second_source_locator':'Senate representation narrative' if is_sl else ('Presidential declaration' if q['profile']=='new_fms' else 'Five-FMS 2025 baseline'),'lexical_context':None})
 b=f['parallel_units'][0];be='ENT-SO-REGION-BRA';E.append({'id':be,'schema_version':SCHEMA_VERSION,'country_code':'SO','canonical_name':b['name'],'canonical_name_language':'en','entity_type':'so_region','status':'current','valid_from':None,'valid_to':None,'canonical_source_id':MOP,'source_locator':'Banadir Regional Administration listed separately after seven FMS','legacy_ids':[],'coordinates':None,'notes':'Parallel federal-capital regional administration; not silently promoted to FMS.','verification_status':'verified','confidence':'high'});R.append({'id':record_id('REL-SO',be,'country'),'schema_version':SCHEMA_VERSION,'child_id':be,'parent_id':'ENT-SO-COUNTRY','relationship_type':'administrative_parent','status':'current','valid_from':None,'valid_to':None,'source_id':MOP,'source_locator':'Banadir Regional Administration separate entry','notes':'Parallel regional-administration path.','verification_status':'verified','confidence':'high'});C.append({'id':record_id('CLM-SO','profile',be),'schema_version':SCHEMA_VERSION,'subject_id':be,'predicate':'federal_planning_profile','value':{'type':'string','data':'banadir_regional_administration'},'unit':None,'status':'verified','observed_at':DATE,'valid_from':None,'valid_to':None,'source_id':MOP,'second_source_id':None,'source_locator':'Banadir Regional Administration listed separately from seven FMS','sensitivity':'ordinary','notes':'Distinct type/path, not an FMS alias.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':None,'lexical_context':None})
 ne='ENT-SO-FMS-07';C.append({'id':record_id('CLM-SO','northeast-transition'),'schema_version':SCHEMA_VERSION,'subject_id':ne,'predicate':'federal_member_transition','value':{'type':'json','data':{'constitution_adopted':'2025-07-30','parliament_formed':'2025-08-17','leadership_elected':'2025-08-30','full_member_declaration':'2026-01-17','predecessor_name':'SSC-Khaatumo'}},'unit':None,'status':'verified','observed_at':'2026-01-17','valid_from':'2025-07-30','valid_to':None,'source_id':MOI,'second_source_id':SONNA,'source_locator':'State formation completion and inauguration, 17 January 2026','sensitivity':'sensitive','notes':'SSC-Khaatumo is transition provenance, not a duplicate current entity.','verification_status':'verified','confidence':'high','classification':'official','published':True,'second_source_locator':'Presidential full-member declaration','lexical_context':None})
 ids={x['id'] for x in E}|{'ENT-SO-COUNTRY'};rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='SO' and r.get('entity_type')!='country',E);rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-SO-') and r.get('entity_id')!='ENT-SO-COUNTRY',[]);rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-SO-') and r.get('child_id')!='ENT-SO-COUNTRY',R);rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in ids,C)
 D=I/'fixtures/cultural_depth_2026.json';DDATE='2026-09-23'
 ILOC='UNESCO ICH and World Heritage pages and the 2012 Provisional Constitution as published by Constitute; factual extraction with attribution; CC BY-SA 3.0 IGO for the UNESCO descriptions'
 dd=L(D)
 assert hashlib.sha256(D.read_bytes()).hexdigest()==next(r['sha256'] for r in m['records'] if r['path'].endswith('cultural_depth_2026.json'))
 assert dd['country_code']=='SO' and dd['snapshot_date']==DDATE
 assert all(e['classification']=='shared' for e in dd['ich_elements'])
 assert dd['world_heritage_state']['inscribed_properties']==0
 DS={'ich_state':'SRC-UNESCO-ICH-SO-STATE-2026','ich_xeer':'SRC-UNESCO-ICH-SO-XEER-CIISE-02087-2024','ich_zaffa':'SRC-UNESCO-ICH-SO-ZAFFA-02283-2025','whc_state':'SRC-UNESCO-WH-SO-STATE-2026','tl_6752':'SRC-UNESCO-WH-SO-BUSHBUSHLE-6752-2024','tl_6753':'SRC-UNESCO-WH-SO-HOBYO-6753-2024','tl_6754':'SRC-UNESCO-WH-SO-LIGHTHOUSE-6754-2025','constitution':'SRC-SO-CONSTITUTION-2012','iso_som':'SRC-SO-ISO639-3-SOMALI','languages':'SRC-SO-LANGUAGES-MIRROR-2026','cuisine':'SRC-SO-CUISINE-MIRROR-2026','culture':'SRC-SO-CULTURE-MIRROR-2026','mogadishu':'SRC-SO-MOGADISHU-MIRROR-2026'}
 def dsrc(k,title,pub,typ,loc,note,tier,lang,lic,pdate=None):
  return {'id':DS[k],'schema_version':SCHEMA_VERSION,'title':title,'publisher':pub,'source_type':typ,'url':dd['sources'][k],'archive_url':None,'publication_date':pdate,'retrieved_at':DDATE,'license':lic if pdate is not None or lic else LIC,'language':lang,'country_codes':['SO'],'locator':loc,'checksum':'sha256:'+hashlib.sha256(D.read_bytes()).hexdigest(),'quality_tier':tier,'notes':note+('' if pdate else ' Publication date unavailable.')}
 U='UNESCO Intangible Cultural Heritage';W='UNESCO World Heritage Centre';SIL='SIL International (ISO 639-3 registration authority)'
 DS_ALL=[dsrc('ich_state','Somalia — UNESCO Intangible Cultural Heritage',U,'institutional_page','عنصران مُدرجان على القائمة التمثيلية (02087 سنة 2024 و02283 سنة 2025)؛ التصديق 23 يوليو 2020؛ تقرير الدورية 15 ديسمبر 2023','صفحة الدولة قُرئت 2026-09-23: قائمة العناصر وسنواتها وقوائمها وتاريخ التصديق.',tier='A',lang='en',lic=ILOC),
  dsrc('ich_xeer','Xeer Ciise: Oral customary laws of Somali-Issa communities in Ethiopia, Djibouti and Somalia',U,'institutional_page','عنصر 02087؛ إدراج 2024 (19.COM) على القائمة التمثيلية؛ إثيوبيا وجيبوتي والصومال','صفحة العنصر قُرئت 2026-09-23: المكوّنات الثلاثة ووسائل النقل الشفهي والقيم.',tier='A',lang='en',lic=ILOC),
  dsrc('ich_zaffa','The zaffa in the traditional wedding',U,'institutional_page','عنصر 02283؛ إدراج 2025 (20.COM)؛ سبع دول منها الصومال','صفحة العنصر قُرئت في دورة الصومال 2026-09-23 لإكمال قائمة الصومال دون ادّعاء حصرية؛ ومعرّف المصدر خاص بالصومال.',tier='A',lang='en',lic=ILOC),
  dsrc('whc_state','Somalia — UNESCO World Heritage Convention',W,'institutional_page','صفر موقع مُدرج؛ ثلاثة مواقع في القائمة المؤقتة (6752 و6753 سنة 2024، و6754 سنة 2025)؛ التصديق 23 يوليو 2020','صفحة الدولة قُرئت 2026-09-23: قائمة الإدراج الفارغة والقائمة المؤقتة وتاريخ التصديق والمساعدة الدولية.',tier='A',lang='en',lic=ILOC),
  dsrc('tl_6752','Bushbushle National Park — Tentative List',W,'institutional_page','ملف 6752؛ إيداع 20 مارس 2024؛ طبيعي؛ المعايير المقترحة (ix)(x)','صفحة الملف قُرئت 2026-09-23: النطاق والوصف والمعايير المقترحة.',tier='A',lang='en',lic=ILOC),
  dsrc('tl_6753','The Hobyo grass and Shrubland — Tentative List',W,'institutional_page','ملف 6753؛ إيداع 20 فبراير 2024؛ طبيعي؛ المعايير المقترحة (ix)(x)','صفحة الملف قُرئت 2026-09-23: الكثبان والمراعي والأنواع المتوطنة.',tier='A',lang='en',lic=ILOC),
  dsrc('tl_6754','Mogadishu Secondo-Lido Lighthouse — Tentative List',W,'institutional_page','ملف 6754؛ إيداع 22 يناير 2025؛ ثقافي؛ المعايير المقترحة (i)(ii)(iii)(iv)؛ مدينة مقديشو، بنادر','صفحة الملف قُرئت 2026-09-23: المنارة والمدينة القديمة «حمر» والمسجد العتيق.',tier='A',lang='en',lic=ILOC),
  dsrc('constitution','Somalia 2012 Provisional Constitution (as published by Constitute)','Constitute Project — Comparative Constitutions Project','law','المواد 1 و2 و5 و6 و7 و9 و15','نصّ دستوري منشور على مشروع Constitute قُرئ 2026-09-23: الدولة والدين واللغات والقواعد والإقليم والعاصمة والسلامة الشخصية؛ لا يُنسب تاريخ إصدار إلى الصفحة.',tier='A',lang='en',lic=None),
  dsrc('iso_som','ISO 639-3 code registration — Somali',SIL,'standard','som = Somali؛ 639-1: so؛ مجموعتا 639-2 و639-3؛ فردية، حيّة','صفحة السجل قُرئت 2026-09-23.',tier='A',lang='en',lic=None),
  dsrc('languages','Languages of Somalia','Wikipedia (English mirror)','local_website','الرسمية: الصومالية؛ شبه الرسمية: العربية؛ أقليات: باجونية وبرافانية وبونية ودبارية وغرّية وجيدوية وموشونغولية وتونية؛ أجنبية: الإنجليزية والإيطالية والسواحيلية؛ لغة إشارة صومالية','مرآة إنجليزية لخريطة اللغات؛ تُستعمل للتصنيف والحضور فقط، ولا تُسجَّل أعداد المتحدثين ولا نسبها المطبوعة.',tier='E',lang='en',lic=None),
  dsrc('cuisine','Somali cuisine','Wikipedia (English mirror)','local_website','مطبخ الصومال: الكنغيرو/اللحوح، الساباياد/الكميس، المووفو، المشاري، السقار، الأوقاك/المقماد، فه فه، الباستو، شاي كاديس، القهوة، حليب الإبل','مرآة إنجليزية تصف المطبخ؛ تُسجَّل كل مادة منها غير منشورة.',tier='E',lang='en',lic=None),
  dsrc('culture','Culture of Somalia','Wikipedia (English mirror)','local_website','تراث شفهي شعري («أمة الشعراء»)، رقص دهانتو، لعبة غوغالايسي، مبخرة دبقاد، فنون: فخار وحفر خشب','مرآة إنجليزية تصف الثقافة؛ تُستعمل للتصنيف فقط، ولا تُسجَّل أي أعداد.',tier='E',lang='en',lic=None),
  dsrc('mogadishu','Mogadishu','Wikipedia (English mirror)','local_website','مقديشو (مقديشو/حمر)، بنادر، موقع ساحلي في المحيط الهندي','مرآة إنجليزية للعاصمة؛ لا تُسجَّل أعداد سكان ولا إحداثيات.',tier='E',lang='en',lic=None)]
 E=[r for r in E if r['id']!='ENT-SO-COUNTRY']+[r for r in E if r['id']=='ENT-SO-COUNTRY']
 PLACE=[('ENT-SO-SITE-BUSHBUSHLE','متنزه بوشبوشلي الوطني','natural_site','ENT-SO-COUNTRY'),('ENT-SO-SITE-HOBYO','مراعي هوبيو والشجيرات','natural_site','ENT-SO-COUNTRY'),('ENT-SO-SITE-LIGHTHOUSE','منارة مقديشو سيكوندو-ليدو','cultural_site','ENT-SO-REGION-BRA'),('ENT-SO-QUARTER-HAMAR','مدينة مقديشو القديمة (حمر)','quarter','ENT-SO-REGION-BRA')]
 PMAP={}
 for q in dd['places']['sites']+dd['places']['quarters']:PMAP[q['latin']]=q
 for eid,name,typ,parent in PLACE:
  q=PMAP[[q for q in dd['places']['sites']+dd['places']['quarters'] if q['name']==name][0]['latin']]
  tier='A'
  E.append({'id':eid,'schema_version':SCHEMA_VERSION,'country_code':'SO','canonical_name':name,'canonical_name_language':'ar','entity_type':typ,'status':'current','valid_from':None,'valid_to':None,'canonical_source_id':DS[q['source']],'source_locator':q['note'],'legacy_ids':[],'coordinates':None,'notes':q['note'],'verification_status':'source_verified','confidence':'high'})
  R.append({'id':record_id('REL-SO',eid,'located'),'schema_version':SCHEMA_VERSION,'child_id':eid,'parent_id':parent,'relationship_type':'located_in','status':'current','valid_from':None,'valid_to':None,'source_id':DS[q['source']],'source_locator':q['note'],'notes':'علاقة مكانية واحدة بلا أب إداري وبلا دعوى سكان وبلا نسبة.','verification_status':'source_verified','confidence':'high'})
 DC=[]
 def dclm(pred,subj,val,cls,key,src,loc,pub=False,conf='low',sec=None,secloc=None,note='',sens='ordinary',vtype='json'):
  row={'id':record_id('CLM-SO-DEPTH',pred,subj,key),'schema_version':SCHEMA_VERSION,'subject_id':subj,'predicate':pred,'value':{'type':vtype,'data':val},'unit':None,'status':'verified' if pub else 'reported','observed_at':DDATE,'valid_from':None,'valid_to':None,'source_id':src,'second_source_id':sec,'source_locator':loc,'sensitivity':sens,'notes':note,'verification_status':'verified' if pub else 'local_reported','confidence':'high' if pub else conf,'classification':cls,'published':pub,'second_source_locator':secloc,'lexical_context':None}
  DC.append(row);C.append(row);return row
 for el in dd['ich_elements']:
  dclm('intangible_cultural_practice','ENT-SO-COUNTRY',{'name':el['name'],'official_title':el['official_title'],'reference':el['reference'],'year':el['year'],'list':el['list'],'co_states':el['co_states'],'description':el['description']},el['classification'],el['reference'],DS[el['source']],f"عنصر {el['reference']}؛ إدراج {el['year']} على القائمة التمثيلية" if el['list']=='RL' else f"عنصر {el['reference']}؛ إدراج {el['year']}",pub=True,note='عنصر مُدرج في قوائم اليونسكو؛ يُنشر بوصفه عنصرًا رسميًا، وملفه مشترك فلا يُدّعى فيه حصرية.')
 for r in dd['ratifications']:
  dclm('convention_ratification_date' if '2003' in r['convention'] else 'world_heritage_convention_ratification','ENT-SO-COUNTRY',r['convention'],'official',r['date'],DS[r['source']],f"تصديق {r['date']}",pub=True,note='تاريخ تصديق من صفحة الدولة؛ يُنشر مرة واحدة ولا يُوسَّع إلى سرد.')
 dclm('world_heritage_inscribed_count','ENT-SO-COUNTRY',dd['world_heritage_state']['inscribed_properties'],'official','inscribed-count',DS['whc_state'],'صفحة الدولة: Properties inscribed on the World Heritage List = 0',pub=True,note='صفر مقصود مقروء من صفحة الدولة؛ يُنشر ليمنع أي تقدير بديل، ولا يُقارن بقوائم إقليمية.',vtype='integer')
 for t in dd['tentative_sites']:
  dclm('unesco_tentative_listing','ENT-SO-COUNTRY',{'name':t['name'],'reference':t['reference'],'year':t['year'],'status':'القائمة المؤقتة','category':t['category'],'criteria_submitted':t['criteria_submitted'],'submitted_on':t['submitted_on'],'submitted_by':t['submitted_by'],'region':t['region']},'official',t['reference'],DS[t['source']],f"ملف القائمة المؤقتة {t['reference']}؛ إيداع {t['submitted_on']}",pub=True,note=t['note'])
 for p in dd['constitution_provisions']:
  dclm('constitutional_provision','ENT-SO-COUNTRY',{'article':p['article'],'topic':p['topic'],'summary':p['summary']},'official',f"article-{p['article']}",DS['constitution'],f"الدستور المؤقت 2012: المادة {p['article']} ({p['topic']})",pub=True,note=p['note'])
 for l in dd['language_presence']:
  pub=l['level'] in ('official','second_language')
  dclm('language_presence','ENT-SO-COUNTRY',{'name':l['name'],'level':l['level'],'official':l['official'],'iso_codes':l['codes'],'note':l['note']},'official' if pub else 'local_reported',l['name'],DS[l['source']],l['name'] if pub else f"مرآة اللغات: {l['name']}",pub=pub,sec=DS[l['second']] if l['second'] else None,secloc='سجل ISO 639-3: som = Somali' if l['second'] else None,note=l['note'])
 for d in dd['dialect_profiles']:
  dclm('dialect_profile','ENT-SO-COUNTRY',{'name':d['name'],'group':d['group'],'features':d['features']},'regional',d['name'],DS[d['source']],f"مرآة اللغات: {d['name']}",note='وصف لهجي مصنَّف من مرآة؛ لا يُنشر ولا يُبنى عليه مقام.')
 for i in dd['language_institutions']:
  dclm('language_institution','ENT-SO-COUNTRY',{'name':i['name'],'founded':i['founded'],'states':i['states'],'mandate':i['mandate']},'regional',i['name'],DS[i['source']],f"مرآة اللغات: {i['name']}",note=i['note'])
 for x in dd['dishes']:
  dclm('food_dish','ENT-SO-COUNTRY',{'name':x['name'],'description':x['desc']},'local',x['name'],DS['cuisine'],f"المطبخ الصومالي: {x['name']}",note='طبق محلي من مرآة؛ يُسجَّل مصنَّفًا غير منشور ولا يُنسب إلى إحصاء.')
 for x in dd['crafts']:
  dclm('craft_custom','ENT-SO-COUNTRY',{'name':x['name'],'description':x['desc']},'local',x['name'],DS['culture'],f"ثقافة الصومال: {x['name']}",note='حرفة أو فن من مرآة؛ يُسجَّل مصنَّفًا غير منشور.')
 for x in dd['customs']:
  dclm('custom_practice','ENT-SO-COUNTRY',{'name':x['name'],'description':x['desc']},'popular',x['name'],DS['culture'],f"ثقافة الصومال: {x['name']}",note='عرف أو ممارسة من مرآة؛ يُسجَّل مصنَّفًا غير منشور ولا يُقدَّم وصفًا قانونيًا.')
 for n in dd['narratives']:
  dclm('place_name_narrative','ENT-SO-COUNTRY',{'name':n['name'],'description':n['desc']},'local_reported',n['name'],DS['mogadishu'],'ملف القائمة المؤقتة 6754: المدينة القديمة «حمر»',note='تسميات وروايات مكانية معلنة من مصدر رسمي؛ تُسجَّل روايةً ولا يُحسم أصل الاسم.')
 IDS={x['id'] for x in E}|{'ENT-SO-COUNTRY'}
 rep(ROOT/'data/entities/entities.jsonl',lambda r:r.get('country_code')=='SO' and r.get('entity_type')!='country',E)
 rep(ROOT/'data/aliases/aliases.jsonl',lambda r:r.get('entity_id','').startswith('ENT-SO-') and r.get('entity_id')!='ENT-SO-COUNTRY',[])
 rep(ROOT/'data/relationships/relationships.jsonl',lambda r:r.get('child_id','').startswith('ENT-SO-') and r.get('child_id')!='ENT-SO-COUNTRY',R)
 rep(ROOT/'data/claims/claims.jsonl',lambda r:r.get('subject_id') in IDS,C)
 def d(i,l,n,s,note,status='official',missing=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SO','layer':l,'definition':note,'value':n,'as_of':DATE,'status':status,'source_id':s,'source_locator':note,'license':LIC,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE}
 def v(i,l,did,n,matched,s,note,complete,missing=None):return {'id':i,'schema_version':SCHEMA_VERSION,'country_code':'SO','layer':l,'snapshot_id':SNAP,'denominator_id':did,'source_id':s,'matched':matched,'unmatched':0 if n is None else n-matched,'excluded':0,'missing':None if n is None else n-matched,'complete':complete,'missing_reason':missing,'notes':note,'denominator':n,'snapshot_date':DATE,'license':LIC,'coverage_percentage':None if n is None else round(matched*100/n,2),'exclusion_reasons':[]}
 specs=[('MOP-FMS','so_federal_member_state_mop_frame',7,7,MOP,'Seven FMS in current Ministry of Planning frame.'),('STANDARD-FIVE','so_federal_member_state_standard_five',5,5,OLD,'Five standard operational FMS in 2025 baseline.'),('SOMALILAND-NARRATIVE','so_fms_somaliland_fgs_narrative',1,1,SEN,'FGS planning/Senate narrative only.'),('NORTHEAST','so_fms_north_east_current',1,1,SONNA,'North East full member from 2026-01-17.'),('BANADIR','so_banadir_regional_administration',1,1,MOP,'Banadir parallel regional administration.')];ds=[d('DEN-SO-'+a,l,n,s,note) for a,l,n,_,s,note in specs];vs=[v('COV-SO-'+a,l,'DEN-SO-'+a,n,mt,s,note,True) for a,l,n,mt,s,note in specs]
 for a,l in [('REGIONS','so_region_record_universe'),('DISTRICTS','so_district_record_universe')]:
  reason='No authority-reconciled national denominator is accepted across overlapping federal, Somaliland, Puntland, North East, and Banadir structures.';ds.append(d('DEN-SO-'+a,l,None,MOP,l,'unavailable',reason));vs.append(v('COV-SO-'+a,l,'DEN-SO-'+a,None,0,MOP,l,False,reason))
 rep(ROOT/'data/coverage/denominators.jsonl',lambda r:r.get('country_code')=='SO' and r.get('layer')!='country_scope',ds);rep(ROOT/'data/coverage/coverage.jsonl',lambda r:r.get('country_code')=='SO' and r.get('layer')!='country_scope',vs);snap={'id':SNAP,'schema_version':SCHEMA_VERSION,'title':'Somalia authority-specific federal planning frames, extended with UNESCO ICH/World Heritage, constitution articles and classified local knowledge','captured_at':DATE,'source_id':MOP,'scope':'Seven MOP FMS, one parallel Banadir administration, five-FMS baseline, Somaliland and North East narratives, two shared ICH elements, three tentative-list sites and four places without rank','method':'Checksum-bound authority/date-specific reconciliation; no territorial union or control map; depth cycle 1 read the UNESCO ICH and World Heritage pages, the 2012 Provisional Constitution as published by Constitute, and the ISO 639-3 registration for Somali.','checksum':'sha256:'+hashlib.sha256(M.read_bytes()).hexdigest(),'notes':'Region/district denominators and territorial/effective-control overlays unavailable; depth layers carry no denominator and no inherited population.'};rep(ROOT/'data/snapshots/snapshots.jsonl',lambda r:r.get('id','').startswith('SNP-SO-PRODUCTION-'),[snap])
 man=L(ROOT/'manifests/SO.yml');man.update({'status':'pilot_migrated','official_authority':{'name':'Federal Ministries of Planning and Interior / SONNA / Upper House','source_ids':[MOP,MOI,SONNA,SEN,OLD],'verification_status':'verified','missing_reason':None},'snapshot':{'as_of':DATE,'snapshot_id':SNAP,'status':'verified'},'coverage_record_ids':['COV-SO-COUNTRY-SCOPE',*[x['id'] for x in vs]],'caveats':['Seven-FMS denominator is explicitly the current Ministry of Planning frame, not a neutral sovereignty/control adjudication.','Banadir is a parallel regional administration.','Somaliland and North East records preserve FGS-attributed narratives; overlapping claims/control are not inferred.'],'next_action':'Maintain authority-specific federal frames; add regions/districts or claim/control overlays only after multi-authority reconciliation.'})
 for x in man['hierarchy']:
  if x['entity_type']=='so_federal_member_state':x.update({'source_ids':[MOP,MOI,SONNA,SEN,OLD],'verification_status':'verified','authority_name':'FGS authority-specific frame','denominator':7,'denominator_id':'DEN-SO-MOP-FMS','coverage_record_id':'COV-SO-MOP-FMS','snapshot_date':DATE,'license':LIC,'scope_status':'closed','notes':'Seven entries in MOP frame; narrative-specific.','special_cases':['Somaliland claimed/FGS narrative; North East full-member transition 2026-01-17.']})
  elif x['entity_type']=='so_region':x.update({'source_ids':[MOP],'verification_status':'pending','authority_name':'Multiple authorities','denominator':None,'denominator_id':'DEN-SO-REGIONS','coverage_record_id':'COV-SO-REGIONS','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'Only Banadir parallel administration emitted; national region universe unreconciled.','special_cases':['Banadir is not an FMS.']})
  elif x['entity_type']=='so_district':x.update({'source_ids':[MOP],'verification_status':'pending','authority_name':'Multiple authorities','denominator':None,'denominator_id':'DEN-SO-DISTRICTS','coverage_record_id':'COV-SO-DISTRICTS','snapshot_date':DATE,'license':LIC,'scope_status':'unavailable','notes':'National district universe unreconciled.','special_cases':['No control-based parent inference.']})
  DEPTH_LAYERS = [
     {'layer': 'unesco_intangible_heritage', 'entity_types': ['cultural_site'], 'local_names': ['عنصر تراث غير مادي'],
      'authority_name': 'UNESCO Intangible Cultural Heritage', 'denominator': 2, 'denominator_id': None, 'coverage_record_id': None,
      'snapshot_date': DDATE, 'source_ids': [DS['ich_state'], DS['ich_xeer'], DS['ich_zaffa']], 'license': ILOC,
      'scope_status': 'closed', 'notes': 'عنصران مُدرجان على صفحة الدولة، وكلاهما ملف مشترك.',
      'special_cases': ['الملفات المشتركة تبقى shared ولا يُدَّعى فيها حصرية.',
                        'الملف المعلن ليس إدراجًا، ولا عنصر وطني حصري في هذه الدورة.',
                        'لا يُسجَّل عدد متحدثين ولا نسبة في أي دعوى ثقافية.']},
     {'layer': 'world_heritage_inscribed', 'entity_types': ['cultural_site', 'natural_site'], 'local_names': ['موقع تراث عالمي'],
      'authority_name': 'UNESCO World Heritage Centre', 'denominator': 0, 'denominator_id': None, 'coverage_record_id': None,
      'snapshot_date': DDATE, 'source_ids': [DS['whc_state']], 'license': ILOC, 'scope_status': 'closed',
      'notes': 'صفر موقع مُدرج مقروء من صفحة الدولة.',
      'special_cases': ['الصفر مقصود ومعلن من المصدر، ولا يُحوَّل إلى تقدير ولا يُقارن بقوائم إقليمية.']},
     {'layer': 'world_heritage_tentative_list', 'entity_types': ['natural_site', 'cultural_site'], 'local_names': ['القائمة المؤقتة'],
      'authority_name': 'UNESCO World Heritage Centre', 'denominator': 3, 'denominator_id': None, 'coverage_record_id': None,
      'snapshot_date': DDATE, 'source_ids': [DS['whc_state'], DS['tl_6752'], DS['tl_6753'], DS['tl_6754']], 'license': ILOC,
      'scope_status': 'closed', 'notes': 'ثلاثة مواقع في القائمة المؤقتة (2024-2025).',
      'special_cases': ['القائمة المؤقتة ليست إدراجًا.', 'المعايير المسجَّلة معايير مقترحة في الملف لا معايير إدراج.',
                        'إحداثيات ملف بوشبوشلي مشوَّشة في هذه القراءة فلا تُسجَّل.']},
     {'layer': 'heritage_places', 'entity_types': ['natural_site', 'cultural_site', 'quarter'], 'local_names': ['موقع أو نطاق تراثي'],
      'authority_name': 'UNESCO World Heritage Centre', 'denominator': None, 'denominator_id': None, 'coverage_record_id': None,
      'snapshot_date': DDATE, 'source_ids': [DS['tl_6752'], DS['tl_6753'], DS['tl_6754']], 'license': ILOC, 'scope_status': 'open',
      'notes': 'أربعة أماكن: ثلاثة مواقع في القائمة المؤقتة ونطاق عمراني قديم.',
      'special_cases': ['الأماكن بـlocated_in فقط: بلا أب إداري وبلا دعوى سكان وبلا نسبة.',
                        'لا تُنسب المواقع الطبيعية إلى ولايات غير مقبولة في الطبقة المقبولة.',
                        'النطاق العمراني «حمر» نطاق لا حي إداري.']},
     {'layer': 'classified_local_knowledge', 'entity_types': ['cultural_site'], 'local_names': ['معرفة محلية مصنَّفة'],
      'authority_name': 'Wikimedia mirrors (Arabic/English)', 'denominator': None, 'denominator_id': None, 'coverage_record_id': None,
      'snapshot_date': DDATE, 'source_ids': [DS['languages'], DS['cuisine'], DS['culture'], DS['mogadishu']], 'license': LIC,
      'scope_status': 'open', 'notes': 'جسم لغوي وأطباق وحرف وأعراف ورواية تسمية، كله غير منشور.',
      'special_cases': ['لا يُنشر أي ادّعاء ضعيف المصدر ولا يُبنى عليه مقام.',
                        'لا تُسجَّل أعداد متحدثين ولا نسب ولا أعداد سكان.',
                        'الرمز اللغوي لا يُسجَّل إلا متحقَّقًا من سجل ISO 639-3.']},
 ]
 for _s in DS_ALL:
     write_json(ROOT / 'data/sources' / f"{_s['id']}.json", _s)
 write_json(I / 'source_catalog.json', {'schema_version': SCHEMA_VERSION, 'country_code': 'SO', 'sources': S + DS_ALL})
 ACCEPTED_LAYERS=[{'layer':'so_federal_member_state_mop_frame','entity_types':['so_federal_member_state'],'local_names':['Federal Member State'],'authority_name':'Ministry of Planning','denominator':7,'denominator_id':'DEN-SO-MOP-FMS','coverage_record_id':'COV-SO-MOP-FMS','snapshot_date':DATE,'source_ids':[MOP],'license':LIC,'scope_status':'closed','notes':'Authority-specific frame.','special_cases':['Somaliland and North East require narrative context.']},{'layer':'so_banadir_regional_administration','entity_types':['so_region'],'local_names':['Regional Administration'],'authority_name':'Ministry of Planning','denominator':1,'denominator_id':'DEN-SO-BANADIR','coverage_record_id':'COV-SO-BANADIR','snapshot_date':DATE,'source_ids':[MOP],'license':LIC,'scope_status':'closed','notes':'Parallel unit.','special_cases':[]}]
 man['pilot_layers'] = ACCEPTED_LAYERS + DEPTH_LAYERS
 man['next_action'] = ('Extend regions/districts only after multi-authority reconciliation; keep heritage places located_in-only; add a dated territorial-control overlay separately; clothing remains unsourced.')
 man['caveats'].append('Depth layers carry no denominator and no inherited population; the inscribed-property count is a deliberate zero.')
 write_json(ROOT / 'manifests/SO.yml', man)
 write_json(ROOT / 'data/cultural/somalia_domain_status.json', {
     'schema_version': SCHEMA_VERSION, 'country_code': 'SO', 'snapshot_date': DDATE,
     'domains': {
         'world_heritage': {'status': 'no_inscribed_properties_three_tentative_sites', 'inscribed': 0, 'tentative_list_sites': 3},
         'intangible_cultural_heritage': {'status': 'documented_two_shared_elements_no_national', 'elements': 2, 'national': 0, 'shared': 2},
         'languages': {'status': 'documented_two_published_rest_unpublished', 'claims': 14},
         'dialect': {'status': 'documented_local_reported_unpublished', 'claims': 3},
         'language_institutions': {'status': 'documented_local_reported_unpublished', 'claims': 1},
         'food': {'status': 'documented_local_reported_unpublished', 'claims': 12},
         'crafts': {'status': 'documented_local_reported_unpublished', 'claims': 3},
         'custom': {'status': 'documented_local_reported_unpublished', 'claims': 3},
         'narratives': {'status': 'documented_naming_narrative_unpublished', 'claims': 1},
         'dress': {'status': 'not_documented_in_cycle', 'claims': 0},
         'heritage_places': {'status': 'documented_places_no_denominator', 'entities': 4, 'denominator': None},
         'territorial_control': {'status': 'requires_separate_dated_overlay'},
     },
     'notes': 'عنصران يونسكويان مشتركان بلا عنصر وطني، وصفر مواقع مُدرجة وثلاثة في القائمة المؤقتة، وسبع مواد دستورية، '
              'ولا يُسجَّل أي عدد متحدثين أو سكان أو نسبة في أي دعوى.'})
 print(json.dumps({'entities': len(E) + 1, 'relationships': len(R), 'claims': len(C), 'depth_claims': len(DC),
                   'places': len([e for e in E if e['entity_type'] in ('natural_site', 'cultural_site', 'quarter')]),
                   'sources': len(S) + len(DS_ALL)}))
if __name__=='__main__':main()
