#!/usr/bin/env python3
import json
from model import ROOT,read_jsonl,write_json
def L(p):return json.loads(p.read_text(encoding='utf8'))
def main():
 f=L(ROOT/'data/imports/somalia/fixtures/federal_frames_2026.json');e=[r for r in read_jsonl(ROOT/'data/entities/entities.jsonl') if r.get('country_code')=='SO'];ids={r['id'] for r in e};families={'entities':e,'aliases':[r for r in read_jsonl(ROOT/'data/aliases/aliases.jsonl') if r.get('entity_id') in ids],'relationships':[r for r in read_jsonl(ROOT/'data/relationships/relationships.jsonl') if r.get('child_id') in ids],'claims':[r for r in read_jsonl(ROOT/'data/claims/claims.jsonl') if r.get('subject_id') in ids],'denominators':[r for r in read_jsonl(ROOT/'data/coverage/denominators.jsonl') if r.get('country_code')=='SO'],'coverage':[r for r in read_jsonl(ROOT/'data/coverage/coverage.jsonl') if r.get('country_code')=='SO']};sids={'SRC-SO-MOP-FMS-2026','SRC-SO-MOIFAR-NORTHEAST-2026','SRC-SO-SONNA-NORTHEAST-DECLARATION-2026','SRC-SO-SENATE-CONSTITUENCY','SRC-SO-MPWR-FIVE-FMS-2025'};families['sources']=[L(p) for p in (ROOT/'data/sources').glob('*.json') if L(p).get('id') in sids];E={r['id']:r for r in e};find=[]
 for q in f['federal_member_states']:
  if E.get('ENT-SO-FMS-'+q['code'],{}).get('canonical_name')!=q['name']:find.append({'severity':'P1','record_id':q['code'],'message':'fixture identity'})
 if E.get('ENT-SO-REGION-BRA',{}).get('entity_type')!='so_region':find.append({'severity':'P1','record_id':'Banadir','message':'parallel type'})
 if E.get('ENT-SO-FMS-06',{}).get('status')!='claimed' or E.get('ENT-SO-FMS-07',{}).get('valid_from')!='2026-01-17':find.append({'severity':'P1','record_id':'narratives','message':'Somaliland/North East temporal status'})
 sample={k:{'population':len(v),'sample_size':len(v),'sample_percentage':100.0,'record_ids':sorted(x['id'] for x in v)} for k,v in families.items()};write_json(ROOT/'data/review/somalia_review_samples.json',{'schema_version':'2.0.0','country_code':'SO','families':sample});write_json(ROOT/'reports/somalia_review_samples.json',{'schema_version':'2.0.0','country_code':'SO','families':sample});n=sum(len(v) for v in families.values());ok=not find;res={k:{'sampled':len(v),'passed':len(v) if ok else 0,'failed':0 if ok else len(v),'status':'PASS' if ok else 'FAIL'} for k,v in families.items()};write_json(ROOT/'reports/somalia_independent_review.json',{'schema_version':'2.0.0','country_code':'SO','status':'PASS' if ok else 'FAIL','p0':0,'critical_p1':len(find),'method':'Independent full-population authority-frame review: 7 MOP entries, Banadir parallel path, Somaliland narrative, North East transition, unavailable lower universes.','families':res,'total_sampled':n,'total_passed':n if ok else 0,'findings':find});print(n);return 0 if ok else 1
if __name__=='__main__':raise SystemExit(main())
