#!/usr/bin/env python3
import json
from model import ROOT,read_jsonl,write_json
def L(p):return json.loads(p.read_text(encoding='utf8'))
def main():
 f=L(ROOT/'data/imports/sudan/fixtures/states_2026.json');e=[r for r in read_jsonl(ROOT/'data/entities/entities.jsonl') if r.get('country_code')=='SD'];ids={r['id'] for r in e};fam={'entities':e,'aliases':[r for r in read_jsonl(ROOT/'data/aliases/aliases.jsonl') if r.get('entity_id') in ids],'relationships':[r for r in read_jsonl(ROOT/'data/relationships/relationships.jsonl') if r.get('child_id') in ids],'claims':[r for r in read_jsonl(ROOT/'data/claims/claims.jsonl') if r.get('subject_id') in ids],'denominators':[r for r in read_jsonl(ROOT/'data/coverage/denominators.jsonl') if r.get('country_code')=='SD'],'coverage':[r for r in read_jsonl(ROOT/'data/coverage/coverage.jsonl') if r.get('country_code')=='SD']};sids={'SRC-SD-PRESIDENCY-STATES-CATALOGUE','SRC-SD-EMBASSY-QATAR-18-STATES','SRC-SD-CBS-AUTHORITY'};fam['sources']=[L(p) for p in (ROOT/'data/sources').glob('*.json') if L(p).get('id') in sids];E={r['id']:r for r in e};find=[]
 for q in f['states']:
  if E.get('ENT-SD-STATE-'+q['code'],{}).get('canonical_name')!=q['name_ar']:find.append({'severity':'P1','record_id':q['code'],'message':'fixture identity'})
 sample={k:{'population':len(v),'sample_size':len(v),'sample_percentage':100.0,'record_ids':sorted(x['id'] for x in v)} for k,v in fam.items()};write_json(ROOT/'data/review/sudan_review_samples.json',{'schema_version':'2.0.0','country_code':'SD','families':sample});write_json(ROOT/'reports/sudan_review_samples.json',{'schema_version':'2.0.0','country_code':'SD','families':sample});n=sum(len(v) for v in fam.values());ok=not find;res={k:{'sampled':len(v),'passed':len(v) if ok else 0,'failed':0 if ok else len(v),'status':'PASS' if ok else 'FAIL'} for k,v in fam.items()};write_json(ROOT/'reports/sudan_independent_review.json',{'schema_version':'2.0.0','country_code':'SD','status':'PASS' if ok else 'FAIL','p0':0,'critical_p1':len(find),'method':'Independent full 18-state fixture comparison and unavailable-lower-layer review.','families':res,'total_sampled':n,'total_passed':n if ok else 0,'findings':find});print(n);return 0 if ok else 1
if __name__=='__main__':raise SystemExit(main())
