#!/usr/bin/env python3
"""Independent full Qatar fixture review."""
import json
from model import ROOT,read_jsonl,write_json
def L(p):return json.loads(p.read_text(encoding='utf8'))
def main():
 f=L(ROOT/'data/imports/qatar/fixtures/municipalities_census_2020.json');e=[r for r in read_jsonl(ROOT/'data/entities/entities.jsonl') if r.get('country_code')=='QA'];ids={r['id'] for r in e};families={'entities':e,'aliases':[r for r in read_jsonl(ROOT/'data/aliases/aliases.jsonl') if r.get('entity_id') in ids],'relationships':[r for r in read_jsonl(ROOT/'data/relationships/relationships.jsonl') if r.get('child_id') in ids],'claims':[r for r in read_jsonl(ROOT/'data/claims/claims.jsonl') if r.get('subject_id') in ids],'denominators':[r for r in read_jsonl(ROOT/'data/coverage/denominators.jsonl') if r.get('country_code')=='QA'],'coverage':[r for r in read_jsonl(ROOT/'data/coverage/coverage.jsonl') if r.get('country_code')=='QA']};sids={'SRC-QA-PSA-CENSUS-MUNICIPALITIES-2020','SRC-QA-QNMP-EIGHT-MUNICIPALITIES-2026','SRC-UNESCO-WHC-QA-1402'};families['sources']=[L(p) for p in (ROOT/'data/sources').glob('*.json') if L(p).get('id') in sids];sample={k:{'population':len(v),'sample_size':len(v),'sample_percentage':100.0,'record_ids':sorted(x['id'] for x in v)} for k,v in families.items()};write_json(ROOT/'data/review/qatar_review_samples.json',{'schema_version':'2.0.0','country_code':'QA','families':sample});write_json(ROOT/'reports/qatar_review_samples.json',{'schema_version':'2.0.0','country_code':'QA','families':sample});find=[];actual={x['canonical_name']:x for x in e if x['entity_type']=='qa_municipality'}
 for x in f['records']:
  q=actual.get(x['name_ar']);
  if not q or not any(c['subject_id']==q['id'] and c['predicate']=='population' and c['value']['data']==x['population'] for c in families['claims']):find.append({'severity':'P1','record_id':x['name_ar'],'message':'fixture mismatch'})
 n=sum(len(v) for v in families.values());ok=not find;res={k:{'population':len(v),'sampled':len(v),'passed':len(v) if ok else 0,'failed':0 if ok else len(v),'status':'PASS' if ok else 'FAIL'} for k,v in families.items()};write_json(ROOT/'reports/qatar_independent_review.json',{'schema_version':'2.0.0','country_code':'QA','status':'PASS' if ok else 'FAIL','p0':0,'critical_p1':len(find),'method':'Independent full comparison to PSA fixture; importer/validator not imported.','families':res,'total_sampled':n,'total_passed':n if ok else 0,'findings':find});print(n);return 0 if ok else 1
if __name__=='__main__':raise SystemExit(main())
