#!/usr/bin/env python3
import json
from model import ROOT,read_jsonl,write_json,norm_name
def L(p):return json.loads(p.read_text(encoding='utf8'))
def main():
 f=L(ROOT/'data/imports/libya/fixtures/current_municipalities_2026.json');e=[r for r in read_jsonl(ROOT/'data/entities/entities.jsonl') if r.get('country_code')=='LY'];ids={r['id'] for r in e};families={'entities':e,'aliases':[r for r in read_jsonl(ROOT/'data/aliases/aliases.jsonl') if r.get('entity_id') in ids],'relationships':[r for r in read_jsonl(ROOT/'data/relationships/relationships.jsonl') if r.get('child_id') in ids],'claims':[r for r in read_jsonl(ROOT/'data/claims/claims.jsonl') if r.get('subject_id') in ids],'denominators':[r for r in read_jsonl(ROOT/'data/coverage/denominators.jsonl') if r.get('country_code')=='LY'],'coverage':[r for r in read_jsonl(ROOT/'data/coverage/coverage.jsonl') if r.get('country_code')=='LY']};sids={'SRC-LY-BSC-CENSUS-2006','SRC-LY-LAW-59-2012','SRC-LY-MOLG-MUNICIPALITIES-2026'};families['sources']=[L(p) for p in (ROOT/'data/sources').glob('*.json') if L(p).get('id') in sids];find=[];cur={norm_name(r['canonical_name']):r for r in e if r['entity_type']=='ly_municipality'}
 for q in f['municipalities']:
  r=cur.get(norm_name(q['name_ar']))
  if not r or r.get('source_locator')!=f"municipalities catalogue entry position {q['catalog_position']}: {q['name_ar']}":find.append({'severity':'P1','record_id':q['name_ar'],'message':'catalogue identity/position mismatch'})
 if any(r['entity_type']=='ly_shabiya_historical' and r['status']!='historical' for r in e):find.append({'severity':'P1','record_id':'historical','message':'status mismatch'})
 sample={k:{'population':len(v),'sample_size':len(v),'sample_percentage':100.0,'record_ids':sorted(x['id'] for x in v)} for k,v in families.items()};write_json(ROOT/'data/review/libya_review_samples.json',{'schema_version':'2.0.0','country_code':'LY','families':sample});write_json(ROOT/'reports/libya_review_samples.json',{'schema_version':'2.0.0','country_code':'LY','families':sample});n=sum(len(v) for v in families.values());ok=not find;res={k:{'sampled':len(v),'passed':len(v) if ok else 0,'failed':0 if ok else len(v),'status':'PASS' if ok else 'FAIL'} for k,v in families.items()};write_json(ROOT/'reports/libya_independent_review.json',{'schema_version':'2.0.0','country_code':'LY','status':'PASS' if ok else 'FAIL','p0':0,'critical_p1':len(find),'method':'Independent full catalogue-position and historical-layer comparison.','families':res,'total_sampled':n,'total_passed':n if ok else 0,'findings':find});print(n);return 0 if ok else 1
if __name__=='__main__':raise SystemExit(main())
