#!/usr/bin/env python3
import json
from model import ROOT,read_jsonl,write_json
def L(p): return json.loads(p.read_text(encoding='utf8'))
def main():
 f=L(ROOT/'data/imports/yemen/fixtures/first_level_2026.json'); e=[r for r in read_jsonl(ROOT/'data/entities/entities.jsonl') if r.get('country_code')=='YE']; ids={r['id'] for r in e}; families={'entities':e,'aliases':[r for r in read_jsonl(ROOT/'data/aliases/aliases.jsonl') if r.get('entity_id') in ids],'relationships':[r for r in read_jsonl(ROOT/'data/relationships/relationships.jsonl') if r.get('child_id') in ids],'claims':[r for r in read_jsonl(ROOT/'data/claims/claims.jsonl') if r.get('subject_id') in ids],'denominators':[r for r in read_jsonl(ROOT/'data/coverage/denominators.jsonl') if r.get('country_code')=='YE'],'coverage':[r for r in read_jsonl(ROOT/'data/coverage/coverage.jsonl') if r.get('country_code')=='YE']}; sids={'SRC-YE-CSO-ADMIN-DEFINITION-LEGACY','SRC-YE-NIC-GOVERNORATES-LEGACY','SRC-YE-LAW-31-SOCOTRA-REPORT-2013'}; families['sources']=[L(p) for p in (ROOT/'data/sources').glob('*.json') if L(p).get('id') in sids]; E={r['id']:r for r in e}; findings=[]
 for q in f['units']:
  eid='ENT-YE-'+('CAPITAL-MUNICIPALITY' if q['kind']=='capital_municipality' else 'GOVERNORATE')+'-'+q['code']
  if E.get(eid,{}).get('canonical_name')!=q['name_ar']: findings.append({'severity':'P1','record_id':eid,'message':'fixture identity mismatch'})
 if E.get('ENT-YE-GOVERNORATE-22',{}).get('valid_from')!='2013-12-18': findings.append({'severity':'P1','record_id':'Socotra','message':'Law issuance date mismatch'})
 sample={k:{'population':len(v),'sample_size':len(v),'sample_percentage':100.0,'record_ids':sorted(x['id'] for x in v)} for k,v in families.items()}; write_json(ROOT/'data/review/yemen_review_samples.json',{'schema_version':'2.0.0','country_code':'YE','families':sample}); write_json(ROOT/'reports/yemen_review_samples.json',{'schema_version':'2.0.0','country_code':'YE','families':sample}); n=sum(len(v) for v in families.values()); ok=not findings; result={k:{'sampled':len(v),'passed':len(v) if ok else 0,'failed':0 if ok else len(v),'status':'PASS' if ok else 'FAIL'} for k,v in families.items()}; write_json(ROOT/'reports/yemen_independent_review.json',{'schema_version':'2.0.0','country_code':'YE','status':'PASS' if ok else 'FAIL','p0':0,'critical_p1':len(findings),'method':'Independent full-population comparison against checksum-bound 22-unit legal/statistical fixture, including Amanat type and Socotra law-date boundary.','families':result,'total_sampled':n,'total_passed':n if ok else 0,'findings':findings}); print(n); return 0 if ok else 1
if __name__=='__main__': raise SystemExit(main())
